### ISSUE TITLE
Installation fails on ubuntu18 and mariadb due to utf8mb4

### ISSUE THREAD

**Issue by haterzlin** [FusionAuth/fusionauth-issues#234] opened 2019-07-26 15:37 UTC
### Description 
When I try to install fusionauth on Ubuntu 18.04, installation fails with:
java.sql.SQLSyntaxErrorException: Specified key was too long; max key length is 767 bytes
while trying to create tables in DB. Issue persists despite following instructions on https://fusionauth.io/docs/v1/tech/installation-guide/database

### Steps to reproduce

docker run -p 9011:9011 -it ubuntu
apt install -y mariadb-server curl unzip vim
echo "[client]
default-character-set = utf8mb4

[mysql]
default-character-set = utf8mb4

[mysqld]
character-set-client-handshake = FALSE
character-set-server = utf8mb4
collation-server = utf8mb4_bin" > /etc/mysql/conf.d/fusionauth.cnf

service mysql start
mysql
> create user 'admin'@'%' identified by 'password';
> grant all privileges on *.* to 'admin'@'%' with grant option;
> flush privileges;
> Ctrl+D

cd /opt
sh -c "curl -fsSL https://raw.githubusercontent.com/FusionAuth/fusionauth-install/master/install.sh | sh -s - -z"

vi /opt/fusionauth/config/fusionauth.properties
database.enforce-utf8mb4=false
:wq

/opt/fusionauth/bin/startup.sh
tail -f /opt/fusionauth/logs/fusionauth-app.log

goto http://localhost:9011 in browser, enter admin credentials to mariadb (admin/password) and proceed - there is http 500
Caused by: java.sql.SQLSyntaxErrorException: Specified key was too long; max key length is 767 bytes

**Comment by robotdan** [comment] 2019-07-26 19:23
There are some known issues with MariaDB, but in general it should work for you.

Do you have the rest of that SQL exception? It looks like there are several issues out there with MariaDB and INNODB. 

Such as :
https://github.com/jhipster/generator-jhipster/issues/8604

But I believe this generally would happen when you index a column over 191 characters long. Any column that ends up being index is specifically defined as `VARCHAR(191)` to avoid this issue. 

We can attempt to recreate, but the full exception may assist us as well. 
Thanks!

**Comment by tyduptyler13** [comment] 2019-07-26 19:42
Reproduced the issue, unfortunately the exception is very non specific about which key/column is causing the exception.

[fusionauth-app.log](https://github.com/FusionAuth/fusionauth-issues/files/3437201/fusionauth-app.log)

**Comment by robotdan** [comment] 2019-07-26 19:52
The last insert looks to be into `integrations`

```

-- Integrations
INSERT INTO integrations(data)
  VALUES ('{}');
.  Cause: java.sql.SQLSyntaxErrorException: Specified key was too long; max key length is 767 bytes
	at org.apache.ibatis.jdbc.ScriptRunner.executeFullScript(ScriptRunner.java:133)
	at org.apache.ibatis.jdbc.ScriptRunner.runScript(ScriptRunner.java:108)
	at com.inversoft.maintenance.db.SQLExecutor.executeSQLScriptWithError(SQLExecutor.java:43)
	at com.inversoft.maintenance.db.JDBCMaintenanceModeDatabaseService.createSchema(JDBCMaintenanceModeDatabaseService.java:159)
	at com.inversoft.maintenance.action.MaintenanceModeDatabaseConfigurationAction.post(MaintenanceModeDatabaseConfigurationAction.java:122)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
```

There is no primary key or indexes defined on this table, perhaps MariaDB assumes an index or builds a primary key on this `TEXT` column automatically? 

@tyduptyler13 can you do a describe table? 

Here is the output in MySQL version `5.7.19`

```
> describe integrations;
+-------+------+------+-----+---------+-------+
| Field | Type | Null | Key | Default | Extra |
+-------+------+------+-----+---------+-------+
| data  | text | NO   |     | NULL    |       |
+-------+------+------+-----+---------+-------+
```

**Comment by picklit** [comment] 2019-07-28 21:56
A workaround may be to enable large prefixes.

set global innodb_large_prefix=on;

**Comment by haterzlin** [comment] 2019-07-29 04:57
> A workaround may be to enable large prefixes.
> 
> set global innodb_large_prefix=on;

I tried that before unsuccesfully

**Comment by robotdan** [comment] 2019-07-29 15:36
@haterzlin can you do a describe on the `integrations` table as created in MariaDB? 

```
> describe integrations;
```

**Comment by haterzlin** [comment] 2019-07-30 06:10
@robotdan I suppose last table created was users and next in query was table user_external_ids where id is of type: VARCHAR(191) which is likely cause of error: "max key length is 767 bytes"

```
MariaDB [(none)]> use fusionauth;
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed

MariaDB [fusionauth]> describe integrations;
ERROR 1146 (42S02): Table 'fusionauth.integrations' doesn't exist

MariaDB [fusionauth]> show tables;
+--------------------------+
| Tables_in_fusionauth     |
+--------------------------+
| application_roles        |
| applications             |
| clean_speak_applications |
| email_templates          |
| group_application_roles  |
| groups                   |
| keys                     |
| lambdas                  |
| tenants                  |
| users                    |
| webhooks                 |
| webhooks_applications    |
+--------------------------+
12 rows in set (0.00 sec)

MariaDB [fusionauth]> describe users;
+----------------+--------------+------+-----+---------+-------+
| Field          | Type         | Null | Key | Default | Extra |
+----------------+--------------+------+-----+---------+-------+
| id             | binary(16)   | NO   | PRI | NULL    |       |
| active         | bit(1)       | NO   |     | NULL    |       |
| birth_date     | char(10)     | YES  |     | NULL    |       |
| clean_speak_id | binary(16)   | YES  | MUL | NULL    |       |
| data           | mediumtext   | YES  |     | NULL    |       |
| expiry         | bigint(20)   | YES  |     | NULL    |       |
| first_name     | varchar(255) | YES  |     | NULL    |       |
| full_name      | varchar(255) | YES  |     | NULL    |       |
| image_url      | varchar(255) | YES  |     | NULL    |       |
| insert_instant | bigint(20)   | NO   |     | NULL    |       |
| last_name      | varchar(255) | YES  |     | NULL    |       |
| middle_name    | varchar(255) | YES  |     | NULL    |       |
| mobile_phone   | varchar(255) | YES  |     | NULL    |       |
| parent_email   | varchar(255) | YES  |     | NULL    |       |
| tenants_id     | binary(16)   | NO   | MUL | NULL    |       |
| timezone       | varchar(255) | YES  |     | NULL    |       |
+----------------+--------------+------+-----+---------+-------+
```

to compare with:

```
CREATE TABLE users (
  id             BINARY(16)   NOT NULL,
  active         BIT(1)       NOT NULL,
  birth_date     CHAR(10)     NULL,
  clean_speak_id BINARY(16)   NULL,
  data           MEDIUMTEXT   NULL,
  expiry         BIGINT       NULL,
  first_name     VARCHAR(255) NULL,
  full_name      VARCHAR(255) NULL,
  image_url      VARCHAR(255) NULL,
  insert_instant BIGINT       NOT NULL,
  last_name      VARCHAR(255) NULL,
  middle_name    VARCHAR(255) NULL,
  mobile_phone   VARCHAR(255) NULL,
  parent_email   VARCHAR(255) NULL,
  tenants_id     BINARY(16)   NOT NULL,
  timezone       VARCHAR(255) NULL,
  PRIMARY KEY (id),
  CONSTRAINT users_fk_1 FOREIGN KEY (tenants_id) REFERENCES tenants(id)
)
  ENGINE = innodb
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_bin;
CREATE INDEX users_i_1 ON users(clean_speak_id);
CREATE INDEX users_i_2 ON users(parent_email);

-- External User Ids
CREATE TABLE user_external_ids (
  id              VARCHAR(191) NOT NULL,
  applications_id BINARY(16)   NULL,
  insert_instant  BIGINT       NOT NULL,
  type            SMALLINT     NOT NULL,
  users_id        BINARY(16)   NOT NULL,
  data            TEXT         NULL,
  PRIMARY KEY (id),
  CONSTRAINT user_external_ids_fk_1 FOREIGN KEY (users_id) REFERENCES users(id),
  CONSTRAINT user_external_ids_fk_2 FOREIGN KEY (applications_id) REFERENCES applications(id)
)
  ENGINE = innodb
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_bin;
CREATE INDEX user_external_ids_i_1 ON user_external_ids(type, insert_instant);
CREATE INDEX user_external_ids_i_2 ON user_external_ids(type, users_id, applications_id);
```

**Comment by robotdan** [comment] 2019-07-30 15:30
Any column that ends up as a primary key or has an explicit index we define as `VARCHAR(191)`, the engine should be able to fit that value into the max key length of 767 bytes.  `191 * 4 = 764 bytes`. 

I don't yet understand why MariaDB is failing, it is possible it is inferring an index that we did not intend or define. MySQL does this with FK implicitly, so perhaps something like that is going on, or MariaDB is calculating a max key length different than `191 * 4`. 

We create all tables using `utf8mb4` to ensure we can store full 4 byte unicode. The configuration value in the `fusionauth.properties` is only an option to disable enforcement at startup. On startup we query the database to see if it is configured to allow 4 byte unicode and then log a warning or fail to start depending upon the configuration.

**Comment by haterzlin** [comment] 2019-07-31 06:09
This is nice document describing problem: http://mysql.rjweb.org/doc.php/limits#767_limit_in_innodb_indexes
version with issue: 10.1.40-MariaDB-0ubuntu0.18.04.1 Ubuntu 18.04
version where limit was raised: MariaDB 10.2.2

workaround is to install mysql db instead of mariadb, which version is sufficient in Ubuntu 18

**Comment by robotdan** [comment] 2019-07-31 14:42
I don't think we're on the same page yet..  you are correct the InnoDB engine historically has a limit on the index size of `767` bytes.  (Which has been raised in more recent versions) This is why each column that we define in the FusionAuth schema that is a primary key, or has a unique constraint that will cause it to end up in an index is defined as `VARCHAR(191)`. This `191` character limit ensures we fall under the `767` byte boundary since `191 * 4 = 764`. 

The issue you're encountering is that MariaDB is failing because it says we have an index greater than `767` bytes, even though we have not defined any indexes or primary keys greater than `191` characters.

So, a couple things could be going on:

1. This is a MariaDB bug, seems unlikely, but possible. 
2. The way we are defining our schema is causing an implicit index of some sort that we do not expect and that MySQL is not creating. Specifically the `integrations` table which has a single column of type `TEXT`  - which IF indexed would certainly be greater than `767` bytes. I've read the InnoDB spec and it indicates that if you create a table without a primary key it creates an internal one that is auto-incremented, but it does not use the column itself. 
3. Other? 

If I am able to recreate perhaps we can narrow down the issue, but it does seem to be some sort of compatibility issue between MySQL and MariaDB as it relates to InnoDB indexes.

I hope that helps.

**Comment by LohithBlaze** [comment] 2020-05-22 08:40
@robotdan any implications on functionality of fusionauth by setting the database.mysql.enforce-utf8mb4 = false.

**Comment by robotdan** [comment] 2020-05-22 15:35
@LohithBlaze that will allow FusionAuth to run even when `utf8mb4` is not configured properly. We added that enforcement to ensure the limitation is understood before you turn off the enforcement. 

The implication is that if you attempt to store a 4 byte unicode character the `INSERT` or `UPDATE` request will fail. The initial MySQL UTF-8 support only allowed for 3 byte characters, they then came out with `utf8mb4` to support 4 byte characters. 

For example, many emoji are 4 byte characters, so if you tried to store a piece of text with a smiley such as 😁 it will fail.  The 😁 is a four byte character, `U+1F601` or `\xF0\x9F\x98\x81`. 

Unless you configure MySQL to use `utf8mb4` any character points between `U+10000` and `U+10FFFF` will fail to be stored.

**Comment by robotdan** [comment] 2020-10-21 22:40
Closing, we can track support for MariaDB here: https://github.com/FusionAuth/fusionauth-issues/issues/367

**Closed** 2020-10-21 22:40 UTC
Labels: current limitation, unsupported configuration
