### ISSUE TITLE
es_419 locale code may break UI

### ISSUE THREAD

**Issue by robotdan** [FusionAuth/fusionauth-issues#978] opened 2020-11-10 21:32 UTC
### Description 
This is a new thread from issue https://github.com/FusionAuth/fusionauth-issues/issues/325

Starting a new thread from this comment https://github.com/FusionAuth/fusionauth-issues/issues/325#issuecomment-724972023 by  @Renkon to see if we can track this down.

### Affects versions
Unknown.

### Steps to reproduce
See above links to previous thread. 

### Related
- https://www.localeplanet.com/icu/es-419/index.html
- https://github.com/prime-framework/prime-mvc/issues/4
- https://issues.apache.org/jira/browse/LANG-1312
- https://github.com/apache/commons-lang/blob/master/src/changes/changes.xml#L331

### Related issues
- https://github.com/FusionAuth/fusionauth-issues/issues/1132
- https://github.com/FusionAuth/fusionauth-issues/issues/1165

**Comment by Renkon** [comment] 2020-11-10 22:09
Reproduced under version:
![image](https://user-images.githubusercontent.com/1048587/98739316-dff71080-2387-11eb-86ef-373bd68e43a5.png)

When trying to access admin:
![image](https://user-images.githubusercontent.com/1048587/98739473-2d737d80-2388-11eb-92e0-0e09c4f70239.png)

Workaround: 
Change fusionauth.locale from es_419 to es_AR.

**Comment by robotdan** [comment] 2020-11-10 22:23
Is there anything in the logs when this occurs?

**Comment by Renkon** [comment] 2020-11-10 22:33
didn't find any useful information related to this incident either on fusionauth-app.log nor on fusionauth-search.log

Also checked Chrome console, and there were no errors there either.

**Comment by robotdan** [comment] 2020-11-10 22:34
What platform are you running on? Windows, macOS, Linux, K8s, Docker, etc? I haven't been able to recreate, but perhaps it has something do with the locales supported by the VM when running on a particular platform.

**Comment by Renkon** [comment] 2020-11-10 22:37
CentOS 8.2.2004 - 4.18.0-193.28.1.el8_2.x86_64

**Comment by mooreds** [comment] 2020-12-11 21:29
This also happened here: https://fusionauth.io/community/forum/topic/655/docker-install-ok-cannot-log-in-after

**Comment by robotdan** [comment] 2020-12-11 21:48
I've been unable to recreate, so my guess is that it also has something to do with the underlying host OS and what locales it is supporting.

**Comment by eirikur-grid** [comment] 2021-01-12 11:23
We sometimes see events like these in the FA Event Log. This is with FusionAuth 1.22.1 hosted on FusionAuth Cloud.
```
Lambda invocation exception.

Id: 52c524b7-4638-8777-2c85-9f83fae1b708
Name: Default OpenID Connect Reconcile provided by FusionAuth

com.fasterxml.jackson.databind.JsonMappingException: Invalid locale format: es_419 (through reference chain: io.fusionauth.domain.User["preferredLanguages"]->java.util.ArrayList[0])
```

**Comment by eirikur-grid** [comment] 2021-01-12 12:48
This particular error message "Invalid locale format" is probably originating from `org.apache.commons.lang.LocaleUtils`. I see several mentions of it in https://github.com/apache/commons-lang/blob/master/src/main/java/org/apache/commons/lang3/LocaleUtils.java

It appears that this issue was addressed in 2017. See https://issues.apache.org/jira/browse/LANG-1312
Hopefully, this is a simple matter of updating dependencies.

**Comment by mooreds** [comment] 2021-01-12 13:17
Looks like that fix was released in 3.6 of commons-lang: https://github.com/apache/commons-lang/blob/master/src/changes/changes.xml#L331

**Comment by robotdan** [comment] 2021-01-12 23:43
Thanks for the clues @eirikur-grid & @mooreds . 

Opened a bug against our mvc, I'll pick up the fix provided by Apache and that should fix it. 
https://github.com/prime-framework/prime-mvc/issues/4

**Comment by robotdan** [comment] 2021-01-12 23:57
The fix in prime-mvc fixes part of our issue, the other end is in our JSON `Locale` de-serializer - which will need a similar fix. 

Internal note, see `LocaleDeserializer` in `jackson5`.

**Comment by robotdan** [comment] 2021-01-13 00:02
Related to https://github.com/FusionAuth/fusionauth-internal-issues/issues/81

**Comment by robfusion** [comment] 2021-11-12 15:18
Should be fixed with recent Locale changes

**Closed** 2021-11-19 19:15 UTC
Labels: bug, triage
