### ISSUE TITLE
Missing refresh token when login using python client

### ISSUE THREAD

**Issue by kejvi-doko** [FusionAuth/fusionauth-issues#782] opened 2020-07-30 13:01 UTC
### Description
I have an instance of fusion auth using version 1.17.5. I am using python client to login using from API but I don't get back the `refreshToken` even so I am sending the `applicationId` as described in the documentation.

```python
class LoginUserCommand(ReadCommand):

    def __init__(self, username, password):
        self.username = username
        self.password = password

    def execute(self):

        fa_client = FusionAuthClient(secrets['FUSION_AUTH_API_KEY'], secrets['FUSION_AUTH_BASE_URL'])
        user_may_be_response = fa_client.retrieve_user_by_username(self.username)

        if not user_may_be_response.was_successful():
            return False, False

        login_user_may_be_response = fa_client.login({
            "loginId": self.username,
            "password": self.password,
            "applicationId": secrets['FUSION_AUTH_APP_ID']
        })

        if not login_user_may_be_response.was_successful():
            return False, False

        return login_user_may_be_response.success_response['token'], login_user_may_be_response.success_response['refreshToken']

```

I get the following response:

```json
{
    "token": "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IkxlNXRpMktZVVktLVNCa1JsenVuY0hRajlUWSJ9.eyJleHAiOjE1OTYxMTcxMjQsImlhdCI6MTU5NjExMzUyNCwiaXNzIjoiYWNtZS5jb20iLCJzdWIiOiJjZmQ5YjJiNy01YTQzLTRlY2QtYjE5ZC05ZWZhN2QwOTdiMDUiLCJhdXRoZW50aWNhdGlvblR5cGUiOiJQQVNTV09SRCIsImVtYWlsIjoiaG9ic29uLnJtQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJTbGljZW9mMkQifQ.NSMd5NFY_YGaFKl2dNgtzP8x2B4xldg5GmaF1hN28U9q0NQYz0kMZEnLiNegP8yiISuP5T9UxOXuY2mf38plF9zdjYwkNxtA2x3wLebKPWv9dxDekpCH86fq14UfWJOVNHiG9nT-OrdebvKHJ_aU2CAPpMGNaVqc2pTRfuSbjZagBxqO9gXY9Nfr95LOs4tOGzKcIEpAdxYJ-F9FqeY8GNTKpp2YrwinMY-bX56AUaX04mvFgL7i6A47xfpYwi61SlQ0qYYgMRf9mYW7XZPFxwbn-ieOHkKtb1z9rwhj_1mOJhgVoTUgeycHZgzYXzVs6hV6STUvYVVrDcndj9DLHQ",
    "user": {
        "active": true,
        "birthDate": "1900-01-01",
        "data": {
            "displayName": " "
        },
        "email": "xxxx@xxxx.xxx",
        "firstName": "",
        "fullName": "",
        "id": "cfd9b2b7-5a43-4ecd-b19d-9efa7d097b05",
        "imageUrl": "https://64.media.tumblr.com/tumblr_l7dbl0MHbU1qz50x3o1_500.png",
        "insertInstant": 1331449200000,
        "lastLoginInstant": 1596113524172,
        "lastName": "",
        "middleName": "",
        "passwordChangeRequired": false,
        "passwordLastUpdateInstant": 1596104391038,
        "preferredLanguages": ["en"],
        "tenantId": "adb1f701-afac-4b4a-a512-4409217d22cb",
        "timezone": "America/Denver",
        "twoFactorDelivery": "None",
        "twoFactorEnabled": false,
        "username": "xxxxxx",
        "usernameStatus": "ACTIVE",
        "verified": true
    }
}
```

I also changed the configuration on application/ security section [https://prnt.sc/tr6gu4](https://prnt.sc/tr6gu4)

How can I get the refresh token, have I done anything wrong?

Thanks in advance

**Comment by mooreds** [comment] 2020-08-04 02:33
Your configuration settings look correct. Can you test with this curl command to see if you get the refresh token? I do, but am running against 1.18.4.

```
APIKEY=....

curl -H "Content-type: application/json" -vv -H "Authorization: $APIKEY" https://yourserver/api/login -d '{ "loginId" :  "user@example.com", "applicationId" : "YOURAPPID", "password" : "users password" }'
```

**Comment by robotdan** [comment] 2020-11-11 15:51
If this is still an error, please re-open. Thanks!

**Comment by shostkevych** [comment] 2020-11-30 14:12
Seems that still not working on version 1.21.0, can't get refresh token with enabled security settings for app. Maybe someone else has this issue ? Thanks !

**Comment by mooreds** [comment] 2020-11-30 14:38
@shostkevych do you get the refresh token using the curl command (example here: https://github.com/FusionAuth/fusionauth-issues/issues/782#issuecomment-668345112 ).

That will help us nail down where the issue might be.

**Comment by shostkevych** [comment] 2020-12-03 13:16
@mooreds , yes, just tried again on fresh install of FusionAuth and enabled **Generate Refresh Tokens** on **Login API configuration** section for the app, still missing refresh token.

**Comment by robotdan** [comment] 2020-12-07 15:13
To confirm, you have enabled Refresh Tokens by checking "Generate Refresh Tokens" in the Login API config, and when you make a login request, you're providing an Application Id - and that Application Id is not the FusionAuth app Id (`3c219e58-ed0e-4b18-ad48-f4f92793ae32`), but a separate application?

**Comment by spsaucier** [comment] 2022-01-12 19:10
I'm getting this same issue as well (cURL) -- Generate Refresh Tokens is ticked on the Application -> Security page, and I'm including that client's `applicationId` in the request.

**Comment by mooreds** [comment] 2022-01-18 03:27
@spsaucier can you try on the latest version (1.32)?

**Comment by spsaucier** [comment] 2022-01-18 22:52
@mooreds Just upgraded to 1.32.1 to test, and it appears to still be a problem:

```
curl --location --request POST 'https://......net/api/login' \
--header 'Content-Type: application/json' \
--header 'Accept: application/json, text/plain, */*' \
--data-raw '{
    "loginId": "stephen......",
    "password": "....",
    "applicationId": "58b18750-7b73-4f6c-bd3c-a47b0a5bd9e6"
}'
```

```
{
    "token": "eyJhbGciOiJSU...",
    "user": {
        "active": true,
        "connectorId": "e3306678-a53a-4964-9040-1c96f36dda72",
        "data": {
            "businessId": "f4dc2eeb-ef97-4307-acd9-2f4e5810b69d",
            "capitalUserId": "c9579c4a-2b07-4ac0-b042-aaa527aa25b0",
            "userType": "BUSINESS_OWNER"
        },
        "email": "stephen.....",
        "id": "7442764a-20e9-4f0f-9cbc-ae6e5b5860f7",
        "insertInstant": 1639068057358,
        "lastLoginInstant": 1642546055579,
        "lastUpdateInstant": 1642193132913,
        "passwordChangeRequired": false,
        "passwordLastUpdateInstant": 1639068057388,
        "tenantId": "933328da-3f46-0236-6ec6-4a04a689f99e",
        "twoFactor": {},
        "usernameStatus": "ACTIVE",
        "verified": true
    }
}
```

**Comment by mooreds** [comment] 2022-01-18 23:29
Hmm. Can you please share your application configuration. The easiest way may be to retrieve it via the API and just share the JSON: `curl -H 'Authorization: APIKEY' https://...net/api/application/APPLICATION_UUID`

I will also try to replicate on 1.32.1.

**Comment by mooreds** [comment] 2022-01-18 23:36
I was not able to replicate this issue.

One other thing to make sure of: Is the user registered for the application? If the user is not, then they won't get a refresh token even if you provide the application id.

**Comment by mooreds** [comment] 2022-01-19 19:18
I'm going to close this issue as I believe the documentation update addresses the root cause.

@spsaucier @kejvi-doko if I am incorrect, please re-open.

**Closed by mooreds** 2022-01-19 19:18 UTC
Labels: client-library, triage

**Comment by spsaucier** [comment] 2022-01-19 19:34
Not seeing any blatant issues with my configuration:
```
{
    "application": {
        "accessControlConfiguration": {},
        "active": true,
        "authenticationTokenConfiguration": {
            "enabled": false
        },
        "emailConfiguration": {},
        "formConfiguration": {
            "adminRegistrationFormId": "4602....."
        },
        "id": "58b18....",
        "insertInstant": 1634724714612,
        "jwtConfiguration": {
            "accessTokenKeyId": "bf4fc....",
            "enabled": true,
            "idTokenKeyId": "bf4fc....",
            "refreshTokenExpirationPolicy": "SlidingWindow",
            "refreshTokenTimeToLiveInMinutes": 43200,
            "refreshTokenUsagePolicy": "Reusable",
            "timeToLiveInSeconds": 3600
        },
        "lambdaConfiguration": {
            "accessTokenPopulateId": "03a5....."
        },
        "lastUpdateInstant": 1642015596144,
        "loginConfiguration": {
            "allowTokenRefresh": true,
            "generateRefreshTokens": true,
            "requireAuthentication": false
        },
        "multiFactorConfiguration": {
            "email": {},
            "sms": {}
        },
        "name": "Capital Dev Environment",
        "oauthConfiguration": {
            "clientAuthenticationPolicy": "NotRequired",
            "clientId": "58b1.....",
            "clientSecret": "d0rW....",
            "debug": false,
            "enabledGrants": [
                "authorization_code",
                "refresh_token",
                "password"
            ],
            "generateRefreshTokens": true,
            "logoutBehavior": "AllApplications",
            "proofKeyForCodeExchangePolicy": "NotRequired",
            "requireClientAuthentication": false,
            "requireRegistration": false
        },
        "passwordlessConfiguration": {
            "enabled": false
        },
        "registrationConfiguration": {
            "birthDate": {
                "enabled": false,
                "required": false
            },
            "confirmPassword": false,
            "enabled": false,
            "firstName": {
                "enabled": false,
                "required": false
            },
            "fullName": {
                "enabled": false,
                "required": false
            },
            "lastName": {
                "enabled": false,
                "required": false
            },
            "loginIdType": "email",
            "middleName": {
                "enabled": false,
                "required": false
            },
            "mobilePhone": {
                "enabled": false,
                "required": false
            },
            "type": "basic"
        },
        "registrationDeletePolicy": {
            "unverified": {
                "enabled": false,
                "numberOfDaysToRetain": 120
            }
        },
        "samlv2Configuration": {
            "debug": false,
            "enabled": false,
            "logout": {
                "behavior": "AllParticipants",
                "requireSignedRequests": false,
                "singleLogout": {
                    "enabled": false,
                    "xmlSignatureC14nMethod": "exclusive_with_comments"
                },
                "xmlSignatureC14nMethod": "exclusive_with_comments"
            },
            "requireSignedRequests": false,
            "xmlSignatureC14nMethod": "exclusive_with_comments",
            "xmlSignatureLocation": "Assertion"
        },
        "state": "Active",
        "tenantId": "933328da....",
        "unverified": {
            "behavior": "Allow"
        },
        "verificationStrategy": "ClickableLink",
        "verifyRegistration": false
    }
}
```

**Comment by mooreds** [comment] 2022-01-19 20:32
I think that OAuth honors the scope presented, per the spec (if you present `offline_access` we'll give you a refresh token) but the login API doesn't have scopes and relies on user and application configuration.

Glad you figured it out!
