### ISSUE TITLE
See prompt for using webauthn even though I've never registered my FireFox browser

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-issues#2076] opened 2023-01-25 16:43 UTC
### Description 

I see a prompt to re-authenticate with webauthn when I go to the sandbox, even though I've never registered a passkey.

### Affects versions

1.42.1

### Steps to reproduce

* set up a passkey for the sandbox@fusionauth.io user using chrome
* go to sandbox.fusionauth.io using Firefox
* prompted with a list of passkeys set up for the sandbox user

### Expected behavior

I wouldn't expect to see a list of passkeys until I've set up at least one on this browser, and preferably only see the passkeys associated with this browser (if I set it up on chrome on my phone, will I see it on safari on my computer? seems weird to show me that, since I can't possibly use it).

### Screenshots

The first screen I see when visiting sandbox.fusionauth.io in FF:

![image](https://user-images.githubusercontent.com/91825/214620926-8f32229e-6505-4cc4-9abb-4314f0a74200.png)

The screen I see when visiting sandbox.fusionauth.io in Chrome, after I've logged in:
![image](https://user-images.githubusercontent.com/91825/214622043-b8fc4263-607d-4a68-bf94-c6d88af80cbc.png)

### Platform

Firefox 108.02 on Windows 10.

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

### Additional context

If I visit the same page (https://sandbox.fusionauth.io/) with chrome or MS edge, I don't see this behavior initially, though I do see other keys after I login with username/password. (Maybe the latter is expected, since the sandbox user has passkeys associated with them?)

Note that the sandbox is reset nightly, so by the time you evaluate this issue, the screenshots will have changed.

FF has 7% of desktop marketshare: https://backlinko.com/browser-market-share

**Comment by robotdan** [comment] 2023-01-31 00:22
This seems like it would have to be working as designed since the only way this can happen is if we find a cookie, so perhaps Firefox is sync'ing cookies.

**Comment by mooreds** [comment] 2023-01-31 01:31
hmmm. Next time I see it I'll look and see what cookies are present.

**Comment by andrewpai** [comment] 2024-12-11 18:36
Closing, as this is working as intended. We provide the list of passkeys registered by the user and are not trying to interact with the authenticator here.

**Closed by andrewpai** 2024-12-11 18:36 UTC
Labels: triage
