### ISSUE TITLE
Audit log does not show action that have been made from the API

### ISSUE THREAD

**Issue by blanchonvincent** [FusionAuth/fusionauth-issues#145] opened 2019-04-25 09:19 UTC
Here an example of our audit log:

<img width="1258" alt="Screen Shot 2019-04-25 at 1 16 42 PM" src="https://user-images.githubusercontent.com/1580512/56724676-86ef6980-675c-11e9-9006-cdc2b43085d6.png">

Since so far almost 100% of our actions come from the API, we have almost nothing in our Audit Logs (except the actions related to users in FusionAuth app)... is there a chance to record as well the actions made from the API?

**Comment by robotdan** [comment] 2019-04-26 00:48
When making requests via the UI, we audit our own API requests by using the Audit API. You can audit anything you like using the API. 

https://fusionauth.io/docs/v1/tech/apis/audit-logs#add-an-entry-to-the-audit-log

We have discussed providing automatic auditing of the API through configuration. The longer term plan is to audit the API requests (optionally) once the API request can be made using a JWT issued by FusionAuth. This would allow us to audit the request and tie it to a user because the JWT will identify the caller as a user and not just an API key.

**Comment by blanchonvincent** [comment] 2019-04-28 04:37
@robotdan ok I got the idea.

`We have discussed providing automatic auditing of the API through configuration` that would be amazing :)

**Comment by mooreds** [comment] 2020-07-09 17:34
See also https://github.com/FusionAuth/fusionauth-issues/issues/507

**Comment by robotdan** [comment] 2021-08-31 00:03
This is working as designed, so I will close this one out. We do have an open issue to audit all API requests, or possibly per API key. 

Related issues:
- https://github.com/FusionAuth/fusionauth-issues/issues/507
- https://github.com/FusionAuth/fusionauth-issues/issues/1321

**Closed by robotdan** 2021-08-31 00:03 UTC

**Comment by shortstack** [comment] 2022-05-02 21:40
+1 would like to have auditing on API endpoints instead of adding manually within applications
