### ISSUE TITLE
Unable to use kickstart when installing via docker

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-issues#1816] opened 2022-08-10 03:05 UTC
### Description 

I have a kickstart file, but kickstart seems to try to run before FusionAuth is ready. See stack trace.

### Affects versions

1.37.0

### Steps to reproduce

Set up a kickstart file. You can use a minimal one. Set up docker to use the kickstart file:

```
{
  "variables": {
    "adminEmail": "admin@fusionauth.io",
    "password": "password",
    "defaultTenantId": "30663132-6464-6665-3032-326466613934"
  },
  "apiKeys": [
    {
      "key": "bf69486b-4733-4470-a592-f1bfce7af580",
      "description": "Standard development API key"
    }
  ],
  "requests": [
    {
      "method": "POST",
      "url": "/api/application/85a03867-dccf-4882-adde-1a79aeec50df",
      "body": {
        "application": {
          "name": "Pied Piper",
          "roles": [
            {
              "name": "dev"
            },
            {
              "name": "ceo"
            },
            {
              "name": "intern"
            }
          ]
        }
      }
    }
  ]
}

```

Start up the docker image: `docker compose up`.

See the exception:

```
fusionauth_1  | 2022-08-10 03:02:09.999 AM ERROR io.fusionauth.api.service.system.kickstart.KickstartRunner - Failed to execute request to [POST][/api/application/85a03867-dccf-4882-adde-1a79aeec50df] Status [-1]
fusionauth_1  | Request body:
fusionauth_1  | {
fusionauth_1  |   "application" : {
fusionauth_1  |     "name" : "Pied Piper",
fusionauth_1  |     "roles" : [ {
fusionauth_1  |       "name" : "dev"
fusionauth_1  |     }, {
fusionauth_1  |       "name" : "ceo"
fusionauth_1  |     }, {
fusionauth_1  |       "name" : "intern"
fusionauth_1  |     } ]
fusionauth_1  |   }
fusionauth_1  | }
fusionauth_1  | 2022-08-10 03:02:09.999 AM ERROR io.fusionauth.api.service.system.kickstart.KickstartRunner - Exception returned
fusionauth_1  | java.net.ConnectException: Connection refused
fusionauth_1  | 	at java.base/sun.nio.ch.Net.pollConnect(Native Method)
fusionauth_1  | 	at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:672)
fusionauth_1  | 	at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:542)
fusionauth_1  | 	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:597)
fusionauth_1  | 	at java.base/java.net.Socket.connect(Socket.java:633)
fusionauth_1  | 	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:178)
fusionauth_1  | 	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:498)
fusionauth_1  | 	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:603)
fusionauth_1  | 	at java.base/sun.net.www.http.HttpClient.<init>(HttpClient.java:246)
fusionauth_1  | 	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:351)
fusionauth_1  | 	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:373)
fusionauth_1  | 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1309)
fusionauth_1  | 	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1287)
fusionauth_1  | 	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1128)
fusionauth_1  | 	at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:1057)
fusionauth_1  | 	at com.inversoft.rest.RESTClient.go(RESTClient.java:387)
fusionauth_1  | 	at io.fusionauth.api.service.system.kickstart.KickstartRunner.run(KickstartRunner.java:137)
fusionauth_1  | 	at java.base/java.lang.Thread.run(Thread.java:833)
fusionauth_1  | 2022-08-10 03:02:10.055 AM INFO  org.primeframework.mvc.netty.PrimeHTTPServer - Starting FusionAuth HTTP server on port [9011]
fusionauth_1  | 2022-08-10 03:02:10.110 AM INFO  org.primeframework.mvc.netty.PrimeHTTPServer - Starting FusionAuth HTTP loopback server on port [9012]
```

### Expected behavior

You can use kickstart.

### Platform

```
% docker compose version
Docker Compose version v2.7.0
```

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

### Additional context

The setup wizard screen appears just fine (asking me to set up the first admin user).

Interestingly, the API key from that kickstart file was added to the instance, but not the application.

**Comment by robotdan** [comment] 2022-08-11 00:01
Is this a duplicate of https://github.com/FusionAuth/fusionauth-issues/issues/1817 ?

**Comment by robotdan** [comment] 2022-08-11 00:37
Nm, recreated.

**Closed** 2022-08-11 21:01 UTC
Labels: bug
