### ISSUE TITLE
Add Forgot Username to themed pages

### ISSUE THREAD

**Issue by robotdan** [FusionAuth/fusionauth-issues#2937] opened 2024-12-04 22:11 UTC
### Description
We've had a customer ask for a "Forgot username" workflow to the hosted login pages. 

The use case is as follows:
1. The customer has many legacy users that have traditionally used usernames to login. 
2. The user's do have a phone or email address. 
3. Even though you could log in with email, in practice, forgetting a username likely results in a call to the support desk. 
4. Since this does not exist in the product, they have had to build it. 

In practice, the username may be a username, or it could be an account number. 

The ideal solution for this customer would be:
1. Add the ability to add a link to the login page or the registration page - named "Forgot username". 
2. This may mean we write the feature, and the themed page but by default maybe we don't display it, but it could be added to an advanced theme, or turned on by a theme policy or an application policy.
3. The themed page would collect an `loginId` of `email`, `phoneNumber` or some verifiable identity that we would allow us to send something to the user.
4. We could accept this input and look up the user, if they have a primary `username` we would send an email to the user. This would be a terminal operation. 
5. We could optionally send all usernames in the email if the user has more than one defined. 

### Duplicate
- https://github.com/FusionAuth/fusionauth-issues/issues/2217

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

**Comment by mooreds** [comment] 2024-12-04 23:25
Is this a duplicate of https://github.com/FusionAuth/fusionauth-issues/issues/2217 , with maybe more details?

**Comment by robotdan** [comment] 2024-12-10 21:22
Closing as duplicate of #2217

**Closed** 2024-12-30 15:57 UTC
