### ISSUE TITLE
Add new role for viewing login records

### ISSUE THREAD

**Issue by envopetter** [FusionAuth/fusionauth-issues#2912] opened 2024-11-04 09:17 UTC
### Problem
Viewing login records is essential for keeping track of what locations the our users are actually logging in from, and is sometimes used for determining geo location blocking for countries and locations we don't accept logins from. As of now, only the System manager and Admin roles has the ability to view these records, but they are not roles we want to assign people that are responsible for viewing and monitoring activities in FusionAuth only. However, on the Dashboard -> Home page, they can actually view the "recent login records",  but when clicking the "view all login records" link on the bottom, they are not able to view it.

### Solution
Add another role for viewing all the login records, so that we can permit certain users to view them, without granting them more permissions than absolutely needed.

### Alternatives/workarounds
-

### Additional context
Roles the viewers have today which let's them view Recent Logins, but not All login records.
![image](https://github.com/user-attachments/assets/48aea0d8-07e7-4b2f-88dc-158e258bddbe)

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by mooreds** [comment] 2024-11-04 21:48
@envopetter is this a duplicate of https://github.com/FusionAuth/fusionauth-issues/issues/2900?

**Comment by envopetter** [comment] 2024-11-05 11:06
> @envopetter is this a duplicate of #2900?

Yes, I seem to have missed that one, sorry. I upvoted the other issue now and hope you'll look into it.

**Comment by mooreds** [comment] 2024-11-05 15:54
no worries @envopetter . 

going to close this out as a duplicate.

**Closed by mooreds** 2024-11-05 15:54 UTC
Labels: duplicate, enhancement
