### ISSUE TITLE
Forgot Password Workflow Bug

### ISSUE THREAD

**Issue by jobannon** [FusionAuth/fusionauth-issues#1989] opened 2022-12-05 18:06 UTC
### Description 
User is displayed a message 
```
Oops. It looks like you've gotten here by accident. Please return to your application and log in to begin the authorization sequence
```
When starting the forgot password workflow via API.

### Affects versions
Latest

### Steps to reproduce
1. Call the forgot password API *without* state parameters
```
curl --request POST \
  --url https://local.fusionauth.io/api/user/forgot-password \
  --header 'Authorization: bf69486b-4733-4470-a592-f1bfce7af580 ' \
  --header 'Content-Type: application/json' \
  --data '{
    "loginId": "joshua@fusionauth.io",
    "applicationId": "85a03867-dccf-4882-adde-1a79aeec50df",
}'
```
2. Click the link (stock link shipped with the latest version of FusionAuth)
3. See the error, but are allowed to complete 2FA and update the password.

### Expected behavior
This is unclear to me. 

But in the event that we have a user that wants to use the Forgot Password API and land on this hosted forgot password page, if they do not supply us a `state` object, we may behave poorly (as seen).  We make certain assumptions about how we arrived on this page (we assume that we arrived based on a user clicking the forgot password link from a hosted page).

### Screenshots
<img width="477" alt="image" src="https://user-images.githubusercontent.com/16090626/205711011-3f50aea1-3efd-48e6-a45e-659cef57493a.png">

### Platform
(Please complete the following information)
Dev Box, latest version.  

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

related ticket - 72968

**Comment by lyleschemmerling** [comment] 2022-12-08 22:57
@jobannon I was not able to reproduce this. Sending the password reset email to my users locally did not hit this. I am going to close as cannot reproduce but if you think it is still a problem could you provide the link from the email that landed you on this page?

**Comment by jobannon** [comment] 2022-12-12 18:51
@robotdan @lyleschemmerling 

https://www.loom.com/share/fb3d3eb82ae74e2fb0dfec5c1aa5836f

Link as emailed in mailcatcher
 
```
To change your password click on the following link.
http://localhost:9011/password/change/uJVmrCGkW3sTaPNL3Vipty_ckCQ5ccvrZlyCmovHPHA?client_id=21c3f299-aea1-4269-aef0-a861982bc0a6&tenantId=f0c5d836-958b-bbec-53ed-77c92b268de5

- FusionAuth Admin
```

email template text

```
[#setting url_escaping_charset="UTF-8"]
To change your password click on the following link.

  [#-- The optional 'state' map provided on the Forgot Password API call is exposed in the template as 'state'.
       If we have an application context, append the client_id to ensure the correct application theme when applicable.
  --]
[#assign url = "http://localhost:9011/password/change/${changePasswordId}?client_id=${(application.oauthConfiguration.clientId)!''}&tenantId=${user.tenantId}" /]
[#list state!{} as key, value][#if key != "tenantId" && key != "client_id" && value??][#assign url = url + "&" + key?url + "=" + value?url/][/#if][/#list]

${url}

- FusionAuth Admin

```

email template HTML

```
[#setting url_escaping_charset="UTF-8"]
To change your password click on the following link.
<p>
  [#-- The optional 'state' map provided on the Forgot Password API call is exposed in the template as 'state'.
       If we have an application context, append the client_id to ensure the correct application theme when applicable.
  --]
  [#assign url = "http://localhost:9011/password/change/${changePasswordId}?client_id=${(application.oauthConfiguration.clientId)!''}&tenantId=${user.tenantId}" /]
  [#list state!{} as key, value][#if key != "tenantId" && key != "client_id" && value??][#assign url = url + "&" + key?url + "=" + value?url/][/#if][/#list]
  <a href="${url}">${url}</a>
</p>
- FusionAuth Admin
```

**Comment by lyleschemmerling** [comment] 2022-12-13 19:15
can repro. Re-opening

**Comment by robotdan** [comment] 2022-12-14 13:58
Internal:
- https://github.com/FusionAuth/fusionauth-app/pull/165

**Closed** 2023-02-17 06:38 UTC
Labels: bug
