### ISSUE TITLE
Allow FusionAuth to access AWS resources?

### ISSUE THREAD

**Issue by jsmwoolf** [FusionAuth/fusionauth-issues#101] opened 2019-03-28 21:11 UTC
### Description
So far, I'm liking the authentication software.  I do have a question though.  How can I allow FusionAuth users to access AWS resources (S3, DynamoDB, etc.)?  Can I do this by creating a new provider in IAM?  My instance is currently running on an EC2 instance.

### Additional context

https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_providers_enable-console-saml.html

It may take some custom work in FusionAuth to make this work because it seems like they have a custom (non spec) implementation of a SAML login.

**Comment by robotdan** [comment] 2019-03-28 23:13
Hi @jsmwoolf thanks for the suggestion. 

I think this should work.  AWS supports SAML and OpenID Connect Identity Providers. 

I just created one myself, haven't tried using it yet. 

Here is how I created it: (you'll need to be using version 1.4.0 or later since AWS will use the JWKS endpoint to verify the configuration)

1. In FusionAuth, create a new Application called `AWS IAM` (or whatever you'd like to call it)
2. Update the newly created application JWT configuration to use the signing algorithm `RSA using SHA-256` (RS256), and then click on Generate new keypair. Now this FusionAuth application is configured to use an RSA keypair to sign and verify JWTs. 
3.  Navigate to IAM in AWS Console
4. Select Identity Providers from the left nav
5. Create New IDP of type OpenID Connect
6. Specify the public URL of FusionAuth (must be https). For example `https://login-acme.com`
7. Specify the `aud` claim using the value from the `Client Id` field on the OAuth tab in your FusionAuth application configuration. 
8. Click `Next Step`

I don't know much about using AWS IAM w/ external Identity Providers, so what you do with it after that I don't know. :-) 

On the FusionAuth side of things, you'll likely need to create some roles for the application, and finish the OAuth configuration for a logout URL and registered redirect URLs. I don't know what those values would be for you.

**Comment by jsmwoolf** [comment] 2019-04-03 04:39
Thank you for the steps.

The issue now is trying to apply SSL against my EC2 instance.  I've been looking on how to do this, but most help guides either refer to ELB or applying it against an Apache HTTPD, Nginx, or IIS server on EC2.  I'm not sure what kind of server framework FusionAuth uses, though I suspect Tomcat since it runs on the JVM.  Any idea how to do this?

Without it, I cannot test out the steps above.

**Comment by robotdan** [comment] 2019-04-04 03:09
The easiest way to set up SSL will be to use Apache + Let's Encrypt. 

https://certbot.eff.org/
https://httpd.apache.org/docs/2.4/vhosts/examples.html

An example AJP proxy configuration may look something like:

```
<VirtualHost *:80>
  RewriteEngine On
  RewriteRule ^/(.*) https://%{HTTP_HOST}/$1 [NC,R=301,L]
</VirtualHost>

<VirtualHost *:443>
  ServerName login.acme.com

  ProxyPass / ajp://localhost:9019/ retry=1
  ProxyPassReverse / ajp://localhost:9019/ retry=1

  Header set Access-Control-Allow-Origin "*"
</VirtualHost>
```

This config does not have SSL enabled. If you configure Apache this far, and then run the Let's Encrypt Certbot, it will configure SSL for you from command line. Once the SSL certs are in place you'll have a few extra lines in the `:443` host configuration. 

Such as:

```
<VirtualHost *:443>
  ServerName login.acme.com

  SSLEngine On
  SSLCertificateFile /etc/letsencrypt/live/login.acme.com/cert.pem
  SSLCertificateKeyFile /etc/letsencrypt/live/login.acme.com/privkey.pem
  Include /etc/letsencrypt/options-ssl-apache.conf
  SSLCertificateChainFile /etc/letsencrypt/live/login.acme.com/chain.pem

  ProxyPass / ajp://localhost:9019/ retry=1
  ProxyPassReverse / ajp://localhost:9019/ retry=1

  Header set Access-Control-Allow-Origin "*"
</VirtualHost>
```

You don't have to use an AJP proxy, you can use a standard HTTP proxy.

**Comment by jsmwoolf** [comment] 2019-04-04 23:20
Thanks for the info, I do have some additional questions:

- Would I configure SSL before setting up FusionAuth?
- Would I enable TLS when first setting up FusionAuth?
- Where do I put the configuration?  The FusionAuth server(s) will not be in the same place as the web app.  This is just a test environment.

**Comment by robotdan** [comment] 2019-04-05 03:37
> Would I configure SSL before setting up FusionAuth?

Totally up to you, if you configure it through Apache as an example, you can set this up whenever you'd like. 

> Would I enable TLS for database communication when first setting up FusionAuth?

This is un-related to the configuration I'm referring to - but you can use certainly use an SSL JDBC connection. 

> Why not just set up SSL for Tomcat? The FusionAuth server(s) will not be in the same place as the web app. This is just a test environment. I can maybe understand to set up AJP in a production environment.

In theory you could configure Tomcat to use SSL. We ship Tomcat with FusionAuth and any changes you make to the `server.xml` will not be persisted across an upgrade. 

You will want to host any public URL for FusionAuth using `https` on port `443`.  In order to bind to port `443` you would have to run the service as `root`.  FusionAuth runs under a non-privileged user by design which is why we do not bind to a well known port such as `443`. 

The common pattern used to expose a web service using TLS is to utilize Apache or Nginx. There are a lot of good resources available on the web for configuring a proxy in this way.

**Comment by mooreds** [comment] 2020-09-10 11:56
Took a look at this. There are a couple of different ways to use identity providers in AWS. Probably the most interesting one is single sign on using SAML https://docs.aws.amazon.com/singlesignon/latest/userguide/manage-your-identity-source-idp.html 

Another interesting option is using FusionAuth as an identity provider for a given role, as documented here: https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_providers.html (which can be oidc or saml). 

Got partway through setting up the latter, but still need to test it end to end.

**Comment by jobelenus** [comment] 2021-05-04 20:18
@mooreds I am curious if there is any support for "linking" a User or Group in FusionAuth (where a customer brings their IdP) to an AWS IAM user/role? Essentially: "FusionAuth UserA should be seen in AWS as IAM User A"? Let me know if I'm making any sense!

**Comment by mooreds** [comment] 2021-05-04 21:32
So it looks like if you are using the identity provider functionality, you assign all users from one identity provider a single role: https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_create_for-idp.html

That role of course can have dynamic elements in its permissions https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_variables.html but I don't see anything about mapping between AWS roles and the roles from the IdP. 

If you have an AWS TAM, I'd love to hear their take. In fact I might file an issue myself.

**Comment by robotdan** [comment] 2021-08-30 23:38
Planning to close this one out. 

If there is something missing in FusionAuth that prevents it from successfully being configured an IdP in AWS to support access to other AWS resources, please do re-open and let us know what is missing so we can review further. 

Thanks!

**Closed by robotdan** 2021-08-30 23:38 UTC
Labels: enhancement, documentation
