### ISSUE TITLE
Trust Challenge Required with Forgot Password Flow when MFA is enabled on User

### ISSUE THREAD

**Issue by jobannon** [FusionAuth/fusionauth-issues#2024] opened 2022-12-17 01:45 UTC
### Description 
Trust Challenge Required with Forgot Password Flow (documentation states this is optional) to allow an MFA user to step up trust and change password.  

### Affects versions
1.42.0

#### Sad Path 🔴 
_________________________________________________________________

1️⃣ 🔴  Forgot Password API (`/api/user/forgot-password`)

<details>
<summary>request</summary>

```
curl --request POST \
  --url https://local.fusionauth.io/api/user/forgot-password \
  --header 'Authorization: bf69486b-4733-4470-a592-f1bfce7af580' \
  --header 'Content-Type: application/json' \
  --data '{
	"loginId": "joshua@fusionauth.io",
	"applicationId": "85a03867-dccf-4882-adde-1a79aeec50df"
}'
```
</details> 

<details>
<summary>response</summary>

```
{
	"changePasswordId": "Awof3AJer-zd_1RUTdJxuqhwHRt_TTxsBFyiBsnM3TI"
}
```
</details>

2️⃣  🔴 Start 2FA. Get Trust (`/api/two-factor/start`)

<details>
<summary>request</summary>

```
curl --request POST \
  --url https://local.fusionauth.io/api/two-factor/start \
  --header 'Authorization: bf69486b-4733-4470-a592-f1bfce7af580' \
  --header 'Content-Type: application/json' \
  --data '{
	"applicationId": "85a03867-dccf-4882-adde-1a79aeec50df",
	"loginId": "joshua@fusionauth.io",
	"state": {},
	"userId": "c85997f1-3377-4687-8c75-c606c167cc8d"
}'
```
</details>

<details>
<summary>response</summary>

```
{
	"code": "143620",
	"methods": [
		{
			"authenticator": {
				"algorithm": "HmacSHA1",
				"codeLength": 6,
				"timeStep": 30
			},
			"id": "CBCN",
			"method": "authenticator"
		}
	],
	"twoFactorId": "VLG3R-fJ36sSz4FmO3No-svBdVMXKbz-r5cgvSGa3Uc"
}
```
</details>

3️⃣ 🔴  Login (`/api/two-factor/login`)

<details>
<summary>request</summary>

```
curl --request POST \
  --url https://local.fusionauth.io/api/two-factor/login \
  --header 'Content-Type: application/json' \
  --data '{
  "code": "143620",
  "twoFactorId": "VLG3R-fJ36sSz4FmO3No-svBdVMXKbz-r5cgvSGa3Uc",
  "userId": "c85997f1-3377-4687-8c75-c606c167cc8d",
  "applicationId": "85a03867-dccf-4882-adde-1a79aeec50df",
   "trustComputer": true
}
```
</details>

<details>
<summary>response</summary>

```
{
	"token": "redacted",
	"tokenExpirationInstant": 1671066745609,
	"trustToken": "VK5K-hE1r1jLkxAUSFWc04R8c6coLhYRZuEJgplCvXI",
	"twoFactorTrustId": "9TJdnz4BVMkGCthhcg24d5ses-sQVMw9yPChZ6VXtF8",
	"user": {
		"active": true,
		"birthDate": "1980-10-17",
		"connectorId": "e3306678-a53a-4964-9040-1c96f36dda72",
		"data": {},
		"email": "joshua@fusionauth.io",
		"id": "c85997f1-3377-4687-8c75-c606c167cc8d",
		"insertInstant": 1668481619240,
		"lastLoginInstant": 1671063145604,
		"lastUpdateInstant": 1670541780184,
		"memberships": [],
		"passwordChangeRequired": false,
		"passwordLastUpdateInstant": 1670969379307,
		"preferredLanguages": [],
		"registrations": [
			{
				"applicationId": "85a03867-dccf-4882-adde-1a79aeec50df",
				"data": {
					"bazbaz": "b",
					"foo": "b"
				},
				"id": "b338c7f5-665d-4cfd-8874-06f047e9f082",
				"insertInstant": 1668481626382,
				"lastLoginInstant": 1671063145604,
				"lastUpdateInstant": 1670541780237,
				"preferredLanguages": [],
				"roles": [],
				"tokens": {},
				"usernameStatus": "ACTIVE",
				"verified": true
			}
		],
		"tenantId": "30663132-6464-6665-3032-326466613934",
		"twoFactor": {
			"methods": [
				{
					"authenticator": {
						"algorithm": "HmacSHA1",
						"codeLength": 6,
						"timeStep": 30
					},
					"id": "CBCN",
					"method": "authenticator"
				}
			],
			"recoveryCodes": []
		},
		"uniqueUsername": "some",
		"username": "some",
		"usernameStatus": "ACTIVE",
		"verified": true
	}
}
```
</details>

4️⃣ 🔴  Use trust to change the password (fail) (`/api/user/change-password`)

<details>
<summary>request</summary>

```
curl --request POST \
  --url https://local.fusionauth.io/api/user/change-password \
  --header 'Content-Type: application/json' \
  --data '{
  "applicationId": "85a03867-dccf-4882-adde-1a79aeec50df",
   "changePasswordId": "Awof3AJer-zd_1RUTdJxuqhwHRt_TTxsBFyiBsnM3TI",
  "currentPassword": "password",
  "loginId": "joshua@fusionauth.io",
  "password": "password",
	"trustToken": "VK5K-hE1r1jLkxAUSFWc04R8c6coLhYRZuEJgplCvXI"
}
```
</details>

<details>
<summary>response </summary>

```
{
	"fieldErrors": {},
	"generalErrors": [
		{
			"code": "[TrustTokenRequired]",
			"message": "This request requires a Trust Token. Use the Start Two-Factor API to obtain a Trust Token required to complete this request."
		}
	]
}
```
</details>

#### Success Path 🟢 

__________________________________________________

1️⃣  🟢 Forgot Password API (`/api/user/forgot-password`)

<details>
<summary>request</summary>

```
curl --request POST \
  --url https://local.fusionauth.io/api/user/forgot-password \
  --header 'Authorization: bf69486b-4733-4470-a592-f1bfce7af580' \
  --header 'Content-Type: application/json' \
  --data '{
	"loginId": "joshua@fusionauth.io",
	"applicationId": "85a03867-dccf-4882-adde-1a79aeec50df"
}'
```
</details> 

<details>
<summary>response</summary>

```
{
	"changePasswordId": "k95gcs11PGNQ_fUGFUluDpthI0j6aMlN_x9eAs5ONxc"
}
```
</details>

2️⃣  🟢 Start 2FA. Get Trust (`/api/two-factor/start`)

<details>
<summary>request</summary>

```
curl --request POST \
  --url https://local.fusionauth.io/api/two-factor/start \
  --header 'Authorization: bf69486b-4733-4470-a592-f1bfce7af580' \
  --header 'Content-Type: application/json' \
  --data '{
	"applicationId": "85a03867-dccf-4882-adde-1a79aeec50df",
	"loginId": "joshua@fusionauth.io",
	"state": {},
	"trustChallenge": "moo",
	"userId": "c85997f1-3377-4687-8c75-c606c167cc8d"
}'

```
</details>

<details>
<summary>response</summary>

```
{
	"code": "545832",
	"methods": [
		{
			"authenticator": {
				"algorithm": "HmacSHA1",
				"codeLength": 6,
				"timeStep": 30
			},
			"id": "CBCN",
			"method": "authenticator"
		}
	],
	"twoFactorId": "G-KqoqTBXon_OqyO30zWWJsrQ3ps3bEZal3P8PaKrwc"
}
```
</details>

3️⃣ 🟢 Login (`/api/two-factor/login`)

<details>
<summary>request</summary>

```
curl --request POST \
  --url https://local.fusionauth.io/api/two-factor/login \
  --header 'Content-Type: application/json' \
  --data '{
  "code": "545832",
  "twoFactorId": "G-KqoqTBXon_OqyO30zWWJsrQ3ps3bEZal3P8PaKrwc",
  "userId": "c85997f1-3377-4687-8c75-c606c167cc8d",
  "applicationId": "85a03867-dccf-4882-adde-1a79aeec50df",
  "trustComputer": true
}'
```
</details>

<details>
<summary>response</summary>

```
{
	"token": "redacted",
	"tokenExpirationInstant": 1671243300318,
	"trustToken": "DsHrN0xbdPW6Nf3lf3-Su0kMXOH3NgGPzY6KWJXEMok",
	"twoFactorTrustId": "syy-x_HQjwgK5qTIR4ZsWgnxXduqxdwy_omvbgbDaSo",
	"user": {
		"active": true,
		"birthDate": "1980-10-17",
		"connectorId": "e3306678-a53a-4964-9040-1c96f36dda72",
		"data": {},
		"email": "joshua@fusionauth.io",
		"id": "c85997f1-3377-4687-8c75-c606c167cc8d",
		"insertInstant": 1668481619240,
		"lastLoginInstant": 1671239700314,
		"lastUpdateInstant": 1670541780184,
		"memberships": [],
		"passwordChangeRequired": false,
		"passwordLastUpdateInstant": 1670969379307,
		"preferredLanguages": [],
		"registrations": [
			{
				"applicationId": "85a03867-dccf-4882-adde-1a79aeec50df",
				"data": {
					"bazbaz": "b",
					"foo": "b"
				},
				"id": "b338c7f5-665d-4cfd-8874-06f047e9f082",
				"insertInstant": 1668481626382,
				"lastLoginInstant": 1671239700314,
				"lastUpdateInstant": 1670541780237,
				"preferredLanguages": [],
				"roles": [],
				"tokens": {},
				"usernameStatus": "ACTIVE",
				"verified": true
			}
		],
		"tenantId": "30663132-6464-6665-3032-326466613934",
		"twoFactor": {
			"methods": [
				{
					"authenticator": {
						"algorithm": "HmacSHA1",
						"codeLength": 6,
						"timeStep": 30
					},
					"id": "CBCN",
					"method": "authenticator"
				}
			],
			"recoveryCodes": []
		},
		"uniqueUsername": "some",
		"username": "some",
		"usernameStatus": "ACTIVE",
		"verified": true
	}
}
```
</details>

4️⃣ 🟢 Use trust to change the password (sucess) (`/api/user/change-password`)

<details>
<summary>request</summary>

```
curl --request POST \
  --url https://local.fusionauth.io/api/user/change-password \
  --header 'Content-Type: application/json' \
  --data '{
  "applicationId": "85a03867-dccf-4882-adde-1a79aeec50df",
  "changePasswordId": "k95gcs11PGNQ_fUGFUluDpthI0j6aMlN_x9eAs5ONxc",
  "currentPassword": "password",
  "loginId": "joshua@fusionauth.io",
  "password": "password",
   "trustToken": "DsHrN0xbdPW6Nf3lf3-Su0kMXOH3NgGPzY6KWJXEMok",
   "trustChallenge": "moo"
}'
```
</details>

<details>
<summary>response</summary>

```
{
	"oneTimePassword": "t9W-D1ANe8GyNiOUbfruVgAkiYO0c3djIFuL0xywtnw"
}
```
</details>

### Expected behavior
👉🏻 A `trustChallenge` should not be required per our doc

👉🏻 Additionally, in either flow a `currentPassword` is required in step 4️⃣ but we document this as *optional*.

### Related
- https://github.com/FusionAuth/fusionauth-issues/issues/2010
- https://github.com/FusionAuth/fusionauth-issues/issues/1909

### Platform
dev setup

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

### Additional context
- Internal ticket - 73016
- https://fusionauth.io/community/forum/topic/1720/fusionauth-1-33-0-update-how-to-update-the-password-reset-functionality-for-users-that-have-two-factor-on?_=1670022886895&lang=en-GB

**Comment by spwitt** [comment] 2022-12-20 14:32
Closing as duplicate of #1909 

Amazing detail on this one though!

**Closed by spwitt** 2022-12-20 14:32 UTC
