### ISSUE TITLE
LoginId hint ignored when already logged in with different LoginId

### ISSUE THREAD

**Issue by PowerMogli** [FusionAuth/fusionauth-issues#940] opened 2020-10-14 11:23 UTC
### Description
Does FusionAuth respect the Login Hint when a user is already logged in to Fusion Auth? 

problem: 

If a user (abc@company.com) is already logged in to FusionAuth and uninstalls/re-install our Android app, then a new email address (xyz@company.com) is given to FusionAuth as a LoginId Hint after reinstalling and logging in, then the previously logged in user is still returned with the email (abc@company.com) as the logged in user. 

Is this a problem or a feature?

**Comment by robotdan** [comment] 2020-10-22 06:53
When you say already logged in, do you mean the user has an SSO session with FusionAuth? 

For example, I think what you're saying is:

1. User `abc@company.com` logs into FusionAuth using the FusionAuth login pages (SSO)
2. User now has an SSO session, and an SSO cookie was dropped (assuming you're using a web view)
3. User un-installs android app
4. User installs the android app
5. User `xyz@company.com` tries to log in, a web view is opened to FusionAuth
6. An SSO cookie still exists on the web view 
7. FusionAuth SSO recognizes the SSO token and logs the user in, and redirects back to the app

I would expect this behavior if the cookie still exists in the android web view. 

Can you ask android to clear cookies for a particular domain  as part of an un-install hook? 

I am not an android dev guy.. but these look promising:

```
@WorkerThread
public static void clearCache() {
    new WebView(getApplicationContext()).clearCache(true);
}
```
https://stackoverflow.com/a/30977400
https://developer.android.com/reference/android/webkit/WebView#clearCache(boolean)

Or, if the cookie manager is scoped to your application, I would assume it would be, you could just clear all cookies during an un-install perhaps.  https://developer.android.com/reference/android/webkit/CookieManager.html#removeAllCookies(android.webkit.ValueCallback%3Cjava.lang.Boolean%3E)

**Comment by PowerMogli** [comment] 2020-10-27 12:42
We are developing our app with Ionic 5 and use the pacakge "ionic-appauth" in the mobile area to access fusionAuth. This package accesses fusionAuth via an inAppBrowser plugin (https://github.com/Onegini/cordova-plugin-inappbrowser).

According to the plugin's documentation, there are two settings that can be specified to clean up the cookies when opening a web page. This is already happening. See here: https://github.com/wi3land/ionic-appauth/blob/master/src/cordova/cordova-browser.ts

Do you see any other possibilities we could do?

Translated with www.DeepL.com/Translator (free version)

**Comment by robotdan** [comment] 2020-10-28 23:20
So that is passing these options to the `InAppBrowser.create` :

```javascript
let options: any = {
  location: 'no',
  zoom: 'no',
  clearcache: 'yes',
  clearsessioncache: 'yes',     
}
```

`clearcache` does seem to indicate this should delete cookies:

https://github.com/Onegini/cordova-plugin-inappbrowser
> clearcache: set to yes to have the browser's cookie cache cleared before the new window is opened

This is making the assumption that this feature works correctly across iOS and Android. Some notable issues opened on that project:

https://github.com/apache/cordova-plugin-inappbrowser/issues/521

You could trying using the iOS or Android native web view components to prove that it works correctly w/out adding Cordova to the mix.

**Comment by andrewpai** [comment] 2024-04-27 19:36
Closing this issue as FusionAuth is behaving as intended in this scenario.

**Closed by andrewpai** 2024-04-27 19:36 UTC
Labels: support
