### ISSUE TITLE
Application webhooks not firing

### ISSUE THREAD

**Issue by trollr** [FusionAuth/fusionauth-issues#169] opened 2019-05-23 12:58 UTC
Application webhooks not firing 

### Description 
If you create a webhook `user.create` for all applications an event will be sent. However if you select only one application nothing happend 

### Steps to reproduce
1. Go to 'Settings->Webhook'
2. Create a webhook for user.created event
3. Goto Settings->webhooks->applications and select only one application
4. Goto Applications an activate the webhook
4. Register a new user for the selected application
5. No event fired

### Expected behavior
I would expect that the webhook is triggered, if you register a new user for the selected application

### Related or Duplicate
https://github.com/FusionAuth/fusionauth-issues/issues/930

### Platform
 - OS: Docker container
 - Chrome  74.0.3729.131

**Comment by robotdan** [comment] 2019-05-23 14:54
Hi @trollr thanks for opening this issue. 

In step 5 of your reproduce, you register a new user.  If you're only creating a new registration for an existing user you will not see the `user.create` event be fired, but you should see the `user.registration.create` event. This event was added in version `1.6.0`.

Let me know if I've misunderstood your recreate steps.

**Comment by trollr** [comment] 2019-05-27 08:23
Hi @robotdan,

I registered a new (not known) user with the registration form of the created application (company). Tried `user.registration.create` as well but nothing happend :(

Webhook config:

![Bildschirmfoto 2019-05-27 um 10 19 21](https://user-images.githubusercontent.com/2591138/58406062-198b6d00-8069-11e9-8862-8168e6b0b592.jpg)

Application config:

![Bildschirmfoto 2019-05-27 um 10 19 53](https://user-images.githubusercontent.com/2591138/58406071-1bedc700-8069-11e9-9ee9-04b899893ab2.jpg)

The webhook test works

**Comment by robotdan** [comment] 2019-05-27 19:30
Can you also ensure the events are enabled globally? 

See `Settings --> System --> Webhooks`

![image](https://user-images.githubusercontent.com/1148709/58436607-7bf16700-8083-11e9-9d27-b49d61efe995.png)

**Comment by trollr** [comment] 2019-05-28 07:23
Yes the events are enabled globally 

![Bildschirmfoto 2019-05-28 um 09 20 41](https://user-images.githubusercontent.com/2591138/58458605-ee1c8700-8129-11e9-8506-5bf6708778a8.jpg)

Should I see something in the event log or can I increase the log level to get some more informations?

**Comment by robotdan** [comment] 2019-05-28 15:02
With the transaction setting you have, FusionAuth won't fail if the webhook isn't working. For a test, can you change the transaction setting to require each webhook to succeed and see if you get a different status code back on the API request? If we fail based upon the transaction setting, you should get a `504`.

**Comment by trollr** [comment] 2019-05-29 07:59
Ok, I'll use the applicationId workaround as long as this bug isn't fixed

**Comment by voidmain** [comment] 2019-05-29 14:38
Hi @trollr. One questions for you on this item:

We have been discussing removing the "Applications" tab on the Webhook configuration pages. This configuration seems to cause quite a bit of confusion and it doesn't make sense for all of the event types. Additionally, the events that are application specific will send the application id(s) in the JSON to the Webhook. This would allow you to handle application specifics in the Webhooks.

Let me know your thoughts on that so we can determine if we should remove that configuration.

**Comment by trollr** [comment] 2019-05-29 18:50
I think it's a common feature to select events for a single application for multiple reasons especially to reduce the workload on my services. Your suggested solution will work, but it's more complicated for developers, because they need to inject the applicationId in their services (eg. staging, prod, dev, local etc). 

I would suggest to split hooks into two scopes. The ones for global purposes which will be configured in the system settings and last but not least the ones for the applications which will be configured in the application itself instead to just enable them. 

For sure that's a way more work for you. However if you encapsulate the events maybe it'll be possible to add custom events on my own eg in my plugins. 

_Note: Thereby you can understand my use case: I have two applications company and employee. Both of them use the user.create hook to send emails to the users. And Both of them will be notified, although only my company service should be notified if some registered as company user._

**Comment by robotdan** [comment] 2019-05-29 19:08
Thanks for that detail and feedback @trollr that is very helpful.

**Comment by mv4208** [comment] 2020-04-10 22:23
@robotdan - just posting on this issue.  We would also like to see webhooks enabled at the application level.  The admin UI shows this as a configuration option but it does not work.  We have to use the enable "all applications" configuration in the webhook, which makes this an all or nothing setting.  Will you be able to prioritize this issue on your roadmap?

**Comment by robotdan** [comment] 2020-04-11 00:35
The configuration works, but it is confusing and sort of a legacy configuration. There are a few event types that are of type "Application" and these events can optionally only be sent to one application. 

The events that are considered "application" events (currently) and can be scoped to an application based up the Webhook config:  `user.action`, `jwt.refresh-token.revoke` and `jwt.refresh`, `jwt.public-key.update`. 



We could look at re-working this to make it actually per application. In practice there are more "user" events as their are application scoped events. 

For example, the `user.delete`, `user.create`, `user.update`, `user.deactivate`, `user.bulk.create`, `user.reactivate`, `jwt.public-key.update`, `user.email.verified` and `user.password.breach` are all non-application specific. 

And the `user.login.success` and `user.login.failed` may or may not be related to an application  scoped event.

The `user.registration.create` , `user.registration.update`, `user.registration.delete` and `user.registration.verified` and `user.action` (sometimes) are application scoped. 

Any input is welcome, if you had your ideal, how would this be configured to allow a "per application" configuration? 

Because all applications belong to a single tenant, and a user is scoped to a tenant, most of the events apply to the tenant, and not to an application.

**Comment by mv4208** [comment] 2020-04-11 01:49
@robotdan thank you for the thoughtful and detailed response.  In our case we set up a dedicated tenant and application for each of our application environments.  For example foo.com we would setup foo-prod tenant > foo-prod app
foo-test tenant > foo-test app
foo-dev tenant > foo-dev app

We need the webhook to respect application-level events so that we can configure the webhook to send to a configured endpoint.  

webhook for prod - endpoint: https://api.foo.com/customer/fusionauth/webhook
webhook for test - endpoint: https://api-test-foo.com/customer/fusionauth/webhook
webhook for dev - endpoint: https://api-dev-foo.com/customer/fusionauth/webhook

In the example above the applications are configured in FusionAuth as dedicated environment tenants and applications, but when we configure the webhook to only the application, it does not fire on the event.  When we use the "All application" setting the webhook fires but the POST sends data to all of our environment endpoints `*/customer/fusionauth/webhook` regardless of what application triggered the event.

**Comment by robotdan** [comment] 2020-04-11 01:56
@mv4208 thanks , that use case is helpful.

In your particular case if you could assign a webhook to a tenant I think this would satisfy your requirement? 

This way you'd create 3 webhooks, and 3 tenants with a one to one relationship.

**Comment by mv4208** [comment] 2020-04-11 02:44
@robotdan - yes, that would be perfect for our requirements!

**Comment by sinqinc** [comment] 2020-09-18 01:03
> @robotdan thank you for the thoughtful and detailed response. In our case we set up a dedicated tenant and application for each of our application environments. For example foo.com we would setup foo-prod tenant > foo-prod app
> foo-test tenant > foo-test app
> foo-dev tenant > foo-dev app
> 
> We need the webhook to respect application-level events so that we can configure the webhook to send to a configured endpoint.
> 
> webhook for prod - endpoint: https://api.foo.com/customer/fusionauth/webhook
> webhook for test - endpoint: https://api-test-foo.com/customer/fusionauth/webhook
> webhook for dev - endpoint: https://api-dev-foo.com/customer/fusionauth/webhook
> 
> In the example above the applications are configured in FusionAuth as dedicated environment tenants and applications, but when we configure the webhook to only the application, it does not fire on the event. When we use the "All application" setting the webhook fires but the POST sends data to all of our environment endpoints `*/customer/fusionauth/webhook` regardless of what application triggered the event.

+1 We are also doing that.

**Comment by haziqtanveer** [comment] 2020-11-29 13:09
Hi robotdan,

I have configured the webhook for all the applications, but the webhook didn't fire at all. 
Can you please guide? it's 1.21.0 version newly deployed

![image](https://user-images.githubusercontent.com/23395153/100542745-6c00a780-3265-11eb-940b-ed97a9238a58.png)

![image](https://user-images.githubusercontent.com/23395153/100542760-7f137780-3265-11eb-97fb-75c161667ae8.png)

**Comment by maabreuc** [comment] 2020-12-16 01:15
@haziqtanveer You have to go to Tenant -> Edit -> Webhook tab, and enable the webhooks from there.

**Comment by LucasPiffer** [comment] 2021-01-29 20:42
1. Enabled inside tenant
2. Configured webhook for one application
3. Registered the user
4. No HTTP Request was fired

5. Enabled webhook for all applications
6. Registered the user
7. HTTP request was sent and webhook worked.

**Comment by robotdan** [comment] 2021-01-30 18:56
@LucasPiffer this is working as designed. It is a bit confusing, see this comment for an explanation. https://github.com/FusionAuth/fusionauth-issues/issues/169#issuecomment-612280619

This is something we plan to improve to avoid confusion.

**Comment by mooreds** [comment] 2021-02-01 22:39
@LucasPiffer Does this section of the webhook documentation help? https://fusionauth.io/docs/v1/tech/events-webhooks/events/#application-scoped-events 

In general, you want to enable webhooks at the tenant level and then filter on the application id.

**Comment by LucasPiffer** [comment] 2021-02-02 16:00
Hey, @robotdan and @mooreds thanks! I configured at tenant and left all applications enabled. In my application I made some checks to avoid events from another application.

**Comment by saul-gush** [comment] 2021-06-10 08:57
Hi @mooreds  and @robotdan, I just experienced the same - I selected which applications the webhooks should fire off for and it fails to fire off - I am not even sure what the purpose of these selections are - see screenshot. I guess a user is always global and not application specific - though that could cause a lot of traffic (and wastage) for a multi tenant environment where webhooks are going to different locations. 

![image](https://user-images.githubusercontent.com/63714857/121496008-f9217780-c9d1-11eb-9cf1-abe04ae861e3.png)

**Comment by mooreds** [comment] 2021-06-10 11:59
> I guess a user is always global and not application specific 

Yes, a user always belongs to a tenant, not to the application.

Sorry for the confusion! We know it's an area that could use some refinement. Unfortunately it is not currently on the near term roadmap to fix the UI/API to deprecate this confusing functionality. 

But if there are documentation changes you can recommend that would help people avoid the frustration you encountered, I'd love to hear them.

**Comment by saul-gush** [comment] 2021-06-10 12:52
Yeah I think just put in the documentation to say that user is a global so
any event is global and won’t fire off a webhook if only the application is
selected.

I added some checks in my code that look for the tenant id. The application
id is more complex as a list of application ids come back so a developer
would need to loop through the application ids to test that the event if
for that application.

Best
Saul

**Comment by robotdan** [comment] 2022-08-18 22:19
Closing this out. We have finally removed the application configuration and made these tenant scoped which should remove most of the confusion I think. 

See https://github.com/FusionAuth/fusionauth-issues/issues/1812 and  https://fusionauth.io/docs/v1/tech/release-notes#version-1-37-0

Please re-open if there are specific items not addressed in the latest release.

**Closed by robotdan** 2022-08-18 22:19 UTC
Labels: enhancement, architecture
