### ISSUE TITLE
Not enough entropy to generate random

### ISSUE THREAD

**Issue by fabiosimeoni** [FusionAuth/fusionauth-issues#241] opened 2019-07-29 17:17 UTC
Hello, am trying to run FusionAuth 1.7..2 in Kubernetes (minikube distro), using also your templates as a guideline.
I'm noticing huge delays right at at the end of startup process, which seem to be the result of a blocking random generator (see `WARNING` below):

```
Jul 29, 2019 5:06:57.722 PM INFO  com.inversoft.migration.Migrator - Run Cleanup [io.fusionauth.api.migration.guice.Migration_1_2_0]
Jul 29, 2019 5:06:57.743 PM INFO  com.inversoft.migration.Migrator - Run Cleanup [io.fusionauth.api.migration.guice.Migration_1_3_0]
Jul 29, 2019 5:06:57.749 PM INFO  com.inversoft.migration.Migrator - Run Cleanup [io.fusionauth.api.migration.guice.Migration_1_3_1]
Jul 29, 2019 5:06:57.757 PM INFO  com.inversoft.migration.Migrator - Run Cleanup [io.fusionauth.api.migration.guice.Migration_1_5_0]
Jul 29, 2019 5:06:57.772 PM INFO  com.inversoft.migration.Migrator - Run Cleanup [io.fusionauth.api.migration.guice.Migration_1_6_0]
Jul 29, 2019 5:06:57.784 PM INFO  com.inversoft.migration.Migrator - Run Cleanup [io.fusionauth.api.migration.guice.Migration_1_7_0]
Jul 29, 2019 5:09:35 PM org.apache.catalina.util.SessionIdGeneratorBase createSecureRandom
WARNING: Creation of SecureRandom instance for session ID generation using [SHA1PRNG] took [157,421] milliseconds.
29-Jul-2019 17:09:35.270 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-9011"]
29-Jul-2019 17:09:35.301 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["https-jsse-nio-9013"]
29-Jul-2019 17:09:35.310 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["ajp-nio-9019"]
29-Jul-2019 17:09:35.329 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in 166496 ms

```

This seems to be a well-known problem, with `Tomcat` in particular. I've tried to set 

```
JAVA_OPTS: -Djava.security.egd=file:/dev/./urandom
```

on Tomcat's Pod, but it seems to have no effect. Any suggestion?

### External references
https://stackoverflow.com/questions/28201794/slow-startup-on-tomcat-7-0-57-because-of-securerandom

https://confluence.atlassian.com/crowdkb/crowd-startup-takes-an-extremely-long-time-on-linux-762872528.html

FusionAuth is using Tomcat v8.5.31

**Comment by robotdan** [comment] 2019-07-29 17:47
Are you running KVM in your k8s configuration?

**Comment by fabiosimeoni** [comment] 2019-07-29 17:58
running `minikube` on a `hyperkit` driver for macos.

logging in the `minikube` VM:

```
$ cat /proc/sys/kernel/random/entropy_avail 
190
``` 

which I understand to be very low.

**Comment by robotdan** [comment] 2019-07-29 18:01
Not sure there is much I can do about this one, I'll leave it open - perhaps another FusionAuth user has a work around for this. 

We hope to be moving to OpenJDK 11 or 12 in the not too distant future - I don't know if their implementation is better or if the cause is directly related to the random generator provided by the underlying OS / hypervisor.

**Comment by robotdan** [comment] 2019-07-29 19:38
@fabiosimeoni I think your work around may be correct, how are you passing that to Java? 

To get it into the VM running FusionAuth you'll need to either set it in the `fusionauth.properties` file or provide another environment variable. 

https://fusionauth.io/docs/v1/tech/installation-guide/docker
https://fusionauth.io/docs/v1/tech/reference/configuration

To use the environment variable you could try setting

```
FUSIONAUTH_ADDITIONAL_JAVA_ARGS=-Djava.security.egd=file:/dev/./urandom
```

**Comment by fabiosimeoni** [comment] 2019-07-29 20:17
@robotdan, excellent, this seems to have solved the problem. I should have dug deeper in your docs for that variable.

To give back something, I seem to be having some success also with a modified `fusionauth` image, where I install [Haveged](https://wiki.archlinux.org/index.php/Haveged) to increase the entropy of the container. This seems to be quite en vogue in cloud-native solutions, even though my understanding is that  cluster managers install it as a `DemonSet`, ie. on all nodes of the cluster, transparently from anything that may run there. But it can of course be installed in individual containers too.

I'm attaching a draft `Dockerfile` with the changes. I'm going to use it for a bit and confirm it's a full solution. If it is, you may want to use it in future versions as a more transparent solution than the env var. 

Note that since I am touching the image, I've also make quick changes to solve #191  (the thing would need cleaning up a bit).

[Dockerfile.zip](https://github.com/FusionAuth/fusionauth-issues/files/3444131/Dockerfile.zip)

thanks again!

**Comment by robotdan** [comment] 2019-07-29 21:18
Great, thanks for the example Dockerfile, we'll take a look!

**Comment by robotdan** [comment] 2020-10-21 22:44
Closing this one out. Please re-open if there is still an issue on a recent version of FusionAuth which is running on Java14.

**Closed by robotdan** 2020-10-21 22:44 UTC
Labels: support, triage
