### ISSUE TITLE
Support Pagination for List of Applications

### ISSUE THREAD

**Issue by brennan-karrer** [FusionAuth/fusionauth-issues#748] opened 2020-07-16 15:44 UTC
### Problem
Retrieving a list of all applications via `GET /api/application` returns the entire set of applications with no ability for pagination. As our application list grows, this becomes an expensive operation and pagination would help reduce the payload size. Additional capability to retrieve only active or inactive applications would be desired as well.

### Solution
Add support for pagination via query parameters or modify the request to a POST and allow a POST body with query parameters. A POST body would mirror the same pagination functionality that FusionAuth provides with other API endpoints, such as the Users Search API:
```
POST /api/application
{
    "numberOfResults": 20,
    "startRow": 1
}
```
If you do not wish to offer the POST method for this API endpoint, then a simple GET with query parameters would suffice as well:
```
GET /api/application?numberOfResults=20&startRow=1
```

### Alternatives/workarounds
At the moment, I am not aware of any workaround which will return only a subset of applications.

### Additional context
N/A

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by robotdan** [comment] 2020-07-17 04:20
Excellent idea! Thanks for the suggestion @brennan-karrer . 

This is on our list.. hoping to get to it soon. This is a duplicate of an issue we have open for this very issue. 
https://github.com/FusionAuth/fusionauth-issues/issues/374

**Comment by brennan-karrer** [comment] 2020-07-17 18:00
> Excellent idea! Thanks for the suggestion @brennan-karrer .
> 
> This is on our list.. hoping to get to it soon. This is a duplicate of an issue we have open for this very issue.
> #374

Oh I should've done a bit more thorough combing through the current open issues. My apologies. I'm glad it's on your radar!

**Comment by robotdan** [comment] 2020-07-19 22:55
Closing as duplicate. Thanks for your contribution @brennan-karrer !

**Closed** 2020-11-03 03:45 UTC
Labels: duplicate
