### ISSUE TITLE
Allow additional data to be put into the token

### ISSUE THREAD

**Issue by davidb-e4s** [FusionAuth/fusionauth-issues#100] opened 2019-03-28 15:40 UTC
Allow additional data to be put into the token

### Problem
I store a critical bit of information in the userdata object thatI'd like to add to the JWT. Right now I have to call /api/user to get the data and this is done on every request (I need the customer the user belongs too at API call time)

### Solution
Allow the adding of userdata to the JWT token so I don't have to do two calls...cache etc.

### Alternatives/workarounds
Calling /api/user and persisting to a cache, but this adds complexity to my app.

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by robotdan** [comment] 2019-03-28 15:52
Hi @davidb-e4s thanks for taking the time to open this feature. This feature is on the roadmap for sure. 

We do have an existing feature open to track this request. https://github.com/FusionAuth/fusionauth-issues/issues/61

I'll close this one out as a duplicate, feel free to add any additional details or comments to the linked issue. 

In the next point release we will be delivering support for lambdas. A lambda will be small free form JavaScript functions that we will allow you to use in different ways. 

One of the planned uses for this feature will be to allow you to register a lambda to customize the claims returned in the JWT. For example, you'll be able to register a lambda that will take a user object and a map of claims, and you will be able to augment the claim map before we build the signed token. 

We hope to have this out sometime in Q2. Stay tuned. Thanks!

**Comment by robotdan** [comment] 2019-03-28 15:52
Closing as duplicate of #61

**Closed by robotdan** 2019-03-28 15:52 UTC
Labels: duplicate, feature

**Comment by davidb-e4s** [comment] 2019-03-28 15:58
Thanks. I’ve added my use case to #61.
