### ISSUE TITLE
Creating user with empty name results in FTL exception

### ISSUE THREAD

**Issue by rmr** [FusionAuth/fusionauth-issues#908] opened 2020-10-02 08:10 UTC
### Description 
```
==> user.id  [in template "WEB-INF/templates/admin/user/manage.ftl" at line 25, column 23]

----
Tip: It's the step after the last dot that caused this error, not those before it.
----
Tip: If the failing expression is known to legally refer to something that's sometimes null or missing, either specify a default value like myOptionalVar!myDefault, or use [#if myOptionalVar??]when-present[#else]when-missing[/#if]. (These only cover the last step of the expression; to cover the whole expression, use parenthesis: (myOptionalVar.foo)!myDefault, (myOptionalVar.foo)??
----

----
FTL stack trace ("~" means nesting-related):
	- Failed at: ${user.id}  [in template "WEB-INF/templates/admin/user/manage.ftl" at line 25, column 21]
	~ Reached through: #nested  [in template "WEB-INF/templates/_layouts/admin.ftl" in macro "head" at line 150, column 3]
	~ Reached through: @layout.head  [in template "WEB-INF/templates/admin/user/manage.ftl" at line 22, column 3]
	~ Reached through: #nested  [in template "WEB-INF/templates/_layouts/admin.ftl" in macro "html" at line 14, column 3]
	~ Reached through: @layout.html  [in template "WEB-INF/templates/admin/user/manage.ftl" at line 21, column 1]
----
```

### Affects versions
1.9.18

### Steps to reproduce
I looked at the audit logs, and this corresponds to the same time of the exception.

Created user with Id [97e1bf39-26b8-4efe-8aac-fa85d51b0052], name [null] and loginId [****]

### Platform
Kubernetes

**Comment by robotdan** [comment] 2020-10-02 16:28
Can expand upon your recreate steps, be as specific as possible, did you use the API, if so, what was the JSON body, if you used the UI, what steps and fields did you use? 

Thanks.

**Comment by jobannon** [comment] 2021-06-21 18:11
Internal Note: see ZenDesk ticket # 71834

**Comment by andrewpai** [comment] 2024-04-27 19:15
Closing this issue, as we were (and are) unable to reproduce the behavior.

**Closed by andrewpai** 2024-04-27 19:15 UTC
Labels: unreproducible
