### ISSUE TITLE
app will not connect to database with empty root password

### ISSUE THREAD

**Issue by vladyslav2** [FusionAuth/fusionauth-issues#238] opened 2019-07-29 12:26 UTC
### Description 
I'm using postgres docker image with empty root password.
Apperently its not possible to run an app when root does not have a password.
Everytime I click next I'm getting an error:

<img width="756" alt="Знімок екрана 2019-07-29 о 5 20 45 дп" src="https://user-images.githubusercontent.com/704096/62048173-0c057700-b1c1-11e9-954f-c310ad1f9a74.png">

### Steps to reproduce
1. Run docker with empty root password `docker run --name postgres -p 5432:5432 -e POSTGRES_PASSWORD= -d postgres`
2. Run fusapp `docker run --env-file .env -p9011:9011 fusionauth/fusionauth-app`
3. open http://127.0.0.1:9011 and try to pass first screen

### Platform
 - MacOS 10.12.6

**Comment by robotdan** [comment] 2019-07-29 15:15
It shouldn't matter if the root user has an empty password. Can you connect to the database with those credentials using `psql` and using the `-h` option to specify the host ( to test connecting over TCP instead of a local socket)? 

Do you have any log output?

**Comment by vladyslav2** [comment] 2019-07-29 16:20
@robotdan 
```
psql -Upostgres -h127.0.0.1
```

does work without any problem. And I used my regular postgres docker image which I'm using on other projects.

When I started using your docker compare file I actually pass the first step but got into other issues #172 

I'm happy to do more specific tests if you need

**Comment by robotdan** [comment] 2019-07-29 17:07
I wonder if this is a SCRAM-SHA-256 issue as described here https://github.com/FusionAuth/fusionauth-issues/issues/209?

**Comment by crocodile2u** [comment] 2020-06-18 16:03
I can confirm the same for linux, with MySQL connection. In my dev environment, I prefer not to set a password for DB.

```yml
DATABASE_URL: jdbc:mysql://db:3306/fusionauth
DATABASE_ROOT_USER: root
DATABASE_ROOT_PASSWORD:
DATABASE_USER: root
DATABASE_PASSWORD:
```

logs of fusionauth container:
```
PM ERROR com.inversoft.maintenance.db.DatabaseSilentConfigurationWorkflowTask - Unable to grant access to the configured user [root] perhaps the user already exists with other credentials or other database issues exist.
```

logs of mysql container:

```
db_1          | 2020-06-18 15:59:14 8 [Warning] Aborted connection 8 to db: 'unconnected' user: 'unauthenticated' host: '172.19.0.11' (This connection closed normally without authentication)
db_1          | 2020-06-18 15:59:15 11 [Warning] Access denied for user 'root'@'172.19.0.11' (using password: YES)
```

**Comment by crocodile2u** [comment] 2020-06-18 16:10
Update: after I changed config to be this:

```
DATABASE_URL: jdbc:mysql://db:3306/fusionauth
DATABASE_ROOT_USER: root
DATABASE_ROOT_PASSWORD:
DATABASE_USER: fusion
DATABASE_PASSWORD: fusion
```

I was able to see the maintainance mode page but when I try to provide an empty password for root mysql user from there, the action fails with error:

```
Unable to connect to your database using the superuser username and password, verify your connection information. If it is correct, make sure the database is running before continuing.
```

User root without password is what I use to connect to db service from the application and from command line.

**Comment by mooreds** [comment] 2020-06-18 16:16
Looks like if you don't pass an env var to docker-compose it assumes it is an empty string: https://github.com/docker/compose/issues/3768

Can you try omitting the `DATABASE_ROOT_PASSWORD` variable from the docker compose file and see if that works?

**Comment by crocodile2u** [comment] 2020-06-18 16:24
It's getting curioser.

DB tables have been created. The normal DB user has been created, I can connect via mysql console with credentials I provided on the Maintenance Mode screen. Fusionauth still show the Maintenance Mode screen if I restart container.

I found this in logs, going to try to fix it:

```
fusionauth_1  | Enforcing utf8mb4 character encoding. Review the following messages:
fusionauth_1  | 
fusionauth_1  |  Errors that caused startup to fail:
fusionauth_1  |   Expected [character_set_server] to start with or be equal to [utf8mb4] but found [latin1]
fusionauth_1  |   Expected [collation_server] to start with or be equal to [utf8mb4] but found [latin1_swedish_ci]
```

**Comment by crocodile2u** [comment] 2020-06-18 16:41
OK, I got it to work with settings:
```
# /etc/mysql/conf.d/charsets.cnf (I used docker image 'mariadb' for db container)
[mysqld]
character_set_server = utf8mb4
collation_server = utf8mb4_unicode_ci
```

**Comment by mooreds** [comment] 2020-06-18 16:49
Ah, yes. Here's more about that, from https://fusionauth.io/docs/v1/tech/reference/configuration

> When set to true and using MySQL, a 4 byte UTF compatible character set configuration is enforced at startup.
> If this validation is not desired or not it is not possible to modify your MySQL configuration to satisfy the validation, disable this check by setting this value to false. If this is false, any attempt to store a 4 byte unicode character will cause the INSERT or UPDATE request to fail. The initial MySQL UTF-8 implementation only supported up to characters up to 3 bytes in length; utf8mb4 extends this to 4 byte characters. 

If you've solved the issue, please feel free to close it.

**Comment by robotdan** [comment] 2020-10-21 22:42
This is likely resolved under issue https://github.com/FusionAuth/fusionauth-issues/issues/95 in version 1.19.0. 
Please re-open if you can still recreate.

**Closed by robotdan** 2020-10-21 22:42 UTC
Labels: support, triage
