### ISSUE TITLE
FusionAuth always sets SSO session when using external IDP

### ISSUE THREAD

**Issue by lyleschemmerling** [FusionAuth/fusionauth-issues#2472] opened 2023-09-15 19:10 UTC
### Description
When setting up an external IDP in FusionAuth there is an option to select which applications it will be available for. However, we always set the FusionAuth SSO session cookie on the callback from the IDP, which means that the user will be authenticated on other applications configured on the tenant. We do not set the value checked on "keep me signed in" when we redirect out to the external IDP.

This is confusing and potentially problematic as the SSO behavior may not always be desired when using an IDP configured for one application.

### Related
- https://github.com/FusionAuth/fusionauth-issues/issues/2464
- https://github.com/FusionAuth/fusionauth-issues/issues/2893
- https://inversoft.slack.com/archives/C0407G6V5/p1698184523642639

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

**Comment by robotdan** [comment] 2023-09-15 20:47
This is working as designed. If you are proposing an alternate design, please add additional information to the description.

**Comment by mooreds** [comment] 2023-09-15 21:09
Seems to me we should respect the `keep me logged in` checkbox, no matter what the source of the login is.

Especially since that's one of the main ways to keep separation of users who are registered to different applications. The alternatives are:

* check for the `applicationId` in the application doing the token exchange, which is always good practice.
* set `application.oauthConfiguration.requireRegistration` to true for all the applications. I haven't tested, but I believe that would stop the automatic login in this case.

At the least we should document this because it is surprising to have the `keep me logged in` checkbox differ in behavior based on the type of authentication.

**Comment by robotdan** [comment] 2023-09-20 01:04
If we are not respecting the state of the `keep me logged in` checkbox, this is a bug. 

If the statement is that you can enable a Google IdP  for `Application A` which means we show a button that says "Login with Google" and then once you have established an SSO  session you can access Application B using SSO, this is working as designed and I don't know that we have any intention to modify this behavior. 

@lyleschemmerling can you please clarify which of these two issues you are describing?

**Comment by lyleschemmerling** [comment] 2023-09-20 01:58
If the user leaves the checkbox unchecked such that if they logged in with fusionauth they would not have an SSO session but instead clicks on the button for the external idp we redirect to the external idp and back and assign them an SSO session on the callback action.

In this flow there is a `temporary` flag on the `ssoSession` that is always `false` so when we complete the login we assign the sso session cookie by default.

**Comment by robotdan** [comment] 2023-10-11 02:18
Internal:
Not sure how to fix this in all cases. But, if we do stop on the login page where the user clicks a button, we could optionally capture the current state of the "Remember me" and pass it along so that we can honor it after we process the IdP request and complete the login. 

This won't cover cases where an `idp_hint` or `login_hint` is used and we bypass the login screen. In these cases, we likely need to accept the initial state of this checkbox on the request so it can be provided by the caller. 

The default should be whatever the default is of the checkbox, assuming it is on.

**Comment by spwitt** [comment] 2024-10-16 19:23
Resolved by
- https://github.com/FusionAuth/fusionauth-issues/issues/2893

**Closed by spwitt** 2024-10-16 19:23 UTC
Labels: bug
