### ISSUE TITLE
Localized email templates not being used during self-service registration

### ISSUE THREAD

**Issue by glen-84** [FusionAuth/fusionauth-issues#1738] opened 2022-05-31 15:34 UTC
### Description 
This is a critical issue for us. Despite a locale cookie being set, neither the `locale` nor `preferredLanguages` are part of the form, and localized email templates are therefore not used. Am I missing something here? What determines which localized templates to use?

I tried adding:

```ftl
[@helpers.hidden name="locale" value="vi" /]
[@helpers.hidden name="user.preferredLanguages" value="vi" /]
```

... to the form, but it doesn't seem to help.

### Affects versions
`1.36.4`

### Steps to reproduce
1. Add localized email templates.
2. Register from a page with the locale set to a locale matching one of the localized email templates.
3. Receive a verification email in the default language instead of the localized language.

### Expected behavior
I expect the localized templates to be used based on the locale cookie. I also expect to be able to set `user.preferredLanguages` via the registration form, or have these automatically set based on the locale, so that subsequent emails are also sent with the correct language.

### Screenshots
n/a

### Platform
(Please complete the following information)
 - Device: Desktop
 - OS: Windows 11
 - Browser + version: Chrome 102
 - Database: PostgreSQL 12.9

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

### Additional context
Our integration is up on staging and is supposed to go live soon. I hope that I'm just missing something obvious here, otherwise this is a big problem.

Possibly related to: #1693, #1713.

You can work around this using advanced registration forms: https://github.com/FusionAuth/fusionauth-issues/issues/1738#issuecomment-1143952909

Note that even if admins have localized the theme and a user selects a different language during the registration process using the locale picker, they do not receive the localized email.

### Documentation
- [x] Change to basic registration API
- [x] Review any existing registration guides (talk to Dan)
  - [x] https://fusionauth.io/docs/v1/tech/guides/advanced-registration-forms
  - [x] https://fusionauth.io/docs/v1/tech/guides/basic-registration-forms
- [x] Review core concepts screen shots for needed updates
- https://github.com/FusionAuth/fusionauth-site/pull/1949

**Comment by mooreds** [comment] 2022-06-01 03:36
If you set `preferredLanguages` using the admin UI, are emails sent using the correct locale?

**Comment by glen-84** [comment] 2022-06-01 11:55
Yes, I tested that.

It wouldn't help as a workaround though, because of the same issue impacting https://github.com/FusionAuth/fusionauth-issues/issues/1580 (the email is sent before the transaction is complete, so there's no opportunity to set the lang pref before that).

Are you able to reproduce both issues?:

- Locale cookie not used for localized template selection.
- Not possible to send `user.preferredLanguages` during registration.

Unless I'm making a mistake somewhere, this means that it's not possible to send localized email verification emails. This is bad.

**Comment by glen-84** [comment] 2022-06-03 07:11
@robotdan

Can you please confirm whether or not this is a bug, so that we're able to make a more informed decision on how to proceed?

The website clearly states that email localization is supported in the Community edition. It's a bit pointless being able to create localized email templates if verification emails always use the default language?

**Comment by glen-84** [comment] 2022-06-08 15:26
Thanks for your reply, Dan.

We set the cookie based on the query string depending on which localized website a user came from (`.in.th`, `.vn` etc.), but it's essentially the same as selecting one via the selector.

The difference between the locales and preferred languages _is_ a bit subtle, but I can see how keeping them separate may make sense – f.e. just because someone registers on an English site doesn't mean that that is necessarily their preferred language ... I suppose.

Using an _explicit_ locale selection to populate a hidden `preferredLanguages` field might make sense, as in that case a user would at least be involved in the decision to some extent.

Allowing `user.preferredLanguages` during basic self-service registration may be the easiest/cleanest solution. I didn't really see it as an advanced feature since it's neither a custom field (similar to `username`) nor does it facilitate multi-step forms or other advanced features, and it would enable this basic use case of sending the verification email using the correct locale.

---

If you have a rough idea of when this might be added, it would really help us to plan our release. For example:

"In the new few days" -> We'd probably wait for it.
"In 1-2 months" -> I might consider paying for a temporary upgrade with my salary until it is added.
"2+ months or no idea" -> We'd probably have to come up with an entirely new solution. 🙂

**Comment by robotdan** [comment] 2022-06-09 03:39
Hard to say on the timeline..  this probably isn't a big lift but we have several larger projects in flight that are consuming most of our engineering resources at the moment.  

I would guess 2+ to get it into plan officially.. but a small feature such as this is more likely to get slid into an existing feature branch. So it is possible it could be sooner if we find a bit of slack in our current projects. 



> I didn't really see it as an advanced feature since it's neither a custom field (similar to username) nor does it facilitate multi-step forms or other advanced features, and it would enable this basic use case of sending the verification email using the correct locale.

I agree. This wasn't left out intentionally in the sense that it is "advanced", but the current basic self-service option is essentially just the older way of doing self-service registration, and when we built "advanced" with a form builder we just left the existing code as is and kept it in the community version. 

W/out looking at the code in detail yet - I would lean towards adding `user.preferredLanguages` to the basic self-service registration feature and leave the theme locale selector as is.

**Comment by glen-84** [comment] 2022-10-01 18:09
Any updates on this one?

**Comment by mooreds** [comment] 2022-10-25 23:16
We are focusing on the next release, which is 1.41. That won't have this in it. The current plan is to have it in 1.42.

**Comment by glen-84** [comment] 2023-02-05 11:25
Is it a large task to add this one field to basic self-service registration?

We're having to send non-translated emails in production due to this issue.

It's been pushed back 7 minor versions already. I provided [a lot of feedback](https://github.com/FusionAuth/fusionauth-issues/issues/created_by/glen-84), and all I'm just asking is for this one issue to be prioritized a bit.

**Comment by spwitt** [comment] 2023-02-16 20:27
Internal
- https://github.com/FusionAuth/fusionauth-app/pull/215
- https://github.com/FusionAuth/fusionauth-client-builder/pull/65
- https://github.com/FusionAuth/fusionauth-localization/pull/59

**Comment by mooreds** [comment] 2023-02-24 22:23
Thanks for your patience and feedback @glen-84 ! I'm going to be glad to see this feature released in 1.44.

**Comment by mooreds** [comment] 2023-05-13 22:08
Is this going to make it into 1.46.0?

**Comment by geoalexidis** [comment] 2023-07-03 06:17
Hello,

This doesn't look like a lot work left to be done. What are you guys waiting for?

We're facing the same issue. It has been over a year since this issue was created.

Thanks and BR

**Comment by mooreds** [comment] 2023-07-04 03:43
Thanks @geoalexidis, appreciate the feedback.

We're hoping to get this into the next release. We've had other priorities, unfortunately. I'm sure you understand that we have a lot of requests from both the community and customers as well as internal work and can't fulfill all of them as quickly as we'd like.

**Closed** 2023-07-28 13:12 UTC
Labels: enhancement

**Comment by elliotdickison** [comment] 2023-09-29 00:35
Hi all, I'm on 1.47.1 and I'm adding `[@helpers.hidden name="user.preferredLanguages" value="pt_BR" /]` to the template for my registration form. I can confirm that the "user.preferredLanguages" field is being submitted with the rest of the form when a user registers, but the user's preferred language is still not being set. I'm using basic forms for simplicity even though I'm a paid user.

**Comment by elliotdickison** [comment] 2023-09-29 20:40
Turns out I needed to enable the "Preferred languages" registration field for the app first.
