### ISSUE TITLE
Encrypted password in user update/patch api

### ISSUE THREAD

**Issue by wax213** [FusionAuth/fusionauth-issues#500] opened 2020-03-02 13:15 UTC
### Problem
There is no way to update user password with encrypted value.

### Solution
The same logic like in https://fusionauth.io/docs/v1/tech/apis/users#import-users

**Comment by robotdan** [comment] 2020-03-02 16:03
Duplicate of https://github.com/FusionAuth/fusionauth-issues/issues/348 ?

**Closed** 2020-03-02 16:03 UTC
Labels: duplicate
