### ISSUE TITLE
Store user's IdP preference in user profile to simplify future logins

### ISSUE THREAD

**Issue by davidmw** [FusionAuth/fusionauth-issues#389] opened 2019-12-01 08:27 UTC
### Problem

When the Google option is used to create an Identity Provider there is no option to specify managed domains. 

This results in a login screen that has fields for email and password, and below that the Google SSO button. Seemingly in every class of kids told to use Google SSO, a significant number of them will try to use Google credentials in the FusionAuth fields. I've seen 5+ retries at this, and a subset of these users will request a password reset and some succeed at that.

I've tried to create a new SAML Identity Provider for Google (along with the SAML App in Google admin) to gain the managed domain functionality but keep getting 403 app_not_configured_for_user on login. Google's SAML app needs an ACS URL and Entity ID from the Service Provider but FusionAuth doesn't provide an Entity ID.

Once I added this new IP our login form no longer displays the password field.  When the email address is submitted the user then sees a Google signon with a blank email field, forcing reentry which isn't great.

Ultimately I'm trying to reduce the login friction for these kids and their teachers. At this point we can use the email domain to route some of the schools to Google SSO and I'm hoping that will solve much of it.

**Comment by davidmw** [comment] 2020-01-07 22:08
The request above, previously titled _Google IdP Managed Domain option_ relies on an overly simplistic filtering of IdP buttons based on email domain. Some of our schools have school specific email domains while others use a State-wide email domain and in both cases the IdP requirements vary.

So email domains aren't very useful when trying to direct our users to the correct login method. 

This is what I think would work:

1) FusionAuth login screen requests email address.
2) User submits email address

  For unverified / first time login / no IdP preference situations: ALL IdPs configured for the tenant are shown along with FusionAuth password field.
     3) User selects IdP button and proceeds with login.  This IdP is saved in FusionAuth user profile as 'last used.'

  For users with 'last used IdP' in profile, FusionAuth shows the single IdP option plus 'more choices' link.
      3) Show the Google SSO button. Clicking it would show the Google popup with active accounts or hopefully autofill the email address if none are active. The 'more choices' link would display FusionAuth password field plus any additional configured IdP buttons.

A major goal here is to only display the FusionAuth password field if the user skips the IdP options or they have indicated intent to rely on FusionAuth account.

**Comment by davidmw** [comment] 2020-01-23 08:42
@voidmain is this a reasonable feature request if properly funded? This is for situations where multiple IdPs are configured for tenant & app, where email domains are frequently useless to filter IdP choices and when users repeatedly throw IdP passwords at the FusionAuth password screen.

**Comment by robotdan** [comment] 2020-01-23 15:57
@davidmw I think so , we'd have to think through all of the cases and come up with a solution.

In theory we could drop a cookie that may tell us what the user preference is so when they got the login screen we can pre-emptively select an IdP.

I can think of several possible issues with this type of solution but I would guess we could come up with something that would work for you and provide value to the core product.

If you're interested hit the contact form on the main site and we can put together an estimate of time, cost etc.

**Comment by davidmw** [comment] 2020-01-27 09:47
Ok, I'll put in the estimate request.

I'm not very fond of putting the IdP preference in cookie or local storage as that isn't very sticky or portable.

Ideally the user will submit email address and server returns the next screen depending on IdP preference in profile. That property would need to be available from user profile prior to authentication. If email address is not found or has no preference stored then proceed to show all configured IdPs to avoid exposing any email validation.

**Comment by mooreds** [comment] 2020-07-10 20:20
Closing as duplicate of https://github.com/FusionAuth/fusionauth-issues/issues/178

**Closed by mooreds** 2020-07-10 20:20 UTC
