### ISSUE TITLE
Error When Granting an Entity to a User in the UI

### ISSUE THREAD

**Issue by dvictory** [FusionAuth/fusionauth-issues#1749] opened 2022-06-05 16:46 UTC
### Description 
I can't grant entity access to a user, using the UI 

### Affects versions
1.36.4

### Steps to reproduce
Create and Entity Type
Create and Entity
Create a user
Go the the Grant Entities tab on the user
Click Add
Search for the entity you created and select it.
ERROR "That entity has been deleted. Refresh your browser." 

See below for stacktrace

### Expected behavior
You should be able to assign a user to an entity.

### Additional context
Error from log:

A FreeMarker exception occurred.

Exception:
FreeMarker template error:
The following has evaluated to null or missing:
"==>" entity  [in template "WEB-INF/templates/admin/entity/grant/upsert.ftl" at line 38, column 14]

Tip: If the failing expression is known to legally refer to something that's sometimes null or missing, either specify a default value like myOptionalVar!myDefault, or use [#if myOptionalVar??]when-present[#else]when-missing[/#if]. (These only cover the last step of the expression; to cover the whole expression, use parenthesis: (myOptionalVar.foo)!myDefault, (myOptionalVar.foo)??

FTL stack trace ("~" means nesting-related):
	- Failed at: #if entity.type.permissions?size > 0  [in template "WEB-INF/templates/admin/entity/grant/upsert.ftl" at line 38, column 9]
	~ Reached through: #nested  [in template "WEB-INF/templates/_layouts/admin.ftl" in macro "pageForm" at line 400, column 9]
	~ Reached through: #nested  [in template "WEB-INF/templates/_utils/panel.ftl" in macro "full" at line 15, column 9]
	~ Reached through: @panel.full titleKey=panelTitleKey pa...  [in template "WEB-INF/templates/_layouts/admin.ftl" in macro "pageForm" at line 399, column 7]
	~ Reached through: #nested  [in template "WEB-INF/templates/_layouts/admin.ftl" in macro "main" at line 391, column 5]
	~ Reached through: @main  [in template "WEB-INF/templates/_layouts/admin.ftl" in macro "pageForm" at line 398, column 5]
	- Reached through: @control.form action=action method=me...  [in template "WEB-INF/templates/_layouts/admin.ftl" in macro "pageForm" at line 396, column 3]
	- Reached through: @layout.pageForm action="upsert" meth...  [in template "WEB-INF/templates/admin/entity/grant/upsert.ftl" at line 29, column 5]
	~ Reached through: #nested  [in template "WEB-INF/templates/_layouts/admin.ftl" in macro "body" at line 371, column 5]
	~ Reached through: @layout.body  [in template "WEB-INF/templates/admin/entity/grant/upsert.ftl" at line 19, column 3]
	~ Reached through: #nested  [in template "WEB-INF/templates/_layouts/admin.ftl" in macro "html" at line 15, column 3]
	~ Reached through: @layout.html  [in template "WEB-INF/templates/admin/entity/grant/upsert.ftl" at line 10, column 1]-

Java stack trace (for programmers):
----
freemarker.core.InvalidReferenceException: [... Exception message was already printed; see it above ...]
	at freemarker.core.InvalidReferenceException.getInstance(InvalidReferenceException.java:134)
	at freemarker.core.UnexpectedTypeException.newDescriptionBuilder(UnexpectedTypeException.java:85)
	at freemarker.core.UnexpectedTypeException.<init>(UnexpectedTypeException.java:48)
	at freemarker.core.NonHashException.<init>(NonHashException.java:49)
	at freemarker.core.Dot._eval(Dot.java:48)
	at freemarker.core.Expression.eval(Expression.java:101)
	at freemarker.core.Dot._eval(Dot.java:41)
	at freemarker.core.Expression.eval(Expression.java:101)
	at freemarker.core.BuiltInsForMultipleTypes$sizeBI._eval(BuiltInsForMultipleTypes.java:504)
	at freemarker.core.Expression.eval(Expression.java:101)
	at freemarker.core.EvalUtil.compare(EvalUtil.java:113)
	at freemarker.core.ComparisonExpression.evalToBoolean(ComparisonExpression.java:78)
	at freemarker.core.IfBlock.accept(IfBlock.java:49)
	at freemarker.core.Environment.visit(Environment.java:334)
	at freemarker.core.Environment.visit(Environment.java:376)
	at freemarker.core.Environment.invokeNestedContent(Environment.java:620)
	at freemarker.core.BodyInstruction.accept(BodyInstruction.java:60)
	at freemarker.core.Environment.visit(Environment.java:370)
	at freemarker.core.Environment.invokeNestedContent(Environment.java:620)
	at freemarker.core.BodyInstruction.accept(BodyInstruction.java:60)
	at freemarker.core.Environment.visit(Environment.java:370)
	at freemarker.core.Environment.invokeMacroOrFunctionCommonPart(Environment.java:876)
	at freemarker.core.Environment.invokeMacro(Environment.java:812)
	at freemarker.core.UnifiedCall.accept(UnifiedCall.java:84)
	at freemarker.core.Environment.visit(Environment.java:370)
	at freemarker.core.Environment.invokeNestedContent(Environment.java:620)
	at freemarker.core.BodyInstruction.accept(BodyInstruction.java:60)
	at freemarker.core.Environment.visit(Environment.java:370)
	at freemarker.core.Environment.invokeMacroOrFunctionCommonPart(Environment.java:876)
	at freemarker.core.Environment.invokeMacro(Environment.java:812)
	at freemarker.core.UnifiedCall.accept(UnifiedCall.java:84)
	at freemarker.core.Environment.visit(Environment.java:370)
	at freemarker.core.Environment$NestedElementTemplateDirectiveBody.render(Environment.java:3244)
	at org.primeframework.mvc.control.FreeMarkerBodyProxy.render(FreeMarkerBodyProxy.java:42)
	at org.primeframework.mvc.control.AbstractControl.renderBody(AbstractControl.java:78)
	at org.primeframework.mvc.control.FreeMarkerControlProxy.execute(FreeMarkerControlProxy.java:62)
	at freemarker.core.Environment.visit(Environment.java:451)
	at freemarker.core.UnifiedCall.accept(UnifiedCall.java:102)
	at freemarker.core.Environment.visit(Environment.java:370)
	at freemarker.core.Environment.invokeMacroOrFunctionCommonPart(Environment.java:876)
	at freemarker.core.Environment.invokeMacro(Environment.java:812)
	at freemarker.core.UnifiedCall.accept(UnifiedCall.java:84)
	at freemarker.core.Environment.visit(Environment.java:370)
	at freemarker.core.Environment.invokeNestedContent(Environment.java:620)
	at freemarker.core.BodyInstruction.accept(BodyInstruction.java:60)
	at freemarker.core.Environment.visit(Environment.java:370)
	at freemarker.core.Environment.invokeMacroOrFunctionCommonPart(Environment.java:876)
	at freemarker.core.Environment.invokeMacro(Environment.java:812)
	at freemarker.core.UnifiedCall.accept(UnifiedCall.java:84)
	at freemarker.core.Environment.visit(Environment.java:370)
	at freemarker.core.Environment.invokeNestedContent(Environment.java:620)
	at freemarker.core.BodyInstruction.accept(BodyInstruction.java:60)
	at freemarker.core.Environment.visit(Environment.java:370)
	at freemarker.core.Environment.invokeMacroOrFunctionCommonPart(Environment.java:876)
	at freemarker.core.Environment.invokeMacro(Environment.java:812)
	at freemarker.core.UnifiedCall.accept(UnifiedCall.java:84)
	at freemarker.core.Environment.visit(Environment.java:334)
	at freemarker.core.Environment.visit(Environment.java:340)
	at freemarker.core.Environment.process(Environment.java:313)
	at freemarker.template.Template.process(Template.java:383)
	at org.primeframework.mvc.freemarker.DefaultFreeMarkerService.render(DefaultFreeMarkerService.java:76)
	at org.primeframework.mvc.action.result.AbstractForwardResult.execute(AbstractForwardResult.java:93)
	at org.primeframework.mvc.action.result.DefaultResultInvocationWorkflow.perform(DefaultResultInvocationWorkflow.java:108)
	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:51)
	at org.primeframework.mvc.message.DefaultMessageWorkflow.perform(DefaultMessageWorkflow.java:44)
	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:51)
	at org.primeframework.mvc.scope.DefaultScopeStorageWorkflow.perform(DefaultScopeStorageWorkflow.java:62)
	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:51)
	at org.primeframework.mvc.workflow.DefaultErrorWorkflow.perform(DefaultErrorWorkflow.java:46)
	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:51)
	at io.fusionauth.app.primeframework.FusionAuthMVCWorkflow.perform(FusionAuthMVCWorkflow.java:91)
	at org.primeframework.mvc.workflow.DefaultWorkflowChain.continueWorkflow(DefaultWorkflowChain.java:44)
	at org.primeframework.mvc.servlet.FilterWorkflowChain.continueWorkflow(FilterWorkflowChain.java:50)
	at org.primeframework.mvc.servlet.PrimeFilter.doFilter(PrimeFilter.java:78)
	at com.inversoft.maintenance.servlet.MaintenanceModePrimeFilter.doFilter(MaintenanceModePrimeFilter.java:63)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.inversoft.servlet.UTF8Filter.doFilter(UTF8Filter.java:27)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:543)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:367)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:639)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:881)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1647)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by mooreds** [comment] 2022-06-13 17:06
I'm unable to recreate this bug on a vanilla 1.36.4 install.

A few qs:

1. Is the 1.36.4 install fresh, or did you upgrade?
2. Do you have a valid license?
3. Are the entity and the user in the same tenant?

**Comment by andrewpai** [comment] 2024-12-08 23:37
Closing this issue, as I am also unable to reproduce the behavior.

**Closed by andrewpai** 2024-12-08 23:37 UTC
Labels: needs more info
