### ISSUE TITLE
API Enable 2fa for user

### ISSUE THREAD

**Issue by xXBuilderBXx** [FusionAuth/fusionauth-issues#2459] opened 2023-09-10 15:17 UTC
### Description 
The FusionAuth API is returning a 421 Misredirect Request when using api/user/two-factor
```json
{
	"code": "123456",
	"method": "authenticator",
	"secret": "REDACTED"
}
```

### Affects versions
1.47.1 

### Steps to reproduce
1. Send a GET to api/two-factor/secret for secret
2. Send a POST request to api/user/two-factor
3. Returning unknown 421 error with no error messages

### Expected behavior
2FA with code setup on user account.

**Comment by mooreds** [comment] 2023-09-11 13:06
Is the code that you pass on step 2 generated by a TOTP implementation to which you provide the secret generated in step 1? If not, how is it generated?

A `421` indicates that `The code request parameter is not valid. The response will be empty.`, which seems to be point to an issue in how the code is generated.

**Comment by robotdan** [comment] 2023-09-12 08:53
This probably belongs in the FusionAuth forum unless there is a bug. My guess this is working as designed, but perhaps we need some additional documentation on how to use this API for various use cases. It does a lot of things.

**Comment by mooreds** [comment] 2023-09-12 10:46
@xXBuilderBXx please create a forum post: https://fusionauth.io/community/forum/ 

I'm closing this issue.

**Closed by mooreds** 2023-09-12 10:46 UTC
Labels: support, working as designed, moved to forum
