### ISSUE TITLE
Allow lambdas to call internal APIs

### ISSUE THREAD

**Issue by alapins** [FusionAuth/fusionauth-issues#1355] opened 2021-08-20 04:09 UTC
### Problem
I'd like to customize a JWT to include information about what entity roles the user is assigned.  This isn't currently supported out-of-the-box.  

### Solution
If I could call the existing APIs from within the lambda, however, I could add that information myself.  I could also add any type of information currently in the system.

### Alternatives/workarounds
None that I've been able to find in the documentation

### Additional context
I suppose I could do this manually, but the process of deserializing the JSON and setting up the API call with an API token seems daunting.  It would be great to be passed an "api" object that had methods corresponding to the public api and returning objects (i.e. a wrapper object containing references to the endpoint methods internally, skipping authentication).

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by robotdan** [comment] 2021-08-20 14:15
I think this is a duplicate of https://github.com/FusionAuth/fusionauth-issues/issues/229, if so, please upvote it.

**Comment by mooreds** [comment] 2022-08-16 03:10
I think this is a duplicate of https://github.com/FusionAuth/fusionauth-issues/issues/267 (which lets you make HTTP calls to any API, including to FusionAuth).

@alapins please comment if not and I'll re-open.

**Closed by mooreds** 2022-08-16 03:10 UTC
