### ISSUE TITLE
Add A Webhook Event to listen for Idp Link and Unlink on the user

### ISSUE THREAD

**Issue by jobannon** [FusionAuth/fusionauth-issues#1589] opened 2022-02-04 23:09 UTC
### Problem
I want to know when a user is linked or unlinked to an IdP via a webhook.

### Solution
Add a webhook event.

### Documentation
- [x] New event types
- [x] Webhook API updates?
- [x] Tenant API updates 
- [x] UI updates for webhooks or tenants?

### Related
- https://github.com/FusionAuth/fusionauth-issues/issues/1525

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

Internal - https://inversoft.slack.com/archives/C01TJLP2HQ8/p1644015556118649

**Comment by robfusion** [comment] 2022-04-05 18:37
- <https://github.com/FusionAuth/fusionauth-api/pull/52>
- <https://github.com/FusionAuth/fusionauth-java-client/pull/28>
- <https://github.com/FusionAuth/fusionauth-app/pull/117>
- <https://github.com/FusionAuth/fusionauth-client-builder/pull/44>

**Comment by glen-84** [comment] 2022-04-14 19:08
May be a duplicate of #1525.

**Comment by glen-84** [comment] 2022-04-24 12:59
Is there any reason why these hooks are non-transactional? If you want to sync the data to an external system, a failure would result in missing data in the external system.

**Comment by mooreds** [comment] 2022-04-25 22:48
Transactional means something a bit different when it comes to FusionAuth webhooks. It allows you to interrupt FusionAuth processing. Is that what you'd want? 

Here's the scenario (with transactional webhooks):

* User links account
* FusionAuth fires webhook
* External system returns non 2xx value
* FusionAuth fails to save link

Can you tell me a bit more about your use case?

**Comment by glen-84** [comment] 2022-04-26 18:36
> Is that what you'd want?

Yes, otherwise the link can be saved in FA but not in the external system.

> Can you tell me a bit more about your use case?

Storing link data in our database, in case we want to switch back to an in-house solution later. I suppose this data would also be available in exports, so it's not critical, but I think that it might make more sense for them to be transactional.

Have you considered making the transactionality (not a word) a flag/setting per hook? (a checkbox `[x] Transactional`)

**Comment by mooreds** [comment] 2022-04-26 20:41
Thanks @glen-84 appreciate you sharing the use case. 

As you say, this data is available via the API so you could export it if/when you wanted to move in-house. Might be a pain to migrate depending on how many users you have, though.

I think you could file an issue to make these transactional; I don't know if there's an inherent reason they aren't.

**Comment by glen-84** [comment] 2022-04-30 08:26
> Might be a pain to migrate depending on how many users you have, though.

I was under the impression that a SQL export would be provided on request, is that not true?

> I think you could file an issue to make these transactional; I don't know if there's an inherent reason they aren't.

I would prefer to wait for a response from one of the developers, to avoid wasting time if they have no intention of changing this.

**Comment by mooreds** [comment] 2022-04-30 14:04
> I was under the impression that a SQL export would be provided on request, is that not true?

Yup, as [specified in the cloud guide](https://fusionauth.io/docs/v1/tech/installation-guide/cloud#accessing-user-data) you can absolutely get a data export if you want to transition from FusionAuth Cloud.

**Comment by robotdan** [comment] 2022-05-01 23:45
@glen-84 this is a completed / delivered issue. We leave issues open until documentation has completed. 

Thanks for your questions / request re: TX, can you please open a GH issue for this, questions on completed issues generally will be lost unless they are tracked as part of a discrete GH issue. Thanks.

**Closed** 2022-05-09 19:45 UTC
Labels: enhancement
