### ISSUE TITLE
Allow filtering by custom data

### ISSUE THREAD

**Issue by atrauzzi** [FusionAuth/fusionauth-issues#2911] opened 2024-11-02 13:45 UTC
### Problem
When I'm searching for any specific record, it would be nice if I could apply filters based on custom data I've tagged the various types with.

### Solution
Some form of filtering expression when executing the various search endpoints that will apply to the `data` property of objects.

### Alternatives/workarounds
Right now I have to fetch data and check it myself.  Not a huge deal, but if I was ever in a scenario where I had to worry about pagination, it makes the implementation kind of yucky on my end.

### Additional context
Even just being able to do an equality check of some form, or if the feature only supported simple types like strings, numbers, etc...  That would be useful!

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by mooreds** [comment] 2024-11-04 20:52
@atrauzzi I'm not sure I understand the context. 

Are you looking for the ability to narrow down the results of a search in some fashion? Or narrow down the data returned (so you only get user emails, for example)?

Can you please provide more details about what you are looking for? Maybe an example of what the data looks like and what you'd like to query on?

**Comment by mooreds** [comment] 2024-11-05 02:28
Ah, you can do that right now, as long as you are using the elasticsearch search engine. Here's doc on how to change search engines: https://fusionauth.io/docs/lifecycle/manage-users/search/switch-search-engines

Please review this doc with example queries: https://fusionauth.io/docs/lifecycle/manage-users/search/user-search-with-elasticsearch#searching-with-query

Please close the issue if that functionality meets your needs, otherwise please provide us with more details.

**Comment by mooreds** [comment] 2024-11-05 15:53
Ah, thanks for clarifying. In this case, I believe this is a duplicate of https://github.com/FusionAuth/fusionauth-issues/issues/745 . Here's what our CTO said on that issue:

> If you require full text search, the recommendation is always going to be use Elasticsearch or OpenSearch.
> ...
> I don't see us ever building out search DSL for database since Elasticsearch has already solved this.

I'd suggest adding as much detail as you can to issue 745 to see if there's an aspect of this that we haven't considered.

That said ES/OpenSearch is so powerful and solves this for us so well that I doubt we'd improve the database search to the level you're looking for; it is certainly not on the short term roadmap.

**Closed as completed** 2024-11-05 16:12 UTC
Labels: needs more info
