### ISSUE TITLE
Authorization with scope openid fails when 2FA is enabled

### ISSUE THREAD

**Issue by StanislavKD** [FusionAuth/fusionauth-issues#53] opened 2018-12-12 16:45 UTC
### Description 
Getting an error in a nextcloud when trying to authorize with two-factor authorization (without 2fa all is ok)(error: "No id_token was found". after refresh page: "Can not get identifier from provider"). 

### Steps to reproduce
1. nextcloud/settings/admin/sociallogin
2. Add Custom OpenID Connect:
Authorize url: fusionauth:9013/oauth2/authorize
Token url: fusionauth:9013/oauth2/token
Client Id: Client Id
Client Secret: Client Secret

Authorization is successful, everything works. But if the user enable 2fa, then he will not enter to nextcloud. After entering the code from the google authenticator, we get the errors error: "No id_token was found". after refresh page: "Can not get identifier from provider". Everything works well, if the authorization is not on nextcloud. If authorization on fusionauth:9013 with 2fa enabled, and then manually go to nextcloud, then everything is fine and the authorization passes.

### Platform
 - OS: ubuntu 18.04
 - Browser: Firefox, Chrome

### Additional context
Thank you for you great product.

**Comment by robotdan** [comment] 2018-12-12 20:15
Hi @StanislavKD thank you for letting us know about this issue. 

So to clarify the scenario, you configure FusionAuth as an OpenID Connect provider in NextCloud, and then when a user logs into FusionAuth, they first are prompted with the FusionAuth login page at `/oauth2/authorize`. 

Upon a successful login, if 2FA is enabled, they will be redirected to `/oauth2/two-factor` where the user will need to enter their challenge code. Upon a successful completion of the 2FA step, the user should then be redirected back to the requested `redirect_uri` that was provided when they were first redirected to the `/oauth/authorize` action. So, in theory - this should work just fine with NextCloud. 

If an error is being returned that says no `id_token` - perhaps the scope `openid` is being lost in this workflow? 

I can do some testing on my end to see if that is a possibility. I am assuming that since this works without 2FA enabled for a user, that you are indeed passing in the `openid` scope during the Authorize request? 

Thanks for brining this to our attention, I'm sure we can get to the bottom of this issue.

**Comment by robotdan** [comment] 2018-12-12 20:51
Hi @StanislavKD I think I've identified the bug. Once I can confirm and verify a fix, I will get this out in a patch release. 

Thanks! Let us know if you encounter any other issues.

**Comment by StanislavKD** [comment] 2018-12-13 08:34
Dear robotdan. Thank you for your help and quick response. If you need a test environment with a nextcloud and fusionauth then let me know. I'll wait the patch. Thank.

**Comment by robotdan** [comment] 2018-12-19 18:03
Fixed in version 1.3.1.

**Closed by robotdan** 2018-12-19 18:03 UTC
Labels: bug
