### ISSUE TITLE
E-Mail Address Verification: second click on link in E-Mail leads to repeated call to verify

### ISSUE THREAD

**Issue by oxyuranus-scutellatus** [FusionAuth/fusionauth-issues#1421] opened 2021-10-04 13:07 UTC
### Description 
A user makes a new registration in FusionAuth. The configuration of FusionAuth requires the user to verify his/her e-Mail address and receives an e-mail containing a verification link. The first click verifies the e-mail address. The _second_ click leads to a "loop":

- GET http://localhost:9011/email/verify/bCfV2Cz8dEJ1Op3KVy0qxFDB5u4-qc14GLLYSEB-ERI?client_id=e5b44aaa-e458-4409-9a14-8079fcf793df&postMethod=true&tenantId=30466e99-2809-11eb-80e9-0242ac1b1000
- GET http://localhost:9011/js/prime-min-1.5.3.js?version=1.27.2
- GET http://localhost:9011/js/oauth2/LocaleSelect.js?version=1.27.2
- POST http://localhost:9011/email/verify
- ... an so on

### Affects versions
At least 1.27.2

### Steps to reproduce
1. Make a (quite) sophisticated setup with kickstart in a docker container, mapping needed resources as e-mail templates, themes, and messages, starting with version i.e. 1.24.
2. Update docker images to versions 1.25, 1.26, 1.27.1 with the existing DB ("...One or more API keys have already been added. Cannot kickstart.")
3. Update your DB-Setup via the FusionAuth API: e-mail templates 1.27.2 (/api/email/template), new themes 1.27.2 (/api/theme)
4. Start up: docker compose up -d ...
5. Register as new user in FusionAuth.
6. Inspect e-mail from FusionAuth in order to verify your e-mail address.
7. Klick link in e-mail (=> ok).
8. Klick link in e-mail a _second_ time.
9. Browser stays in "loop".

### Expected behavior
Link should be invalid the _second_ time it is clicked.

### Screenshots
Refer to attachments.

### Platform
 - Device: Desktop
 - OS: may not be related to OS, but docker 20.10.8 on macOS, Windows 10
 - Firfox 92.0.1 (64-bit) and Chromium: 94.0.4606.71 (Offizieller Build) (64-Bit)
 - Database Percona 5.7.32-centos

### Additional context
#629 seems to be fixed but this new one is introduced (IMHO).

[har-first-and-second-click-on-link-in-email.zip](https://github.com/FusionAuth/fusionauth-issues/files/7278168/har-first-and-second-click-on-link-in-email.zip)

<img width="1207" alt="VerifyEmailSecondTimeEndlessLoop" src="https://user-images.githubusercontent.com/63788454/135856539-e87cf4df-6e83-4848-b4e9-8a30505ce8f9.png">

**Comment by mooreds** [comment] 2023-01-03 16:01
Is this still an issue on later versions, @oxyuranus-scutellatus ? What is the latest version you've replicated this on?

**Comment by oxyuranus-scutellatus** [comment] 2023-01-03 16:56
We are still using the same version as indicated. Why should the issue have been resolved magically after investigating nothing within more than one year? No desire to upgrade.

**Comment by mooreds** [comment] 2023-01-03 17:14
thanks @oxyuranus-scutellatus

**Comment by robotdan** [comment] 2023-08-23 23:50
Possibly a duplicate of 
- https://github.com/FusionAuth/fusionauth-issues/issues/2360


Please re-open if you can recreate after version 1.47.0. 
- https://fusionauth.io/docs/v1/tech/release-notes

**Closed by robotdan** 2023-08-23 23:50 UTC
Labels: triage
