### ISSUE TITLE
Account Lock On User Action- Email not fired

### ISSUE THREAD

**Issue by jobannon** [FusionAuth/fusionauth-issues#1801] opened 2022-07-28 21:10 UTC
### Description 
When enabling an account lockout using a user action, when the user is locked, an email is not sent to that user (even when configured)

### Affects versions
1.36.7

### Steps to reproduce
1. Make a user action.
2. Set the action to send an email (`Email user` option)
3. Setup email
4. Lock the account (fail login multiple times)
5. No email is sent to user

### Expected behavior
The user should be sent an account lockout email notification.

### Platform
(Please complete the following information)
 - Device: [e.g. Desktop, iPhone X, Pixel 3, etc]
 - OS: [e.g. iOS, macOS, Windows ME]
 - Browser + version [e.g. chrome, safari plus a version]
 - Database [MySQL | PostgresSQL] & and version

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

**Comment by robotdan** [comment] 2022-08-02 03:05
Is this a duplicate of https://github.com/FusionAuth/fusionauth-issues/issues/1654 ? Please try and recreate on version 1.36.7 or later.

**Comment by robotdan** [comment] 2022-08-08 03:06
Closing this out - if anyone can recreate after version 1.36.7 w/ the fix from the referenced issue, please re-open.

**Comment by jobannon** [comment] 2022-08-10 23:25
Tested on local on latest (netty web server release 😎 ).  Still does not fire an email when 

1. A user action is set up.  This action prevents login and is triggered after `N` failed login attempts. 
2. A user triggers the user action via failed login attempts on hosted login pages.  Gets a message saying "your account has been locked"
4. No email is sent to the user of the start, cancel, modify, or end of that action preventing login.

**Closed** 2022-08-11 21:00 UTC
Labels: bug
