### ISSUE TITLE
Password settings should either display all rules that aren't met below the input field or display green/or red check marks to indicate whether a password setting condition has been met

### ISSUE THREAD

**Issue by jaywood128** [FusionAuth/fusionauth-issues#2042] opened 2023-01-06 17:34 UTC
### Description 
When all or more than two Password Settings are enabled under `Tenant > Password Settings`, and a password fails all or more than two validation errors on the`Change Password Form` page that ships with the Default FusionAuth Theme, such as does not meet the min length, does not contain a number, a special character, upper & lower case, etc. only the first two errors are displayed below the input field. It would be nice to see all the rules the password is failing. 

### Affects versions
1.42 

### Steps to reproduce
1. Set Password settings under `Passwords`. Turn all options one or more than 2. 
2. Copy and paste the Application's Login URL into an incognito tab
3. Click the Forgot Password link
4. Verify email and perform any MFA
5. Type in a password that meets none of the requirements such as `pa`. 
6. Not the errors displayed below the input field - there should only be the first two for `Password does not meet the minimum length requirement, Password requires upper and lower case characters`. 

### Expected behavior
It would be a better user experience if each of the requirements had either a green check mark or a red x as a user is entering it, to after the incorrect password. 

### Screenshots

![image](https://user-images.githubusercontent.com/12218379/211064604-f7a8810d-f81a-4a93-860b-b1331be12234.png)

### Platform
(Please complete the following information)
 - Desktop
 - macOs
 - Chrome
 - PostgresSQL 

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

**Comment by robotdan** [comment] 2023-01-09 15:44
@jaywood128 can you please check if this is due to the theme and how the errors are displayed, or if the API is not returning all of the field errors?

**Comment by jaywood128** [comment] 2023-01-17 16:55
@robotdan this is for the Change Password Form that ships with the default FusionAuth Theme. The template should be displaying all the errors but only the first two show. I will have to get with the User API to see if the behavior is the same. https://fusionauth.io/docs/v1/tech/apis/users#request-15

**Comment by robotdan** [comment] 2024-06-15 01:06
Closing. Please re-open if there is a bug here, but it appears this is working as designed. 

The current design is to allow the end user to display all of the password rules all the time, or optionally only once the user fails to meet the requirements. 

Then separately the errors displayed below the field should represent the rules that are not met.

**Closed by robotdan** 2024-06-15 01:06 UTC
Labels: needs more info
