### ISSUE TITLE
Create and Delete user in rapid succession may result in an Elasticsearch error returning 404

### ISSUE THREAD

**Issue by robotdan** [FusionAuth/fusionauth-issues#913] opened 2020-10-05 20:49 UTC
### Description 
When we delete a user we try to also remove that user from the Elasticsearch index. If the re-index request returns `404` we may fail the delete operation. 

### Affects versions
All?

### Steps to reproduce
1. Create a user
2. Delete a user

```
{
  "code": "[SearchEngineRequestFailedException]",
  "message": "A request to the search index has failed. This error is unexpected. Contact Support."
}
```

Exception in the log

```
2020-10-05 8:38:02.910 PM DEBUG com.inversoft.search.AbstractElasticSearchSearchEngine - ElasticSearch request failed.
org.elasticsearch.client.ResponseException: method [DELETE], host [http://localhost:9021], URI [/fusionauth_user/_doc/0f600100-48b8-44ad-97f9-e906d4c9f02e], status line [HTTP/1.1 404 Not Found]
{"_index":"fusionauth_user","_type":"_doc","_id":"0f600100-48b8-44ad-97f9-e906d4c9f02e","_version":5,"result":"not_found","_shards":{"total":2,"successful":2,"failed":0},"_seq_no":27787,"_primary_term":1}
	at org.elasticsearch.client.RestClient.convertResponse(RestClient.java:302)
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:272)
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:246)
	at com.inversoft.search.AbstractElasticSearchSearchEngine.request(AbstractElasticSearchSearchEngine.java:240)
	at io.fusionauth.api.service.search.ElasticsearchSearchEngine.delete(ElasticsearchSearchEngine.java:75)
	at io.fusionauth.api.service.user.DefaultUserService._delete(DefaultUserService.java:1948)
	at io.fusionauth.api.service.user.DefaultUserService.delete(DefaultUserService.java:594)
```

### Expected behavior
We could optionally ignore this ES failure but we should probably determine why the document does not exist. It is possible it has not yet been replicated between shards.

**Comment by iveelsm** [comment] 2020-10-08 20:03
I was unable to reproduce this issue within my testing. Here are some notes from my testing.

Initially I attempted to use the UI as a means of reproducing this problem. I attempted to create and delete a user as quickly as I could through the interface. After a few attempts, it yielded no results.

Next I attempted to make api calls via `/api/user` with a POST and a DELETE request. I would send the request to create the user, then assert the database had written said user, then remove the user. This test was insufficient to prove the problem. I attempted to remove the database assertion as a means of speeding this up, however was still unable to reproduce it.

Next, I remove the api call for the POST, instead creating an existing user via service calls and then executed the subsequent DELETE request. This was attempted 1000 times in rapid succession. None of the 1000 attempts were able to reproduce the condition.

I continued this line of testing, executing this test against 4 different Elasticsearch versions, the following were tested:

* 6.3.1
* 6.8.9
* 7.6.1
* 7.7.1

None of these versions were able to produce the condition for the error. While I do see some potential for creating this problem, it would result in a strange use case (doing a bulk insert and then bulk delete of group members added) and that bug would actually be testing a different Elasticsearch API (`_bulk` instead of `_doc/<id>`).

Therefore I am moving this bug to be closed.

**Comment by prasanna10021991** [comment] 2020-10-20 12:26
Hi @robotdan ..I'm facing the same issue with my FA deployment as ElasticSearch has locked itself now and not able to create or delete users. Has this issue been resolved and if so should I wait till the next release or is there something that I can fix up to resolve this issue in elasticsearch

**Comment by robotdan** [comment] 2020-10-20 19:13
@prasanna10021991 can you provide a detailed set of steps to recreate the issue?

**Comment by prasanna10021991** [comment] 2020-10-20 19:43
> @prasanna10021991 can you provide a detailed set of steps to recreate the issue?

Hi @robotdan .. thank you for the prompt reply. But I've found the reason to be space shortage on elastic search which automatically activates the read_only index locks on the elastic search service.
 So once the container space is increase and by forcefully updating the settings to reset the read_only locks was able to resolve this. So I guess that's should give an idea for anyone facing the issue.

**Closed** 2021-02-24 17:04 UTC
Labels: bug, unreproducible
