### ISSUE TITLE
Enforce obfuscation of sensitive information across all fields of the Admin UI

### ISSUE THREAD

**Issue by jobannon** [FusionAuth/fusionauth-issues#1302] opened 2021-07-09 18:41 UTC
### Problem
FusionAuth currently hides some clearly sensitive information, such as API keys within the Admin UI.  However, it does not currently hide ALL possibly sensitive information in the Admin UI.  
_______________________
To be clear, the security of FusionAuth as a product is not in question.  This is a request to help site admins and devs keep sensitive information secure from accidental-screenshot-oversharing or over-the-shoulder prying eyes.
______________________

### Solution
Enforce the intentional hiding of 
- Some client ID's
- All Client Secrets
- Any other sensitive UUID's (reactor instance id?)

### Alternatives/workarounds
Be aware of how you are using the Admin UI when you are accessing sensitive information.

### Additional context
We have two working solutions already implemented:
1.  On the tenant, once you enter an email password, for instance, your only option is to change it. You cannot see what was previously entered:
![image](https://user-images.githubusercontent.com/16090626/125122042-12d9db80-e0b2-11eb-9f07-81665eaf0efd.png)
1. On key master or API keys we have a `click here` button to see the secret
Example with "test" key:
![image](https://user-images.githubusercontent.com/16090626/125122323-81b73480-e0b2-11eb-8098-12b1b77349df.png)

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by robotdan** [comment] 2021-07-12 13:52
Duplicate of https://github.com/FusionAuth/fusionauth-issues/issues/1059 ?

**Closed** 2024-10-09 17:53 UTC
Labels: enhancement
