### ISSUE TITLE
Trouble with SAML and OpenID logins

### ISSUE THREAD

**Issue by davidmw** [FusionAuth/fusionauth-issues#181] opened 2019-06-14 04:31 UTC
### Description 
FusionAuth doesn't seem to be handling the response from the IdP.

### Steps to reproduce
We have multiple IdP configured. These appear on our FusionLogin screen and clicking one takes the user to the IdP. It authenticates and redirects back to FusionAuth with token.  FusionAuth doesn't seem to be handling that response. We've followed the document closely when configuring FusionAuth but it is possible something has been overlooked.

We get these errors:

A request to the OpenID Connect Token API has failed. Unable to complete this login request. The authentication request has failed. The login request failed.

With SAML:  FusionAuth encountered an unexpected error. Please contact support for assistance.

There is nothing logged in our Event Log.

### Platform
Fusion 1.6.1

**Comment by robotdan** [comment] 2019-06-14 13:21
We'll hopefully be adding a debug option for these IdP configurations to create events logs in the near future. 

Currently any errors that occur during this step will be written to the FusionAuth log. If you have access to that you can attach the exception here. 

`/usr/local/fusionauth/logs/fusionauth-app.log` if installed via RPM or Deb, or wherever you installed FusionAuth you'll find the `logs` directory. 

What type of IdP are you connecting to for OpenID Connect and SAML v2? Is this Azure AD, AD, etc ?

**Comment by davidmw** [comment] 2019-06-17 06:20
This is an example entry from the log: 

`Jun 14, 2019 9:08:12.364 AM WARN  org.primeframework.mvc.message.l10n.ResourceBundleMessageProvider - Message could not be found for the URI [/api/identity-provider/login] and key [[missing]SAMLResponse]
Jun 14, 2019 9:08:12.365 AM ERROR io.fusionauth.app.primeframework.error.ExceptionExceptionHandler - An unhandled exception was thrown
org.primeframework.mvc.message.l10n.MissingMessageException: Message could not be found for the URI [/api/identity-provider/login] and key [[missing]SAMLResponse]
	at org.primeframework.mvc.message.l10n.ResourceBundleMessageProvider.getMessage(ResourceBundleMessageProvider.java:80)`

The IdP with this error is https://studentnet.net/cloudwork.php (SAML).  At the moment the OpenID example (wonde.com) is complicated with an invalid token returned to us and this fact is evident in the log.

**Comment by voidmain** [comment] 2019-06-17 14:21
Hi @davidmw. This is an error with FusionAuth missing a localized message for an error it is encountering but that doesn't look to be the root cause of the SAML issue. The interesting part is that it looks like the external IdP is sending back an empty response. This is what the error `[missing]SAMLResponse` normally indicates. However, without the full logs, I can't determine where that error is coming from.

I'm also assuming that this is through a SAML login using the FusionAuth OAuth front-end, meaning that the browser is navigating to FusionAuth's OAuth 2 Authorize endpoint. From there the user clicks on a `Login with X` button that navigates them to the SAML IdP. After they successfully log into the SAML IdP, the browser is redirected (actually it's a form post for SAML) back to FusionAuth's `/oauth2/callback` endpoint. From here, FusionAuth will attempt to call its own `/api/identity-provider/login` API to handle the SAML response.

If that all sounds accurate, then this looks like an issue where the SAML response is missing. Perhaps the IdP is not correctly encoding and `POST`-ing the form that sends back the SAML response. You can also open the inspector in the browser and see all of these steps and ensure that the SAML response is correctly being written out to the HTML and then JavaScript should be submitting the form using something like `document.forms[0].submit();`.

Also, if you can attach the log files, that would help us figure out the root cause.

**Comment by prabhakarreddy1234** [comment] 2019-06-17 18:40
@voidmain  I am working in the same team as the author. From the browser dev toolbar i see that there is a SAML Response posted to `/oauth2/callback` endpoint. But it's missing/not handled afterwards.
![saml-response](https://user-images.githubusercontent.com/1984707/59628064-a476f900-9137-11e9-8d2f-86fbc73475f8.png)

Attached logs:

[logs-from-fusionauth-in-fusionauth-fdb7976d6-g8rt4 (1).txt](https://github.com/FusionAuth/fusionauth-issues/files/3298377/logs-from-fusionauth-in-fusionauth-fdb7976d6-g8rt4.1.txt)

**Comment by prabhakarreddy1234** [comment] 2019-06-18 18:26
@robotdan Any input on this issue or pointers on how to troubleshoot. Can't see much useful logs to make progress on it.

**Comment by robotdan** [comment] 2019-06-18 18:40
You could try adding the following like to `web/WEB-INF/messages/package.properties`.

`[missing]SAMLResponse=Missing response`

This should fix the exception so we can see the original cause. So if you can add that message, them recreate and attach the logs.

**Comment by prabhakarreddy1234** [comment] 2019-06-18 20:24
I added the message as you said. Now i'm not seeing any error on fusionauth UI but also not seeing any logs. We hosted fusionauth on AKS.

I added a `SAML v2 reconcile Lambda` to print samlResponse on console. Still no trace of these logs in `event log` or `hosted fusionauth server`.

**Comment by davidmw** [comment] 2019-06-19 00:27
It might be more efficient to schedule a call and for us to provide SAML & OAuth (with login details) configurations for you to try from a local instance.  It is best to schedule something to fit @prabhakarreddy1234 availability (London) and I'll join from Sydney if possible.

**Comment by robotdan** [comment] 2019-06-19 16:22
I won't be in the office until next week, we could try to set up a call then. If you want to jump on the Slack channel and DM me we may be able to try to recreate if you share some of your configuration details.

**Comment by voidmain** [comment] 2019-06-19 18:58
Hi everyone. Sorry everyone for the delay. I've been coding my face off, trying to get some things done before I head out for vacation. I can probably hop on a call this afternoon or tomorrow morning early to discuss this. You can send me your email here or fill out the contact form on the website.

Also, SAML parse errors will be logged to the Event Log in FusionAuth 1.6.0+. Therefore, if you do have a `SAMLResponse` coming in that can't be parsed, the error might there.

I have looked through the code and we did a lot of testing for SAML providers like Azure, Google, Pivotal, Zendesk, Keycloak and others. I don't see any reason that the error you are describing would be thrown if you have the correct `SAMLResponse` form parameter being sent from the SAML IdP. 

Any other information you all can provide to help would be great. Logs, event logs, etc.

Thanks.

**Comment by voidmain** [comment] 2019-06-19 19:02
Ignore most of my last comment. I think I found the error in the code that is causing this problem. I'm doing some investigation into how it got changed, but it looks like a naming issue. This fix should be simple and I can roll a release with the fix later today.

**Comment by robotdan** [comment] 2019-06-19 22:17
Fix is in 1.7.2 which is released. 
https://fusionauth.io/docs/v1/tech/release-notes/

Let us know how it goes, this contains Brian's fix.

**Comment by robotdan** [comment] 2019-06-19 22:18
> A request to the OpenID Connect Token API has failed. Unable to complete this login request. The authentication request has failed. The login request failed.


Was there still an OpenID Connect issue as well?

**Closed** 2019-06-19 22:35 UTC
Labels: bug, support

**Comment by prabhakarreddy1234** [comment] 2019-06-20 08:57
@robotdan  Thanks. Latest release fixed SAML issue. But still having trouble with Open Id Connect. Getting same error as earlier.

External Idp is returning `code` to fusionauth `/callback`.  Getting error while exchanging this `code` for `token`. 

I see this in event log:

`Call to OpenIDConnect [https://edu.wonde.com/oauth/token] API failed. Status code [400]

Unable to parse OpenID Connect response. Exception encountered.

com.inversoft.rest.JSONException : Message: Failed to parse the HTTP response as JSON. Actual HTTP response body:
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>InvalidArgument</Code><Message>Unsupported Authorization Type</Message><ArgumentName>Authorization</ArgumentName><ArgumentValue>Basic NjcwMzE5OjdhYzdlM2NlMWFmOWFmMjY0MjA5YzkyNjg3Y2NjMmZkYWY4NDUxYjc=</ArgumentValue><RequestId>6ACA48D7C50F7B22</RequestId><HostId>mL2J807dycg7fSr9T1s27p3bfmg0IVda2ucZskr5Ek7wuedYfigOJjMqrfL56MsNQ7paNWjRuKs=</HostId></Error>`

**Comment by robotdan** [comment] 2019-06-20 14:44
Moving the OpenID Connect issue that @prabhakarreddy1234 is encountering to a separate issue since this SAML issue has been resolved. 

https://github.com/FusionAuth/fusionauth-issues/issues/189
