### ISSUE TITLE
No option to disable email template at the application level

### ISSUE THREAD

**Issue by davidmw** [FusionAuth/fusionauth-issues#950] opened 2020-10-25 09:02 UTC
### Description 
Removing original issue, leaving this one:

If email is enabled at tenant level - there is currently no option to disable the template at the application level.

### Affects versions
1.19.8

**Comment by robotdan** [comment] 2020-10-27 04:11
Can you describe this a bit further so I understand what the issue is? Is there a particular workflow or email template that is not working how it should?

**Comment by andrewpai** [comment] 2024-04-27 19:44
Closing this issue as it isn't clear what was being asked.

**Closed by andrewpai** 2024-04-27 19:44 UTC
Labels: needs more info
