### ISSUE TITLE
Allow for rehashs on password change

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-issues#1450] opened 2021-10-20 16:17 UTC
### Problem

When using a plugin, I want to rehash on password change, not just on login.

### Solution

A configuration parameter similar to that defined here: https://fusionauth.io/docs/v1/tech/plugins/custom-password-hashing/#rehashing-user-passwords that lets you rehash on password change.

### Alternatives/workarounds

n/a

### Additional context

Mentioned on a support ticket (72053).

When this changes, update the docs referenced in this PR: https://github.com/FusionAuth/fusionauth-site/pull/1056

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by robotdan** [comment] 2022-01-26 23:43
Duplicate of https://github.com/FusionAuth/fusionauth-issues/issues/1062.

**Closed by robotdan** 2022-01-26 23:43 UTC
Labels: enhancement
