### ISSUE TITLE
Review Google Implementation

### ISSUE THREAD

**Issue by jobannon** [FusionAuth/fusionauth-issues#1894] opened 2022-09-23 01:55 UTC
### Description
Google may be changing how services operate per this announcement.  Review for needed changes in FusionAuth.

- https://developers.googleblog.com/2022/03/gis-jsweb-authz-migration.html

### Related
- https://github.com/FusionAuth/fusionauth-issues/issues/1911
- https://github.com/FusionAuth/fusionauth-issues/issues/1939

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

Internal - ticket 72837

**Comment by spwitt** [comment] 2023-02-22 20:41
If the Google IdP is configured with the redirect login method, then there are no changes required.

FusionAuth uses a separate redirect process that is shared between a few different IdPs rather than redirect the user to Google directly. This workflow does not currently invoke the JavaScript API that is being deprecated.

The popup login method will require changes to be supported after March 31. I'm still working on a solution, but at this point I think that customers will be able to get around Google's API being deprecated with template updates (i.e. it will not require upgrading FusionAuth).

**Comment by spwitt** [comment] 2023-02-23 15:26
**UPDATE**

FusionAuth offers two login methods for the Google IdP: redirect and popup. These can be configured in _Settings > Identity Providers > Edit Google_.

If your Google IdP is configured to _Use redirect for login_, then **you are not impacted by the upcoming library deprecation**.

If your Google IdP is configured to _Use popup for login_, then prior to the March 31, 2023 deadline you must either:

1. Change your login method to _Use redirect for login_
2. Update to a new version of FusionAuth with the Google IdP client-side fixes (in progress)

![image](https://user-images.githubusercontent.com/3409780/220948851-bcb0513b-41db-4302-9bf7-ca7d0c533222.png)

_More info_

I used Google's `G_AUTH2_MIGRATION` cookie with a value of `informational` ([link](https://developers.google.com/identity/gsi/web/guides/migration#identifying_affected_code_and_testing)) to log console warnings when it detects that the client invokes deprecated JavaScript APIs. Based on this testing I found that:

* When the login method is _Use redirect for login_, nothing is logged to the console
* When the login method is _Use popup for login_, there is a message logged to the console

```
Your client application uses libraries for user authentication or authorization that will soon be deprecated. See the [Migration Guide](https://developers.google.com/identity/gsi/web/guides/gis-migration) for more information.
```

I tested and observed the same behavior across the following browsers on macOS:
* Chrome
* Firefox
* Safari
* Brave
* Edge

**Comment by spwitt** [comment] 2023-02-23 20:17
Closing this as a duplicate of
- https://github.com/FusionAuth/fusionauth-issues/issues/1939

Further updates on the migration to Google Identity Services will be tracked there.

**Closed by spwitt** 2023-02-23 20:17 UTC
Labels: internals
