### ISSUE TITLE
Unable to fetch user data after 10,000 users

### ISSUE THREAD

**Issue by umangbholasamagra** [FusionAuth/fusionauth-issues#701] opened 2020-06-24 14:08 UTC
### Description 
I am trying to fetch the user list on Fusion Auth Console, whenever the pagination crosses number of users beyond 10,000, it renders an error. 
The same issue crops up whenever I try to hit Search Users API (api/user/search), and send startRow beyond 10,000
### Steps to reproduce
Steps to reproduce the behaviour:
1. Go to Fusion Auth Console, Go to users
2. Set number of rows in page 500,  keep going till Page 20, Click on 21st page, the error dialog will appear.
3. Send  a POST Request to /api/user/search API, and set the query request Body as follows
4. Request Body:

{"search":{"queryString":"(registrations.applicationId:{APPLICATION_ID})","sortFields":[],"numberOfResults":10,"startRow":10000}}

5. Following error would be returned:
{
    "statusCode": 500,
    "error": "Internal Server Error",
    "message": "Request failed with status code 503"
}

### Expected behavior
Users should appear
### Screenshots
Please refer attached screenshot to see error dialog on Fusion Auth Console
### Platform
(Please complete the following information)
 - Device: [e.g. Asus Vivobook]
 - OS: [e.g. Windows 10]
 - Browser + version [e.g.Chrome/ Safari]

![Annotation 2020-06-24 191905](https://user-images.githubusercontent.com/63345263/85571917-30c4d180-b652-11ea-8381-36b4cd06db1a.png)

**Comment by mooreds** [comment] 2020-06-24 14:15
Thanks for the feedback!

This looks like a duplicate of https://github.com/FusionAuth/fusionauth-issues/issues/494

If you agree, please close this issue. If not, please add more details on how it is different.

**Comment by mooreds** [comment] 2020-09-09 01:59
Closing because this is a duplicate.

**Closed by mooreds** 2020-09-09 01:59 UTC
Labels: duplicate
