### ISSUE TITLE
FusionAuth Elastic Queries Failing

### ISSUE THREAD

**Issue by Flavsditz** [FusionAuth/fusionauth-issues#1229] opened 2021-05-17 19:30 UTC
I have a FusionAuth setup with Elasticsearch.

When I try to filter by tenant everything works as expected. 
If I try to filter by application ID I get an error:
```
FusionAuth encountered an error while processing your request. If the problem persists, contact FusionAuth support for assistance.
```

I went into postman to check and for ANY Elastic query I get the same error. I went over the [documentation here](https://fusionauth.io/docs/v1/tech/apis/users/#search-for-users) and tried all different variations and I always get the same message:

```
{
    "fieldErrors": {
        "query": [
            {
                "code": "[invalid]query",
                "message": "The [query] field is invalid. Explanation [[{\"index\":\"fusionauth_user\",\"valid\":false,\"error\":\"[fusionauth_user/E8p3D6DASCKLloaVMlc_sQ] QueryShardException[failed to create query: {\\n  \\\"bool\\\" : {\\n    \\\"must\\\" : [\\n      {\\n        \\\"nested\\\" : {\\n          \\\"query\\\" : {\\n            \\\"bool\\\" : {\\n              \\\"must\\\" : [\\n                {\\n                  \\\"match\\\" : {\\n                    \\\"registrations.applicationId\\\" : {\\n                      \\\"query\\\" : \\\"c50329fa-93e5-4618-8d9f-73d0ab069a54\\\",\\n                      \\\"operator\\\" : \\\"OR\\\",\\n                      \\\"prefix_length\\\" : 0,\\n                      \\\"max_expansions\\\" : 50,\\n                      \\\"fuzzy_transpositions\\\" : true,\\n                      \\\"lenient\\\" : false,\\n                      \\\"zero_terms_query\\\" : \\\"NONE\\\",\\n                      \\\"auto_generate_synonyms_phrase_query\\\" : true,\\n                      \\\"boost\\\" : 1.0\\n                    }\\n                  }\\n                },\\n                {\\n                  \\\"match\\\" : {\\n                    \\\"registrations.roles\\\" : {\\n                      \\\"query\\\" : \\\"admin\\\",\\n                      \\\"operator\\\" : \\\"OR\\\",\\n                      \\\"prefix_length\\\" : 0,\\n                      \\\"max_expansions\\\" : 50,\\n                      \\\"fuzzy_transpositions\\\" : true,\\n                      \\\"lenient\\\" : false,\\n                      \\\"zero_terms_query\\\" : \\\"NONE\\\",\\n                      \\\"auto_generate_synonyms_phrase_query\\\" : true,\\n                      \\\"boost\\\" : 1.0\\n                    }\\n                  }\\n                }\\n              ],\\n              \\\"adjust_pure_negative\\\" : true,\\n              \\\"boost\\\" : 1.0\\n            }\\n          },\\n          \\\"path\\\" : \\\"registrations\\\",\\n          \\\"ignore_unmapped\\\" : false,\\n          \\\"score_mode\\\" : \\\"avg\\\",\\n          \\\"boost\\\" : 1.0\\n        }\\n      }\\n    ],\\n    \\\"adjust_pure_negative\\\" : true,\\n    \\\"boost\\\" : 1.0\\n  }\\n}]; nested: IllegalStateException[[nested] nested object under path [registrations] is not of nested type];; java.lang.IllegalStateException: [nested] nested object under path [registrations] is not of nested type\"}]]."
            }
        ]
    }
}
```

I am using:
- FusionAuth v 1.21.0 
- ElasticSearch v 7.6.2

I am not sure if I might have to do a re-indexing or something but since there is a big warning to not "just do that" I would like to ask first... I don't have a lot of experience with elastic but I really need this functionality to be working since we maintain 3 Applications and 2 Tenants under the same FusionAuth and we need to differentiate the users in an easier manner now that we have more than 100 users

Thanks for the awesome tool and support

**Comment by mooreds** [comment] 2021-05-17 19:56
Hi @Flavsditz ,

Thanks for using FusionAuth!

This looks like a support request. If you have a paid plan that includes support, please open a support ticket: https://account.fusionauth.io/account/support/

Otherwise, please post in our community forum: https://fusionauth.io/community/forum/

Closing because this is not a feature request or bug report with reproduction steps.

**Closed by mooreds** 2021-05-17 19:56 UTC
