### ISSUE TITLE
Login hint ignored. No way to force user to re-authenticate

### ISSUE THREAD

**Issue by JonasPrapuolenis** [FusionAuth/fusionauth-issues#1999] opened 2022-12-09 13:31 UTC
Login hint ignored. No way to force user to re-authenticate

### Description 
LoginHint is ignored if another user is already logged in. No way to workaround this issue when mobile app is re-installed.

### Steps to reproduce
1. User abc@company.com installs android app and opens it.
2. User enters  abc@company.com username in app. In the app there is a single username field to enter username. Entered value is then used as a login hint.
3. User presses 'next' button. This opens ChromeCustomTabs browser pointing to FusionAuth authorization endpoint. Login hint is passed into this endpoint.
4. User logs in and can fully use the app.
5. User uninstalls the app without logging out.
8. User xyz@company.com installs the android app and opens it
9. User enters his xyz@company.com username as login hint in the app and presses next.
10. This opens ChromeCustomTabs browser pointing to FusionAuth authorization endpoint. Login hint is passed into this endpoint. ChromeCustomTabs still have session of abc user, because he did not logout when uninstalling the app.
11. User abc is logged in to the app, instead of user xyz.

- There is no way to clear cookies in ChromeCustomTabs (or SafariViewController for iOS) to workaround this case.
- FusionAuth does not seem to support 'prompt=login' that could fix this and require user to re-authenticate.

### Expected behavior
LoginHint should not automatically log in the wrong user into app, or there should be a way to force user to re-authenticate.

**Comment by robotdan** [comment] 2022-12-09 15:27
In OIDC I think this would be `prompt=login`
https://openid.net/specs/openid-connect-core-1_0.html#AuthRequest

**Comment by mooreds** [comment] 2022-12-09 15:29
@JonasPrapuolenis Hmmm.

Looks like you can use a `WebView` instead of a `ChromeCustomTab` and get more control over deleting the cookies: https://stackoverflow.com/questions/50445469/how-to-clear-cookies-in-chromecustomtabs

**Comment by JonasPrapuolenis** [comment] 2022-12-09 15:32
@robotdan is prompt=login currently supported? I tried it but did not seem to work.

@mooreds webview is not the recommended approach. See:
https://www.oauth.com/oauth2-servers/oauth-native-apps/use-system-browser/
https://support.google.com/faqs/answer/12284343?hl=en-AU

**Comment by mooreds** [comment] 2022-12-09 15:50
@JonasPrapuolenis fair point. 

`prompt=login` is not currently supported.

**Comment by robotdan** [comment] 2023-04-12 09:13
This seems to be working as designed. Closing. 

Opened a feature request to support `prompt=login`.

- https://github.com/FusionAuth/fusionauth-issues/issues/2208

**Closed** 2023-04-12 09:13 UTC
Labels: working as designed
