### ISSUE TITLE
Throwing Exception within Lambda Exits Login Flow

### ISSUE THREAD

**Issue by matt1hathcock** [FusionAuth/fusionauth-issues#1707] opened 2022-04-28 22:52 UTC
### Description
I configured the Google IdP with a working client id and secret to succesfully login users via Google.

User login was sucessful.

I then added some javascript to the Google Reconcile Lambda to throw an exception.

The lambda was then added to the Google IdP.

Upon attempting to login again the login failed.

The error message is shown as pictured.

<img width="470" alt="Screen Shot 2022-04-28 at 4 49 07 PM" src="https://user-images.githubusercontent.com/44510264/165860423-086fa29b-7c91-4df4-869e-f7d3afc65718.png">

### Related
- https://github.com/FusionAuth/fusionauth-issues/issues/1725

**Comment by mooreds** [comment] 2022-04-29 15:15
This is either a doc bug (we should document this behavior) or a product bug (we should catch thrown exceptions from a lambda). I vote for the latter, as I think it is more consistent to have only webhooks be able to intervene in the login flow, but either option works.

**Comment by robotdan** [comment] 2022-04-29 19:22
What was the expected behavior in this case? Currently if you throw an exception in the lambda, it will fail the login request, this is by design.

**Comment by mooreds** [comment] 2022-04-29 19:27
Excellent, then we should document this. 

The alternative is that we don't allow thrown exceptions to stop the login process. But if this is working as designed, I'll just document it.

**Comment by robotdan** [comment] 2022-04-29 19:31
I would consider this a dev time issue. I would hesitate to mask the issue because it may affect data integrity depending upon what is happening in the lambda, and what the user of FusionAuth expects the user to look like after a login is complete.

**Comment by matt1hathcock** [comment] 2022-08-23 22:54
Need to add some notes here as this was done with a reconcile lambda.

@robotdan This behavior is not the same in the JWT populate lambda as the user is still authenticated and redirected to the application

**Comment by mooreds** [comment] 2024-07-12 22:25
Per https://github.com/FusionAuth/fusionauth-site/pull/1670 we should not document this behavior for now.

**Comment by robotdan** [comment] 2024-12-10 21:25
Closing per https://github.com/FusionAuth/fusionauth-issues/issues/1707#issuecomment-2226436005

**Closed by robotdan** 2024-12-10 21:25 UTC
Labels: documentation
