### ISSUE TITLE
Cannot Update User's Email or Username with patchUser()

### ISSUE THREAD

**Issue by pmolaro** [FusionAuth/fusionauth-issues#1472] opened 2021-11-03 14:09 UTC
### Description
I'm having an issue updating a user's email and username (we use email as the username) with the fusionAuthClient.patchUser() method. I'm hoping its developer error, but I also saw an older post where this happened in previous versions (https://github.com/FusionAuth/fusionauth-issues/issues/1333)

General setup is my website calls my NestJS api that then calls FusionAuth using the typescript client. We already have several calls setup with this workflow and it works great. 

For Update user, the user is logged in (using JWT authentication passed in the header via HTTP-Only cookies), and submits an update user web form. From the form submission, the following user info is passed (note this is an example, we pass only updated fields):
```
{
	"username":"joeuser@somedomain.net",
	"email": "joeuser@somedomain.net",
	"firstName": "Joe",
	"lastName": "User",
	"fullName": "Joe Foo User",
	"internalcall": true
}
```

In this example I am just updating the fullName value from "Joe User" to "Joe Foo User".

In my NestJS API, the JWT is verified, then a service function builds the request model for the call to the FusionAuth Typescript client, using the user info from above:
```
const updateRequest: UserRequest = {
	applicationId: this._faAppId,
	sendSetPasswordEmail: false,
	skipVerification: true,
	user: {
		"username":"joeuser@somedomain.net",
		"email": "joeuser@somedomain.net",
		"firstName": "Joe",
		"lastName": "User",
		"fullName": "Joe Foo User",
		"internalcall": true
	},
}

return await this.fusionAuthClient.patchUser( currentUser.faUserId, updateRequest );
```

Note the FusionAuth App ID and current user's FusionAuth User Id are already stored as variables, and I have verified these are correct.

With a simple update, properties are updated and I get a 200 response with an updated user model:
```
ClientResponse {
  statusCode: 200,
  response: {
    user: {
      active: true,
      connectorId: 'e9999999-a53a-9999-9999-1c96f36dda72',
      email: 'joeuser@somedomain.net',
      firstName: 'Joe',
      fullName: 'Joe Foo User',
      id: '4e1796f3-1f43-4105-bfb3-25d8c721baba',
      imageUrl: 'https://testimages.signupgenius.com/memberImages/profile/73305/profilepic_128.png',
      insertInstant: 9999999999999,
      lastLoginInstant: 9999999999999,
      lastName: 'User',
      lastUpdateInstant: 9999999999999,
      passwordChangeRequired: false,
      passwordLastUpdateInstant: 9999999999999,
      registrations: [Array],
      tenantId: '99fcf999-ef9e-99b9-9d9e-99aa9c99fb99',
      twoFactor: {},
      uniqueUsername: 'joeuser@somedomain.net',
      username: 'joeuser@somedomain.net',
      usernameStatus: 'ACTIVE',
      verified: true
    }
  }
}
```
I can also verify in the FusionAuth admin UI that the user has been changed. 

However, if I perfrom the same steps above and submit a different email in the email and/or the username field, I still get a successful response with a user model (exactly like the one above), however the values aren't changed. The FusionAuth admin UI also shows no changes. I believe the code isn't finding the user, despite the fact that I'm passing in the user id.

We're using **version 1.30.2** of the FusionAuth software.  Note I've also tried this with the PUT version of this command and have the same results. We choose to use the PATCH version bc there are several places in our site that update only a few properties so PATCH works better for our use case.

Also to verify, When I take this action, IF I change the email (which also changes the username), I am then following up and calling the issueJwt() to get an updated JWT and sending it back as a new http-only cookie. I assume thats the right way to handle a user update like this (once it works), yes?

**Comment by mooreds** [comment] 2021-11-05 15:39
I am unable to replicate this bug. Here's my curl script:

```
API_KEY=...

curl -XPATCH -H "content-type: application/json" https://sandbox.fusionauth.io/api/user/2016c3ed-0063-45ed-9944-c911d4c38ae1  -H 'Authorization: '$API_KEY -d '{"user": {"username": "testdan2" }}'
```

Both username and email address can be changed by the patch method.

I'm going to close this because it seems like a support issue (and your last question is definitely a support question :) ). 

If you have a paid support contract, please open a ticket here https://account.fusionauth.io/account/support/  Otherwise, please ask a question in the forum: https://fusionauth.io/community/forum/

If you do more research and later find reproduction steps, preferably with curl (so that it is easy to reproduce), please feel free to re-open this bug.

**Closed** 2021-11-05 15:39 UTC
Labels: already fixed, moved to forum
