### ISSUE TITLE
500 error when using webauthn to authentication with Edge

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-issues#1928] opened 2022-10-20 20:10 UTC
### Affects versions
List the version you are running, and any other versions you have attempted a recreated. 

### Steps to reproduce

* able to register, have to use pin
* authenticate, can't use fingerprint because it is denied, then use pin, then get 500 error.

From logs:

```
2022-10-20 08:01:23.997 PM ERROR io.fusionauth.app.primeframework.error.ExceptionExceptionHandler - An unhandled exception was thrown
java.lang.NullPointerException: null
	at java.base/java.util.Objects.requireNonNull(Objects.java:208)
	at io.fusionauth.webauthn.rsa.RSAVerifier.<init>(RSAVerifier.java:31)
	at io.fusionauth.webauthn.rsa.RSAVerifier.newVerifier(RSAVerifier.java:52)
	at io.fusionauth.api.service.webauthn.DefaultWebAuthnProviderService.buildVerifier(DefaultWebAuthnProviderService.java:729)
	at io.fusionauth.api.service.webauthn.DefaultWebAuthnProviderService.completeAssertion(DefaultWebAuthnProviderService.java:204)
	at io.fusionauth.api.service.authentication.DefaultAuthenticationService.authenticateWebauthn(DefaultAuthenticationService.java:368)
	at org.mybatis.guice.transactional.TransactionalMethodInterceptor.invoke(TransactionalMethodInterceptor.java:100)
	at org.mybatis.guice.transactional.TransactionalMethodInterceptor.invoke(TransactionalMethodInterceptor.java:100)
	at org.mybatis.guice.transactional.TransactionalMethodInterceptor.invoke(Transac
```

### Platform

using edge ( Version 106.0.1370.47 (Official build) (64-bit) ) on windows 10 home.

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

### Additional context

Using EAP 20221020 server.

**Comment by spwitt** [comment] 2022-10-20 20:24
Have you tried on any other browsers? It works on Edge for macOS.

Trying to pin down whether the issue is with the OS, browser, or the combination.

**Comment by mooreds** [comment] 2022-10-20 20:48
Just tried to do it with windows chrome and got another error. registration failed and there was an error in the browser console: 

```
Uncaught (in promise) DOMException: The user attempted to register an authenticator that contains one of the credentials already registered with the relying party.
```

This may be a separate issue. I will delete edge credential and try again.

**Comment by mooreds** [comment] 2022-10-20 20:51
Same error message on chrome.

```
java.lang.NullPointerException: null
	at java.base/java.util.Objects.requireNonNull(Objects.java:208)
	at io.fusionauth.webauthn.rsa.RSAVerifier.<init>(RSAVerifier.java:31)
	at io.fusionauth.webauthn.rsa.RSAVerifier.newVerifier(RSAVerifier.java:52)
	at io.fusionauth.api.service.webauthn.DefaultWebAuthnProviderService.buildVerifier(DefaultWebAuthnProviderService.java:729)
	at io.fusionauth.api.service.webauthn.DefaultWebAuthnProviderService.completeAssertion(DefaultWebAuthnProviderService.java:204)
	at io.fusionauth.api.service.authentication.DefaultAuthenticationService.authenticateWebauthn(DefaultAuthenticationService.java:368)
	at org.mybatis.guice.transactional.TransactionalMethodInterceptor.invoke(TransactionalMethodInterceptor.java:100)
```

**Comment by spwitt** [comment] 2022-10-20 21:45
This helped to uncover an issue with registration. We shouldn't have allowed you to complete the registration. Once I've got that resolved, I may need to work with you to debug this by proxying traffic to my dev instance.

It's interesting that Windows is using SHA256withRSA as the signing algorithm. That's the bottom of the list in terms of our preferences, meaning that Windows isn't supporting _any_ of the other, more secure algorithms.

**Comment by spwitt** [comment] 2022-10-21 16:17
I was able to debug this on my dev instance with a proxy. For both Dan's laptop and a borrowed Windows laptop, the exception parsing the public key was:
```
java.security.InvalidKeyException: exponent is larger than modulus
```

Considering that the same machines work on the webauthn.io demo site, this is almost certainly an issue with how we are parsing RSA keys.

**Comment by spwitt** [comment] 2022-10-21 17:59
Resolved in EA build.

Modulus and exponent for the RSA key are encoded as byte arrays. The values were being parsed as signed bigint, but they should have been treated as unsigned values.

**Closed by spwitt** 2022-10-21 17:59 UTC
Labels: bug, EAP
