### ISSUE TITLE
Add a PATCH user's data

### ISSUE THREAD

**Issue by ericher4worximity** [FusionAuth/fusionauth-issues#230] opened 2019-07-22 19:35 UTC
### Problem
Currently, there is only one method to update a user: `PUT`, which represents a full overlay of a user. Our system allows our end users, via our own api, to update a limited set of information about a user (first name, last name, birthdate). To achieve our goal, we are forced to perform a `GET`, merge the input and then `PUT` it. There is sensitive data we have to store inside the user `data` section. The `GET` then `PUT` forces us to "re-write" a lot of information that must not change.

### Solution
To reduce risk, could you provide a `PATCH` operation to your User REST api? We would be sure to not accidentally crush that sensitive information. We would provide only the information that changed, nothing else.

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by robotdan** [comment] 2019-07-22 19:37
Thanks for the request @ericher4worximity - I completely agree, this is on the road map for sure! 

Duplicate of https://github.com/FusionAuth/fusionauth-issues/issues/121

**Closed** 2019-07-22 19:37 UTC
Labels: duplicate

**Comment by ericher4worximity** [comment] 2019-07-22 19:41
Thanks!
