### ISSUE TITLE
Sign in with Apple failing on some devices

### ISSUE THREAD

**Issue by thekoding** [FusionAuth/fusionauth-issues#1134] opened 2021-03-04 10:46 UTC
### Description 
Sign in with Apple works fine for some devices, but for others I get an error - "invalid_grant" with the error code 400. I could not reproduce the error myself, but our app was rejected on the App Store because of it.

### Affects versions
1.22.0

### Expected behavior
Sign in with Apple should authenticate the user.

### Related
- https://github.com/FusionAuth/fusionauth-issues/issues/778
- https://github.com/FusionAuth/fusionauth-issues/issues/1134
- https://github.com/FusionAuth/fusionauth-issues/issues/1389

### Platform
(Please complete the following information)
 - Device: iPad
 - OS: iOS 14.4
 - Browser + version Safari with a Symfony backend performing the actual communication with FusionAuth
 - Database PostgreSQL

**Comment by mooreds** [comment] 2021-03-04 14:41
Hi @thekoding ,

Thanks for the issue report.

Can you provide any more details? As you can imagine, we'd want to fix this but also need as much detail as possible to reproduce this.

Is the platform you listed a reliable repro setup? 

Do you have any debug logs from the FusionAuth side with a failing 'sign in with apple' flow?

**Comment by robotdan** [comment] 2021-03-04 20:05
Possibly related to https://github.com/FusionAuth/fusionauth-issues/issues/885 or https://github.com/FusionAuth/fusionauth-issues/issues/778 ?

**Comment by robotdan** [comment] 2023-01-30 15:45
Closing as duplicate of 778

**Closed by robotdan** 2023-01-30 15:45 UTC
Labels: needs more info
