### ISSUE TITLE
OAuth Client Credentials Flow

### ISSUE THREAD

**Issue by joaonice** [FusionAuth/fusionauth-issues#155] opened 2019-05-02 11:59 UTC
### Problem
I'm using fusion auth to handle the user's registration and authentication. After a successful login, the JWT is returned and can be used to call the backend authenticated endpoints on my frontend application. 
The problem is, I want to give my users and SDK so they can use it on their backend to call some of my backend's endpoints.

### Solution
If each user had a client id and a client secret, they could use that to retrieve a token that they could use to call the authenticated endpoints. (OAuth Client Credentials Flow)

### Alternatives/workarounds
Right now the users could use the login endpoints to get the JWT and then use it to call the authenticated endpoints. 

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

### Related
https://github.com/FusionAuth/fusionauth-issues/issues/881
https://github.com/FusionAuth/fusionauth-issues/issues/1125

### Notes
Great product! 🍻

**Comment by robotdan** [comment] 2019-05-02 15:48
Thanks for the request @joaonice this is on the roadmap for sure. Could you use the Password grant in the same fashion since each client credential pair would belongs to a user? 

So they would each just have an email and password, or a username and password instead of a client id and client secret? 

Or do you have use cases where the client credential pair does not belong to a user and instead to an SDK or a device?

**Comment by joaonice** [comment] 2019-05-02 15:59
Hi @robotdan, thank you for the quick response.

Exactly, I have some use cases where the client credential pair does not belong to a user.

I'll keep watching the future versions!

Thanks!

**Comment by robotdan** [comment] 2019-05-02 17:53
Great, thanks for the feedback. This will likely make it into the upcoming release or two. We have been brainstorming on this and other features to build to better support IoT use cases. 

So feel free to open features, or provide other feedback if you identify other features that would make your life easier - especially in context of IoT. 

Thanks!

**Comment by solarmosaic-kflorence** [comment] 2020-01-23 22:25
@robotdan this is a missing requirement for us to integrate with FusionAuth, just FYI. We also have a use case that requires us to provide client credentials authentication (in this case, it is for backend API integrations with our partners) where we cannot use password grants.

**Comment by solarmosaic-kflorence** [comment] 2020-02-04 01:14
@robotdan any idea when this will be done?

**Comment by robotdan** [comment] 2020-02-04 04:44
No ETA, we have several large projects under way that are taking precedence. 

Features can be expedited with professional services if you have an immediate business requirement.

**Comment by trevorr** [comment] 2020-05-08 21:10
Ideally, a given client/user would be able to have more than one secret (temporarily), so that credentials can be rotated without service interruption across multiple client instances. For example, if rotating from secret A to secret B for a given client, secret A would need to remain valid until all client instances have been updated with secret B (which may take hours). AWS API keys are an example of this kind of feature.

**Comment by janakapdj** [comment] 2020-05-13 07:28
> No ETA, we have several large projects under way that are taking precedence.
> 
> Features can be expedited with professional services if you have an immediate business requirement.
Hi @robotdan we also looking the same feature for business requirement

**Comment by voidmain** [comment] 2020-05-15 14:46
@janakapdj - if you are interested in professional services, you can use the contact form on our website and I'll get back to you to discuss options. Here's the contact form: https://fusionauth.io/contact

**Comment by mooreds** [comment] 2020-06-26 22:50
When this is implemented, we should update this guide: https://github.com/FusionAuth/fusionauth-site/pull/96

**Comment by EronWright** [comment] 2020-07-08 18:15
An interesting tidbit in support of this feature request.  Auth0 recently implemented a cap of 100 OAuth2 clients for its non-Enterprise plans, making it less attractive for machine-to-machine flows ([reference](https://auth0.com/docs/policies/entity-limits)).  This feature would make FusionAuth more attractive as an alternative.

**Comment by robotdan** [comment] 2020-07-08 19:39
Thanks @EronWright that is good to know. We have a few larger features in progress at the moment..  but this is something we want to get to. 

To be transparent, this feature may be delivered with a few other features that we are designing for IoT and a general asset model. If that is the case it would require a paid edition of FusionAuth. However, we do offer a  developer edition which includes paid features w/out support and it starts at $125 per month. 

It is also possible that we would de-couple the client credentials feature from the other IoT, asset based features we will be delivering and make this feature available in the base community edition. 

Any feedback is welcome, would you be willing to purchase an edition for this feature?

**Comment by EronWright** [comment] 2020-07-10 17:35
Thanks @robotdan for the insight.  It seems reasonable to me that M2M at scale would be a paid feature, e.g. at "Premium" level. I'd expect to be able to create thousands of OAuth2 clients and to issue a great many access tokens, in support of my scenario which is to authenticate API clients of a SaaS product.

**Comment by doug-shontz** [comment] 2020-08-11 18:08
My company is also looking at FusionAuth as an alternative to Auth0 and Okta (which both have pricing slightly outside our reach).  We are looking at implementing API's for a SaaS product as well.  I would be more than happy (and would expect) to pay for a true M2M solution.

**Comment by robotdan** [comment] 2020-08-11 18:15
Thanks for the feedback @doug-shontz. Feel free to use the contact form on the main fusionauth.io site if you have any questions on pricing and delivery of this feature.

**Comment by voidmain** [comment] 2020-09-18 23:10
I've created an feature request to track the "Entity Management" idea. This could be a solution for this feature request as well. The issue is #881. If everyone that is following this feature request can please review #881 and see if it will work for your needs, that would be great. Also, please provide additional feedback on #881 if you feel we need additional capabilities to cover the client credentials grant.

**Comment by autom8ter** [comment] 2020-10-07 15:43
@robotdan this is also a missing requirement for us... We also have a use case that requires us to provide scoped client credentials auth for backend API integrations across various tenants.

**Comment by voidmain** [comment] 2020-10-07 17:23
@autom8ter - have you reviewed our design in issue #881? That design should hopefully cover all of your use cases because you can create multiple Entities for each backend and then grant them permissions to each other. We likely will also make Entities scoped to a Tenant. 

If you have any feedback, please post it on that issue.

**Comment by Mistic92** [comment] 2021-02-25 20:13
I see that there are 56 upvotes for this feature. Do you have plan to implement it?

**Comment by mooreds** [comment] 2021-02-25 20:43
Hi @Mistic92 

We do plan to implement it. I believe the current plan is to implement it under #881. In the interests of full transparency, I'm not sure whether this will be available in the community edition. I think the plan right now is to make it a feature for our [paid editions](https://fusionauth.io/pricing/editions/), which start at $125/month.

I'm unsure of the timeline right now, but believe it is going to be delivered in the first half of 2021.

I hope this answers your question; please let me know if you have any others.

**Comment by voidmain** [comment] 2021-02-25 20:55
This will be available by the end of March.

**Comment by mooreds** [comment] 2021-05-06 17:08
This was delivered in 1.26. 

Here is the documentation:

https://fusionauth.io/docs/v1/tech/oauth/#configure-entities

https://fusionauth.io/docs/v1/tech/oauth/#example-client-credentials-grant

Closing.

**Closed by mooreds** 2021-05-06 17:08 UTC
Labels: feature, paid-feature

**Comment by matthewhartstonge** [comment] 2021-05-06 21:53
Hey @mooreds just wanted to mention that the "learn more" Entities link is dead/doesn't exist under the core concepts documentation.

[https://fusionauth.io/docs/v1/tech/core-concepts/entities/](https://fusionauth.io/docs/v1/tech/core-concepts/entities/)

![image](https://user-images.githubusercontent.com/6119549/117370066-f4bcf700-af19-11eb-916e-effbc455f34e.png)

**Comment by mooreds** [comment] 2021-05-07 02:04
Thanks @matthewhartstonge , will get that fixed.
