### ISSUE TITLE
Registrating a new User does not send verification email 

### ISSUE THREAD

**Issue by Gashunkification** [FusionAuth/fusionauth-issues#1592] opened 2022-02-08 16:23 UTC
### Description

First of all some background
- I am using the official go client 
- I am using the latest fusionauth docker image `image: fusionauth/fusionauth-app:latest` in a docker-compose.yaml

Since updating from version 1.22.0 to 1.32.1 I no longer receive any verification emails for newly registered users. If I manually downgrade to version 1.22.0 it seems to be working just fine. When checking via the web interface I can see the user has been correctly created and I can then manually resend a verification email which then gets sent out correctly.

I am not sure this is a bug or some setting that changed in between versions. I tried looking for something in the release notes but wasn't able to find anything that seemed related, hence the issue here.
Also I hope this is the right place to post this.

Any help on the matter would be greatly appreciated, thanks in advance!

**Comment by mooreds** [comment] 2022-02-08 23:55
@Gashunkification thanks for checking out the release notes. I took a look and don't see anything that would cause that.

If you can share how you register users (what the JSON looks like) that may be helpful in narrowing down if this is a regression or a new setting. 

It would also be helpful for you to provide your tenant config JSON and your application JSON.

I also know that we have added some documentation around verification that may be worth reviewing: https://fusionauth.io/docs/v1/tech/tutorials/gating/gate-accounts-until-user-email-verified#troubleshooting-email-and-registration-verification

**Comment by jobannon** [comment] 2024-07-29 20:45
Closing as more details needed.  Registration verification functions in the lastest version.  Can reopen if a bug is identified.

**Closed by jobannon** 2024-07-29 20:45 UTC
Labels: needs more info
