### ISSUE TITLE
FusionAuth Containers require internet access on init

### ISSUE THREAD

**Issue by PGQW** [FusionAuth/fusionauth-issues#442] opened 2020-01-16 21:31 UTC
### Description 
Deploying FA 1.7.2 or 1.13.2 will not work on kubernetes clusters that do not have internet access in the form of a NAT or gateway.  We discovered this when trying to deploy FA to air-gapped Kubernetes clusters.

### Steps to reproduce
1. Deploy the FusionAuth helm deployment to an air-gapped Kubernetes cluster.
2. Allow the DB and search containers to come up.
3. Observe the liveness check fail on the FA-app pod.
4. Check the logs.
5. Observer the pod fall into a CrashLoopBackoff.

### Expected behavior
Deployment should come up smoothly without a Cloud NAT in place.

### Logs

FA 1.7.2 not coming up.

[notworkingFAnonat172.txt](https://github.com/FusionAuth/fusionauth-issues/files/4073878/notworkingFAnonat172.txt)

FA  1.7.2 starting with NAT.
[workingFAwithnat.txt](https://github.com/FusionAuth/fusionauth-issues/files/4073880/workingFAwithnat.txt)

### Platform
Kubernetes 1.15 and 1.14 on GCloud, and on AWS.
 - OS: Nodes run ubuntu 18.04
 - Browser + version [e.g. chrome, safari plus a version]

### Additional context
Concern that FA may be pulling down something malicious, or just JRE 1.8 unnecessarily.

**Comment by robotdan** [comment] 2020-01-16 21:50
From a offline thread, it sounds like we are downloading Java on startup even when using the docker container which should have it provided already. 

Because we lay down our JRE in the Docker image we should not try to download it again on Tomcat startup.

**Comment by robotdan** [comment] 2020-01-22 21:48
Do you know off hand what is returned on the k8s host node when you run `uname -s` ?

**Comment by PGQW** [comment] 2020-01-23 22:22
Not off hand, I'll see if I can run that command on a master node.
We're also running your container, albeit one that we copied into our own docker repo.

**Comment by robotdan** [comment] 2020-01-24 22:21
@tyduptyler13 can you take a look at this one? 

We may have to try to recreate using docker compose, k8s, etc and see if there are any nuances to these setups that would cause our checks to be failing and subsequently downloading java again.

**Comment by tyduptyler13** [comment] 2020-01-28 22:22
I can't reproduce the issue with local testing. I think we would need more details about that specific environment.

**Comment by robotdan** [comment] 2020-05-08 15:55
Going to close this one out. We have been unable to create. 

However, we have made a few changes to the way we handle downloading Java to eliminate this possibility. 

As with all of our docker images, Java is built into the image. Beginning in version 1.16.0, the Docker image will set an environment variable that instructs the rest of our startup to always skip downloading Java.

**Closed by robotdan** 2020-05-08 15:55 UTC
Labels: bug, needs more info, works on my machine
