### ISSUE TITLE
Error Handling Improvements

### ISSUE THREAD

**Issue by jobannon** [FusionAuth/fusionauth-issues#1952] opened 2022-11-04 00:20 UTC
### Description 
If we have:

- 2FA enabled 
- w/out SSO
- We should not be pushing up an error message to the user interface as such during a forgot password workflow.

### Affects versions
- DEV 

### Steps to reproduce
- 2FA enabled 
- w/out SSO
- We should not be pushing up an error message to the user interface when doing a forgot password workflow via API

### Screenshots
<img width="1182" alt="image" src="https://user-images.githubusercontent.com/16090626/199859027-caedf1f7-d936-410c-b182-6fdb161083ea.png">

### Platform
(Please complete the following information)
 - Device: [e.g. Desktop, iPhone X, Pixel 3, etc]
 - OS: [e.g. iOS, macOS, Windows ME]
 - Browser + version [e.g. chrome, safari plus a version]
 - Database [MySQL | PostgresSQL] & and version

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

**Comment by andrewpai** [comment] 2024-12-10 01:49
It looks like this was fixed with interim changes, cannot reproduce now.

**Closed by andrewpai** 2024-12-10 01:49 UTC
