### ISSUE TITLE
Secrets for lambdas

### ISSUE THREAD

**Issue by Tory-JohnConnor** [FusionAuth/fusionauth-issues#2560] opened 2023-11-23 21:47 UTC
### Problem
Trying to supply sensitive values to a lambda to use in request to further populate the jwt. 

### Solution
I would expect a secrets system that injects the values somehow into the env of the lambda

### Alternatives/workarounds
Using a third party service but even that has sensitive values. 

### Additional context
Auth0 has this and was nice, but even had it's own issues. so maybe an integration with something like aws secrets manager or another company? 

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by mooreds** [comment] 2023-11-24 15:31
@NilShortcut is this issue a duplicate of https://github.com/FusionAuth/fusionauth-issues/issues/1629 ?

**Closed as completed** 2023-11-28 05:12 UTC
