### ISSUE TITLE
docs: Tenant ID is required when deleting an entity, docs say optional.

### ISSUE THREAD

**Issue by matthewhartstonge** [FusionAuth/fusionauth-issues#1712] opened 2022-05-03 23:41 UTC
### Description
I hit this using the Terraform provider trying to delete an entity where the API reports a Tenant ID is _required_ but the [docs mention the Tenant ID is optional](https://fusionauth.io/docs/v1/tech/apis/entity-management/entities#delete-an-entity).

```
"fusionauth_entity.service[\"people\"] (destroy)" error: unexpected status code: 400(Bad Request) Errors: A Tenant Id is required to complete this request. To complete this request, you may assign a Tenant to your API key, or add the X-FusionAuth-TenantId HTTP request header with the Tenant Id.
```

I'll be patching the fusionauth provider via https://github.com/gpsinsight/terraform-provider-fusionauth/issues/118

Documentation probably needs an update 👍 

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

**Comment by mooreds** [comment] 2022-05-04 12:36
Hmmm. Feels like a bug to me, not a doc bug. Since you are providing a UUID and entities are uniquely scoped to a tenant, we should be able to look up the tenant in the same way we do when deleting a user.

**Comment by robotdan** [comment] 2022-05-09 19:12
This looks like it is working as designed according to the code. Once more than a single tenant exists, the `tenantId` will be required. 

In general we always want the `tenantId`, many APIs will resolve the `tenantId` as long as we have another unique Id that allows us to do so. This behavior is primarily for backwards compatibility for pre-tenant APIs.

**Comment by mooreds** [comment] 2022-05-11 22:47
Closing as this doc was updated. thanks again @matthewhartstonge !

**Closed by mooreds** 2022-05-11 22:47 UTC
Labels: documentation
