### ISSUE TITLE
Apple Signin - Status code [400] Error response is { "error" : "invalid_client" }

### ISSUE THREAD

**Issue by satsangswami** [FusionAuth/fusionauth-issues#885] opened 2020-09-22 20:48 UTC
With Apple Signin Status code [400] Error response is { "error" : "invalid_client" }

### Description
We are implementing , Apple as IDP, We have configured everything properly. AppID, ServiceID and Key
1. It does go to Apple Signin Page
2. It verifies User/password
3. Takes the Consent from User about information usage
4. continue to our web application
5. We get following Error
```
A request to the Apple Token API has failed. Unable to complete this login request.
```
In event log we get 
```Status code [400] Error response is { "error" : "invalid_client" }```

Tried multiple things but no gain.

**Comment by satsangswami** [comment] 2020-09-22 20:56
noticed on apple forum but there can be issue with content-type header, but don't know where to configure.

> https://developer.apple.com/forums/thread/122648
> Adding what helped me solve a similar problem:
> 
> I had the same issue, checked every credential, made sure I'm using the `bundleId` from ios to verify and create client secret. Everything looked correct, but still, the request failed.
> 
> 
> 
> Finally noticed that the request I was making trough a library sent is as `Content-Type: application/json`. Changed it to the correct `Content-Type: application/x-www-form-urlencoded` and everything was good. I'd call it a bug as Apple should fail the request with "415 Unsupported Media Type" status instead "400 Bad Request".

Please help us find the solution

**Comment by robotdan** [comment] 2020-10-29 19:22
I would guess this is because your Apple configuration stuff is not correct. This would cause us not to be able to correctly build the client secret signature to Apple.

**Comment by robotdan** [comment] 2020-12-01 16:55
@satsangswami can we close this one out, or are you still experiencing this error?

**Comment by trevorr** [comment] 2021-05-02 00:24
I'm getting the same error: https://fusionauth.io/community/forum/topic/752/not-able-to-login-with-apple-id/3

There's not much to configure, so I'm not sure what else to try. Their API error message couldn't be less helpful.

**Comment by robotdan** [comment] 2021-05-02 00:41
Can you enable debug on the oauth config and the Apple config and then add the debug event logs here? Perhaps that will shed some light on the root cause.

**Comment by trevorr** [comment] 2021-05-02 00:48
Where are those settings? I have debug enabled on the Apple IdP. I haven't found any other debug settings.

**Comment by robotdan** [comment] 2021-05-02 01:19
The oauth debug was added in recent version, if it is available you’ll find it in Applications > Edit > Oauth. 

This may not help much of Apple is the one returning the error.

**Comment by trevorr** [comment] 2021-05-02 01:43
Ah, yes, that is new to me. I am running 1.26.1 though, so I enabled it. I just ended up with the same looking logs from the forum though.

**Comment by robotdan** [comment] 2021-05-02 02:11
@trevorr one option if you're open to it - is to send me your apple config and I can try to recreate. 

If you want to do this, shoot me a note daniel - at -....    with any necessary config, and add `https://local.fusionauth.io/oauth2/callback` as a registered redirect in your Apple dev account (this is where I'll be testing the redirect).

**Comment by trevorr** [comment] 2021-05-02 05:26
I finally figured out the issue: The private key identifier wasn't correct. After re-creating the private key with the Apple-provided ID, I get a bit farther. I have it working with one Apple ID but not with another:

```
5/2/2021 05:05:52 AM GMT Call the configured Token endpoint [https://appleid.apple.com/auth/token] with the the following [client_secret] value:
ey...
5/2/2021 05:05:52 AM GMT Endpoint returned status code [200]
5/2/2021 05:05:52 AM GMT Access Token Response:
{
  "access_token" : "...",
  "token_type" : "Bearer",
  "expires_in" : 3600,
  "refresh_token" : "...",
  "id_token" : "ey..."
}
5/2/2021 05:05:52 AM GMT Build a new user object from the claims collected from the [id_token] and the Token endpoint response.
5/2/2021 05:05:52 AM GMT The identity provider was unable to reconcile the email address. An email address is required to complete this request.
```

Anyway, this particular issue is resolved for me. Thanks for the Saturday evening help @robotdan!

**Comment by trevorr** [comment] 2021-05-02 05:54
BTW, I got both Apple IDs working. For the one that wasn't working, I revoked the app and gave permission again and it worked. 🤷

**Comment by trevorr** [comment] 2021-05-02 06:27
@robotdan wanted me to suggest here that the Apple provider documentation emphasize the key identifier issue. I'd recommend also mentioning that getting it wrong leads to an `invalid_client` error, so it will come up in searches. There are all sorts of implementation-related causes of this error discussed on the web, but this may be the only way to hit it with FusionAuth.

**Comment by robotdan** [comment] 2021-05-02 20:01
Thanks for the update @trevorr. 

@mooreds it sounds like we should add some emphasize the the importance of setting the correct key identifier when importing the Apple private key to the value Apple provides. 

If folks are used to importing keys into key master, they will likely be used to letting the `kid` be defaulted by FusionAuth and in this case it will cause a problem because Apple will expect the `client_secret` we generate (which is a JWT) to have a specific `kid` in the JWT header. 

We can also mention that if you get a failure from Apple of `invalid_client`, the first thing the user can do is to verify the private key has been imported correctly with the `kid` provided by Apple. 

Can you or @jobannon update this Apple integration guide to make an additional note about this particular part of the configuration. 

Thanks!

**Comment by robotdan** [comment] 2021-05-02 20:02
@satsangswami can you also confirm that the private key you imported into FusionAuth is using the correct `kid` and if not, re-import the key and then attempt to recreate the symptom again.

**Comment by satsangswami** [comment] 2021-05-03 03:26
Jay Swaminarayan. I would be able to check in a week or two as we are under
different priority at the moment concerning COVID volunteer services in
India

**Comment by robotdan** [comment] 2023-03-14 19:34
Closing due to inactivity. If anyone is still able to recreate, please re-open.

**Closed by robotdan** 2023-03-14 19:34 UTC
