### ISSUE TITLE
Event Log Details doesn't fit on page with long event lines

### ISSUE THREAD

**Issue by bhalsey** [FusionAuth/fusionauth-issues#2073] opened 2023-01-23 19:38 UTC
### Description 
When an event log line is too long, the Event Log Details modal is configured wider than the viewable page.  The main page doesn't scroll horizontally, so the modal isn't entirely viewable.  The long lines were from errors when Oauth Debug is enabled.

### Affects versions
1.43

### Steps to reproduce
1. Turn on Oauth Debug for an application
2. Misconfigure something.  E.g., the redirect url
3. Hit an oauth endpoint
4. View the System -> Event Log.  Click on an entry

### Expected behavior
Modal would not be too wide.

### Screenshots
<img width="2100" alt="Screenshot 2023-01-23 at 11 27 26" src="https://user-images.githubusercontent.com/211656/214133516-8bd91402-0bc6-4330-b229-22e4100d94ea.png">

### Platform
(Please complete the following information)
 - Device: Desktop
 - OS: macOS
 - Browser + version: Brave

**Comment by bhalsey** [comment] 2023-01-23 20:05
On the second attempt to view this event log item, the modal displayed properly.  This issue appears difficult to reproduce.

**Comment by robotdan** [comment] 2023-01-23 22:46
The code mirror editor has options for line wraps, and we can also ensure the CSS on the dialog is correct. It could be a timing issue because the DOM has likely already determined the width of the element before we initialize the code mirror editor with the content.

**Comment by andrewpai** [comment] 2024-12-11 13:03
Closing as I can't reproduce this either.

**Closed by andrewpai** 2024-12-11 13:03 UTC
Labels: ux
