### ISSUE TITLE
Using anonymous linking strategy causes exception when user logs in the second time

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-issues#1418] opened 2021-09-28 18:18 UTC
### Description 

If I set up an OIDC connection to use the anonymous linking strategy and login two times, I get an exception in my system logs the second time.

### Affects versions
1.30.1

### Steps to reproduce

* Set up OIDC connection (I used FusionAuth running on a different port. If you do this, make sure to set the application's callback url to be https://local.fusionauth.io/oauth2/callback )
* Create an application, allow the auth code grant and set the redirect uri to https://fusionauth.io
* Configure the OIDC identity provider to enabled for this application. Also to create a registration. And finally to use an anonymous link linking strategy.
* Add a user in the OIDC identity provider (I created an account with the email address testanon@example.com)
* View the application in FusionAuth and get the login URL.
* Append `idp_hint` with the value of the OIDC identity provider (not sure that is important, but that is what I was using).
* You end up with a url like this: https://local.fusionauth.io/oauth2/authorize?client_id=85a03867-dccf-4882-adde-1a79aeec50df&response_type=code&redirect_uri=https%3A%2F%2Ffusionauth.io&idp_hint=f5153db1-f008-4088-9ff6-7aa19ddc117b
* Open an incognito window.
* Visit the url, login as the anonuser@example.com user
* You are sent to fusionauth.io/... with the authorization code. All is good in the world.
* Close the incognito window.
* Open an incognito window.
* Visit the url, login as the anonuser@example.com user
* Ka-boom. You see the error message displayed in the screenshot and if you look at the system logs, you'll see output similar to below.

### Expected behavior

No exception in the system logs, login to complete.

### Screenshots
<img width="2032" alt="Screen Shot 2021-09-28 at 12 11 14 PM" src="https://user-images.githubusercontent.com/91825/135142256-3d0f229e-1781-4393-aee6-cc57348e4436.png">

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

### Additional context

Logfile excerpt from system logs:

```
2021-09-28 11:50:40.248 AM ERROR io.fusionauth.app.primeframework.error.ExceptionExceptionHandler - An unhandled exception was thrown
org.apache.ibatis.exceptions.PersistenceException: 
### Error updating database.  Cause: java.sql.SQLIntegrityConstraintViolationException: Column 'encryption_scheme' cannot be null
### The error may exist in io/fusionauth/api/domain/UserMapper.xml
### The error may involve defaultParameterMap
### The error occurred while setting parameters
### SQL: INSERT INTO identities (users_id, breached_password_last_checked_instant, breached_password_status, connectors_id, email, encryption_scheme, factor, insert_instant, last_login_instant, last_update_instant, password, password_change_reason, password_change_required, password_last_update_instant, salt, tenants_id, username, username_index, username_status, verified, status)       VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, UPPER(?), ?, ?, ?)
### Cause: java.sql.SQLIntegrityConstraintViolationException: Column 'encryption_scheme' cannot be null
        at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:30)
        at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:196)
        at org.apache.ibatis.session.defaults.DefaultSqlSession.insert(DefaultSqlSession.java:181)
        at jdk.internal.reflect.GeneratedMethodAccessor117.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.apache.ibatis.session.SqlSessionManager$SqlSessionInterceptor.invoke(SqlSessionManager.java:350)
        at com.sun.proxy.$Proxy53.insert(Unknown Source)
        at org.apache.ibatis.session.SqlSessionManager.insert(SqlSessionManager.java:236)
        at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:62)
        at org.apache.ibatis.binding.MapperProxy$PlainMethodInvoker.invoke(MapperProxy.java:145)
        at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:86)
        at com.sun.proxy.$Proxy85.createIdentity(Unknown Source)
        at io.fusionauth.api.service.user.DefaultUserService._updateAllowConnectorIdChange(DefaultUserService.java:588)
        at org.mybatis.guice.transactional.TransactionalMethodInterceptor.invoke(TransactionalMethodInterceptor.java:96)
        at org.mybatis.guice.transactional.TransactionalMethodInterceptor.invoke(TransactionalMethodInterceptor.java:96)
        at org.mybatis.guice.transactional.TransactionalMethodInterceptor.invoke(TransactionalMethodInterceptor.java:96)
        at org.mybatis.guice.transactional.TransactionalMethodInterceptor.invoke(TransactionalMethodInterceptor.java:96)

```

Both the main fusionauth instance at local.fusionauth.io and the OIDC connection running at local2.fusionauth.io were using mysql, but they were talking to different databases.

**Comment by robotdan** [comment] 2021-09-28 21:57
Duplicate of https://github.com/FusionAuth/fusionauth-issues/issues/1316

**Closed** 2021-09-28 21:57 UTC
Labels: bug, duplicate
