### ISSUE TITLE
Logout endpoint doesn't log the user out of FusionAuth

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-issues#1699] opened 2022-04-24 21:25 UTC
### Description 
Calling the logout endpoint with a different client doesn't log the user out of the FusionAuth admin application, even if the logout behavior is 'all applications'.

### Affects versions
1.36.4

### Steps to reproduce

* create a second application, make sure that logout behavior is 'all applications'
* register the user for both the second application and FusionAuth
* Find the logout url of the second application: Logout endpoint doesn't log the user out of FusionAuth: https://example.fusionauth.io/oauth2/logout?client_id=85a03867-dccf-4882-adde-1a79aeec50df 
* Log into FusionAuth admin panel
* Visit the logout url

Observe you are still logged into FusionAuth

### Expected behavior
Either:

* user should be logged out of FusionAuth

or

* this should be documented as a known limitation

### Platform
(Please complete the following information)
 - Device: [e.g. Desktop, iPhone X, Pixel 3, etc]
 - OS: [e.g. iOS, macOS, Windows ME]
 - Browser + version [e.g. chrome, safari plus a version]
 - Database [MySQL | PostgresSQL] & and version

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

### Additional context

First mentioned here, but I was able to replicate: https://fusionauth.io/community/forum/topic/1751/does-the-oauth2-logout-endpoint-log-the-user-out-of-fusionauth

**Comment by spwitt** [comment] 2022-04-27 22:37
This is working as designed. I will document this as a known limitation but leave the issue open in case others would like to see this change.

**Comment by mooreds** [comment] 2022-04-27 22:40
@spwitt can you explain why this is working as designed, please?

**Comment by robotdan** [comment] 2022-04-28 15:23
The short answer is I don't remember. 

But each application in a single logout scenario can decide if they wish to log out or not, so in that perspective, the FusionAuth can do whatever it wants. 

We can review to see if we can identify the reason it was coded this way to begin with, and if it still makes sense. This behavior existed prior to removing the HTTP stateful sessions and moving to stateless token sessions, so it is possible the current design point is related to this old behavior and no longer applies. Needs more investigation. 

But for now since this is the current behavior, I'd rather not change it unless we understand the use case and how the current behavior negatively affects anyone.

**Comment by mooreds** [comment] 2022-04-28 15:54
@robotdan okay, I tagged the user in the forum post, hopefully they'll come over and give more details about what they are looking for.

**Comment by spwitt** [comment] 2022-04-28 16:39
For now, the doc changes are being handled in
- https://github.com/FusionAuth/fusionauth-site/issues/1346

**Comment by yuezhou1998** [comment] 2022-04-28 16:40
Thanks to the team for looking into this, I am the original poster from https://fusionauth.io/community/forum/topic/1751/does-the-oauth2-logout-endpoint-log-the-user-out-of-fusionauth/5 and wanted to clarify our use case.

The scenario we are trying to handle is as follows:

1. An admin registered to FusionAuth decides to sign into FusionAuth and establishes an SSO session
2. After signing in, they access another Oauth-configured application, after they are done with it, they then hit the sign out button for this application. This signout button corresponds to the _oauth2/logout?clientId=_ url, and the application logout behaviour is set to "all applications". The clientId supplied is that of the Oauth-configured application, not that of FusionAuth.
3. After signing out, the user's fusionauth.sso cookie is revoked and the application-specific logout endpoint is triggered for all applications, except for FusionAuth.
4.  As FusionAuth's session is reliant on the fusionauth.session cookie (my assumption), a valid session remains strictly for the FusionAuth application. This means the admin user, despite signing out of all other Oauth-configured applications, still has a valid session solely within the FusionAuth application.
5. A non-admin user then uses the same browser and can access the FusionAuth application, despite not being registered for it, they are able to access it as they are using the session from the previous admin user, this essentially grants the non-admin user all the FusionAuth registrations the admin user had. 

According to this: https://fusionauth.io/docs/v1/tech/guides/single-sign-on, it seems like the FusionAuth application should be destroying its own session when a call to the oauth/logout endpoint is performed on the Pied Piper application, I don't believe this is currently happening. Unless if there's a difference in terminology between "local" session and "FusionAuth" sessions.

**Closed** 2022-08-10 18:52 UTC
Labels: enhancement, documentation, architecture
