### ISSUE TITLE
Tenant account page not accessible without keep me signed in

### ISSUE THREAD

**Issue by jswinth-cd** [FusionAuth/fusionauth-issues#1843] opened 2022-08-26 15:01 UTC
### Description
When sending user to account pages, they are not accessible unless the user checks the (non-defaulted) box to keep them logged in.  Instead the user is simply asked to login again and again until they click the box during login.

https://xxx.fusionauth.io/account/?client_id=xxx

**Comment by mooreds** [comment] 2022-08-31 13:59
Hmmm. 

Thanks for filing the issue, @jswinth-cd !

So you are saying that this is happening:

* User logs into application A and doesn't select 'keep me logged in'
* User visits the link to the self service account management link
* User is required to log in.
* If user logs in without checking the box, they are sent back to the login page.
* If user logs in and checks the box, they are allowed to visit the self service account management page.

Is that correct?

**Comment by robotdan** [comment] 2022-08-31 14:29
This is working as designed. The self-service account pages leverage the SSO session. 

Duplicate of 
- https://github.com/FusionAuth/fusionauth-issues/issues/1546

**Closed** 2022-08-31 14:30 UTC
Labels: duplicate, working as designed

**Comment by jswinth-cd** [comment] 2022-08-31 15:02
@mooreds, yes you have it correct.

@robotdan, sorry I did not locate the duplicate.  The "as designed" nature of your reply seems odd compared to other IDP integrations and the user experience this creates for self-service password/mfa management.

The workaround in #1546 to force the remember me will likely be what we are forced to use for now.

Thanks for your consideration.
