### ISSUE TITLE
Error messages are not really useful

### ISSUE THREAD

**Issue by blanchonvincent** [FusionAuth/fusionauth-issues#72] opened 2019-01-30 12:43 UTC
The error messages from the API are not descriptive and today pretty useless.
Having code 500 with "FusionAuth encountered an unexpected error. Please contact support for assistance." does not help the developer.

For example, if you create a user with an existing ID or username, you will get this kind of error and it can take hours to figure out why it is not working.

Could you work on better error messages?

**Comment by robotdan** [comment] 2019-01-30 13:10
Hi @blanchonvincent thanks for letting us know. The `500` status code with a message such as `FusionAuth encountered an unexpected error. Please contact support for assistance.` is truly an exception message. Generally speaking this means either the user did something we completely did not expect, or we have a bug. 

So I agree, that is a vague message, but it is intentional. Something happened that we did not expect, this is likely a bug, and you should open a GitHub issue so we can resolve it. The correct API response for this type of scenario is a `400` with a JSON body describing what field is in error and why.  We do try very hard to make sure whenever possible the error response is helpful to the developer. 

For example, here is what I would have expected:

```
{
  "fieldErrors" : {
    "user.username", "[duplicate]user.username", "A User with username = [bob] already exists."
  }
}
```

Can you share the JSON body and API that was causing this exception? Was it just a duplicate Id or username? We have lots of tests for this type of scenario, so I'm wondering if there is an additional variable I'm not seeing?  

I can try to recreate, but if you could provide the exception from the log that would be helpful. 
Thanks.

**Comment by blanchonvincent** [comment] 2019-01-30 14:21
Thank you for the details.
It happens when we create a user with an existing ID **and** username actually. Basically, we assigned our own ID and username for each user, so in our unit tests, sometime if something goes wrong it tries to create the same user again.

**Comment by robotdan** [comment] 2019-01-30 14:54
Strange, there should be an exception in the `fusionauth-app.log` which should tell me what happened. If you're using the RPM or Debian packages the log file will be located `/usr/local/fusionauth/logs/fusionauth-app.log`.

**Comment by blanchonvincent** [comment] 2019-01-30 14:59
I did not check this file at all since I knew what was the error. I was just worry it could happens for the other developers, but if we can get details easily from this file, it will make things easier :)
We will check this file and I will let you know.

**Comment by robotdan** [comment] 2019-01-30 15:03
Great, yes please do so, this is a bug, you should have received a much better error message. I have been unable to recreate, so I must be missing some other variable, are you using tenants?

**Comment by robotdan** [comment] 2019-02-05 18:33
Hi @blanchonvincent - were you able to capture any of the log when you see this symptom? 

If you can get the logs, I should be able to identify the root cause, if not - that is fine we can always re-open if you recreate. 

Thanks.

**Comment by robotdan** [comment] 2019-03-19 00:15
Closing as un-reproducible, please do re-open if you see again or have the log. Thanks.

**Closed by robotdan** 2019-03-19 00:15 UTC
Labels: bug

**Comment by cg3y** [comment] 2019-10-22 19:01
Unreproducible? Seriously? The issue is that the logs aren't useful when exceptions are thrown for a reason that your developers haven't covered (and it's not possible to cover every one in such a large code base). The OP merely provided an example, the ticket wasn't meant to have you work on the example provided (that you couldn't reproduce) but rather focus on useless error messages and correct that. In fact I just got one today and it is, in fact, not useful. 

I would suggest that if the debug is enabled, then you should simply catch the entire exception stack along with any internal messages and post those to the event log. This "unexpected error" is pointless. And it's clear people get it for a variety of reasons. I'm getting it today attempting to setup a federated IDP using SAML2. I get redirected to my IDP just fine, sign in there, get authenticated, the SAML assertion is sent back to fusionauth...and I get this "unexpected error". Unhelpful to say the least. 

So rather than close a valid ticket as unreproducible (seriously, you aren't able to get a useless error message in ANY of your testing??? Then you need to expand your testing to be able to produce the "unexpected error" error message others are getting) reopen this and actually work on your error messages (or post the stack and inner exception trace to the log when debug enabled).
