### ISSUE TITLE
User account override when doing social login

### ISSUE THREAD

**Issue by LohithBlaze** [FusionAuth/fusionauth-issues#777] opened 2020-07-28 14:36 UTC
### Description 
User account is overriden when doing social login. When we create a new user in fusionauth with email id and password and if we use the same email id is used to login using google, login API is returning change password id.

### Affects versions
any version <1.18.3

### Steps to reproduce
1. Create a user with email id and password using registration API
2. logout using API
3. login to google with the same email id
4. logout from fusionauth again
5. Use the username and password from the initial time you had created the user
6. Login fails and returns changePassword Id

### Expected behavior
Login should be successfull and should return jwt token

**Comment by robotdan** [comment] 2020-07-28 18:45
I'm unable to recreate. Are you doing anything in your reconcile lambda?

**Comment by LohithBlaze** [comment] 2020-07-29 03:14
No, I'm doing these operations through API.

1. Create a user with email id and password using registration API(create user and registration API)
2. logout using API(logout api)
3. login to google with the same email id(identity provider login with create registrations enabled)
4. logout from fusionauth again(logout api)
5. Use the username and password from the initial time you had created the user(login API)
6. Login fails and returns changePassword Id(response from login API is changePasswordId )

Does fusionauth override the password which was already set when we use social login.

**Comment by andrewpai** [comment] 2024-04-26 23:16
Closing, as I am unable to reproduce this behavior.

**Closed by andrewpai** 2024-04-26 23:16 UTC
Labels: triage
