### ISSUE TITLE
FusionAuth v. 1.19.5 not start but 1.19.4 yes

### ISSUE THREAD

**Issue by mao75** [FusionAuth/fusionauth-issues#873] opened 2020-09-16 15:32 UTC
### Description 
On a clean system, after the installtion, the service not start.
In /var/log/message I found:
Sep 16 19:22:02 localhost systemd[1]: Started FusionAuth App.
Sep 16 19:22:02 localhost catalina.sh[1442]: You are using a deprecated configuration property of [fusionauth-app.cookie-same-site-policy] in [fusionauth.properties]. The new variable name is [fusionauth-app.http.cookie.same-site-policy]
Sep 16 19:22:02 localhost catalina.sh[1442]: /usr/local/fusionauth/fusionauth-app/apache-tomcat/bin/setenv.sh: line 91: : bad substitution
Sep 16 19:22:02 localhost systemd[1]: fusionauth-app.service: Main process exited, code=exited, status=1/FAILURE
Sep 16 19:22:02 localhost systemd[1]: fusionauth-app.service: Failed with result 'exit-code'.

### Affects versions
1.19.5

### Steps to reproduce
Yesterday (20200915) i tried the installation on a Centos8 minimal: it worked (yesterday was installed 1.19.4).
Today (20200916) I want to replicate the installation but I found the problem.

1.  install rsyslog and enable/start it
    yum install rsyslog -y
    systemctl enable rsyslog
    systemctl start rsyslog
2. install FusionAuth with
     sh -c "curl -fsSL https://raw.githubusercontent.com/FusionAuth/fusionauth-install/master/install.sh | sh"
3. try start service
    service fusionauth-app start
4. the service does not start and in the /var/log/messages there is information about the error

### Platform
 - Device: virtual machine 64bit
 - OS: Centos 8.2 minimal 
 - Database PostgresSQL 12.4

### Additional context
I also changed fusionauth-app.cookie-same-site-policy in fusionauth-app.http.cookie.same-site-policy
on the config file. The problem persist.

**Comment by mao75** [comment] 2020-09-16 15:34
Issue with title "**setenv.sh: line 91: : invalid variable name**" is the same

**Comment by robotdan** [comment] 2020-09-16 15:47
Thanks for opening the issue @mao75 , this looks to be a duplicate of https://github.com/FusionAuth/fusionauth-issues/issues/870, so we'll track that one.

**Closed by robotdan** 2020-09-16 15:48 UTC
