### ISSUE TITLE
PATCH clears out language value, username and timezone from registration when updating registration.data with a PATCH

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-issues#667] opened 2020-06-03 20:13 UTC
### Steps to reproduce
1. Create a user in the admin ui. Assign them to an application. Add a language to the registration.
2. Run this curl command (assuming you've created an API key with access):
```
curl -XPATCH -H "Content-type: application/json" -H "Authorization: $API_KEY" 'http://localhost:9011/api/user/registration/<userid>'  -d '{"registration" : { "applicationId" : "<appid>", "data" : {"test" : "data2"} } }'
```
3. Examine the user. You'll see that `registration.data` is set correctly, but that the language value has been reset to null.

Based on testing, the `username` and `timezone` registration attributes are also cleared.

### Expected behavior

A `PATCH` request should not modify any registration data that is not part of the request, including language.

### Platform

Issue is present in 1.15.8 and 1.16.1. 

### Related or duplicate
- https://github.com/FusionAuth/fusionauth-issues/issues/441 
- https://github.com/FusionAuth/fusionauth-issues/issues/534
- https://github.com/FusionAuth/fusionauth-issues/issues/667 (this)
- https://github.com/FusionAuth/fusionauth-issues/issues/956

### Additional context

Originally reported on this forum post: https://fusionauth.io/community/forum/topic/144/user-registration-patch-merge-behavior

**Comment by robotdan** [comment] 2020-06-03 20:36
I think this is a known limitation of patch.
See this for more info.
https://github.com/FusionAuth/fusionauth-issues/issues/441

**Comment by mooreds** [comment] 2020-06-03 20:56
Are language, username, and timezone all arrays? #441 seems to be talking only about arrays, unless I'm missing something.

**Comment by voidmain** [comment] 2020-06-03 21:08
Preferred languages is an array. Username and timezone aren't. Username is a unique identifier, so that might also behave differently than other attributes. Timezone is a mystery though. We'll have to write a test to verify what is happening with each of those.

**Comment by robotdan** [comment] 2022-08-31 19:03
Close as duplicate of https://github.com/FusionAuth/fusionauth-issues/issues/667.

**Closed** 2022-08-31 19:04 UTC
Labels: bug, duplicate
