### ISSUE TITLE
Add User: incorrect years in "Birthdate" date picker

### ISSUE THREAD

**Issue by ceefour** [FusionAuth/fusionauth-issues#561] opened 2020-04-18 16:03 UTC
### Description 
The years go into the future.

### Steps to reproduce
1. Click Add user
2. Click on Birthdate
3. The earliest year selectable is 2010. I doubt if any current FusionAuth developers can fill this field ^_^

### Expected behavior
Some years ago (perhaps 100 years ago?) up to this year.

### Screenshots

![image](https://user-images.githubusercontent.com/24123/79642602-be0a2680-81c8-11ea-8e61-7a92d7cc5904.png)

### Platform
(Please complete the following information)
 - Device: Web
 - OS: Ubuntu 18.04
 - Browser + version: Chrome 81

**Comment by robotdan** [comment] 2020-07-16 15:06
Bug is likely in the date picker widget. 

https://github.com/inversoft/prime.js/blob/master/src/main/js/Widgets/DateTimePicker.js
https://github.com/inversoft/prime.js/blob/master/src/test/js/Widgets.DateTimePickerTest.js

If anyone wants to take a crack at it and fix it, a PR would be great.

**Comment by amans330** [comment] 2020-12-17 19:34
@robotdan 
• The expected behaviour suggests that the years should start from 100 years ago, that's okay?
• Displaying the list from 1920 might look weird, almost every time people would have to scroll down a lot. A better option would be to have years in decreasing order starting from the current year?

**Comment by robotdan** [comment] 2020-12-17 20:18
If you look at the code ( https://github.com/inversoft/prime.js/blob/7ae67b0e586e98f454750c942d1c53bc2983d59a/src/main/js/Widgets/DateTimePicker.js#L256 ) you'll see the intended behavior is to show 10 years in either direction of the current value. I would start with just fixing it so the behavior matches the intention.

**Comment by amans330** [comment] 2020-12-17 20:45
@robotdan I think you misunderstood. I corrected the code already, now the year range would be 100 years before the current year to the current year. What I was asking is should I go for 100 years or maybe 90 or 80 years.

**Comment by ceefour** [comment] 2020-12-17 23:39
@amans330 I agree for BirthDate, years should be listed decreasing

**Comment by robotdan** [comment] 2020-12-17 23:44
@amans330 not sure I follow. Once you have the bug fixed, you can submit a PR and I can look at it, I'm sure your questions ill be clearer once I look at the code. Thanks!

**Comment by amans330** [comment] 2020-12-17 23:54
PR --> https://github.com/inversoft/prime.js/pull/25

**Comment by robotdan** [comment] 2022-11-17 17:53
We'll be moving to an HTML 5 date picker.

**Closed by robotdan** 2022-11-17 17:53 UTC
Labels: bug

**Comment by robotdan** [comment] 2022-11-17 18:23
here is a decent replacement using HTML 5 in a self service form. This just an example, but it will set the min and max age for birthdays based upon the current year. 

```
<div class="form-row">
  [#local currentYear = .now?date?string("YYYY") /]
  [#local minYear = (currentYear?number - 120)  + "-01-01"/]
  [#local maxYear = (currentYear?number - 10) + "-01-01"/]
  <label for="${fieldId}">${label} [#if field.required] <span class="required">*</span>[/#if]</label>
  <input id="${fieldId}" type="date" name="${key}" [#if field.key = "user.birthDate"]min="${minYear}" max="${maxYear}"[/#if]/>
       </div>
```
