### ISSUE TITLE
setenv.sh: line 91: : invalid variable name

### ISSUE THREAD

**Issue by arunmg007** [FusionAuth/fusionauth-issues#872] opened 2020-09-16 15:14 UTC
### Description
The Docker instance of the fusionauth app failed to start with error

fusionauth_1  | You are using a deprecated configuration property of [fusionauth-app.cookie-same-site-policy] in [fusionauth.properties]. The new variable name is [fusionauth-app.http.cookie.same-site-policy]
fusionauth_1  | /usr/local/fusionauth/fusionauth-app/apache-tomcat/bin/setenv.sh: line 91: : invalid variable name
documents_fusionauth_1 exited with code 1
fusionauth_1  | /usr/local/fusionauth/fusionauth-app/apache-tomcat/bin/setenv.sh: line 91: : invalid variable name
documents_fusionauth_1 exited with code 1

Not Good with these, but finally decided to # out the following lines to get this started.

88   if [ -n "${!newEnvName}" ]; then
89     appendToVariable "${envVarName}" "${cmdOption}${!newEnvName}"
90     return
91 #  elif [ -n "${!oldEnvName}" ]; then
92 #    echo "You are using a deprecated environment variable of [${oldEnvName}]. The new variable name is [${newEnvName}]"
93 #    appendToVariable "${envVarName}" "${cmdOption}${!oldEnvName}"
94 #    return
95   elif [ -f "${FUSIONAUTH_CONFIG_DIR}/fusionauth.properties" ]; then
96     if [ -n "${newName}" ]; then

**Comment by robotdan** [comment] 2020-09-16 15:47
Thanks for the issue @arunmg007. This looks to be a duplicate of https://github.com/FusionAuth/fusionauth-issues/issues/870 so we'll track that one.

**Closed by robotdan** 2020-09-16 15:47 UTC

**Comment by arunmg007** [comment] 2020-09-16 17:29
Thanks Robot
