### ISSUE TITLE
Adding radio button or dropdown custom form field doesn't save values the first time you save it

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-issues#865] opened 2020-09-15 16:45 UTC
### Description 

If you create a new custom drop down or radio button and add values separated by newlines:

```
a
b
c
```

And click save, these option values won't be saved.

### Affects versions

1.19.4

### Steps to reproduce

1. Create a new custom form field.
1. Store the data in `registration.data.testradio`
1. Change the control to 'radio button' (or dropdown)
1. Add values to the options list (separated by newlines)
1. Click save

Go back and edit the new custom field. You won't see any of your options.

### Expected behavior
I'd expect the values for options to be saved when they are first added.

### Platform

Saw on Firefox and Safari on the mac.

### Additional context

No error messages showed up in the javascript console. No error messages showed up in the fusionauth app logs.

You can workaround this by simply editing the existing custom field and re-adding your options.

**Comment by iveelsm** [comment] 2020-10-08 21:23
It looks like this was fixed with some of the recent changes to those code paths. This is not reproducible anymore so we can call a wrap on this one. @bguyza and I discussed and it was likely fixed with the changes to the Form Fields for https://github.com/FusionAuth/fusionauth-issues/issues/867

Let me know if you see otherwise @mooreds

**Comment by mooreds** [comment] 2020-10-08 21:25
If you tried to repro and couldn't, that's good enough for me @iveelsm !

**Comment by robotdan** [comment] 2020-10-08 23:05
Sounds good, @iveelsm can you confirm we have a test somewhere to cover this use case? It will likely be easiest to test this using the custom user edit or the custom registration edit tests.

**Comment by iveelsm** [comment] 2020-10-08 23:06
I have the test written. I will push it into @bguyza 's branch.

**Comment by voidmain** [comment] 2020-10-14 21:39
Thought I would mention that I saw this on `demo.fusionauth.io` today while giving a demo. I had to save a Select box field twice to get it to work.

**Comment by robotdan** [comment] 2020-10-15 03:23
@iveelsm can you link your commit on this issue, I couldn't find it.

**Comment by iveelsm** [comment] 2020-10-15 04:33
@robotdan I unfortunately didn't link the commits. Here are the SHAs associated with this one:

*  [c7bbf32f6aa3a164ee6a4e48273428a82ce0efdc](https://github.com/FusionAuth/fusionauth-app/commit/c7bbf32f6aa3a164ee6a4e48273428a82ce0efdc)
* [720adb8c2500d811d057c7523eaf1278e436e3a4](https://github.com/FusionAuth/fusionauth-app/commit/720adb8c2500d811d057c7523eaf1278e436e3a4)
* [a24b0441fae0846788d88ef852711cb5623279de](https://github.com/FusionAuth/fusionauth-app/commit/a24b0441fae0846788d88ef852711cb5623279de)

The test will be linked here in a second.

**Closed** 2020-10-26 18:14 UTC
Labels: bug
