### ISSUE TITLE
Migration error with mysql

### ISSUE THREAD

**Issue by nulian** [FusionAuth/fusionauth-issues#482] opened 2020-02-20 13:05 UTC
On mysql 8.0.18 the 1.15 migration seems to fail on the DELIMITER part at the function creation.
If I just execute the create function it works fine.

`
DELIMITER |
CREATE FUNCTION bin_to_uuid(b BINARY(16))
  RETURNS CHAR(36) DETERMINISTIC
BEGIN
  DECLARE HEX CHAR(32);
  SET HEX = HEX(b);
  RETURN LOWER(CONCAT(LEFT(HEX, 8), '-', MID(HEX, 9, 4), '-', MID(HEX, 13, 4), '-', MID(HEX, 17, 4), '-', RIGHT(HEX, 12)));
END
|
DELIMITER ;
`

**Comment by robotdan** [comment] 2020-02-20 18:32
Thanks for letting us know. We do run against several versions of MySQL, strange we did not encounter this issue. 

We'll take a look and see if we need to adjust the syntax of this migration. 

It sounds like you have identified a workaround for the time being?

**Comment by trex** [comment] 2020-02-20 21:57
I was able to recreate this with mysql `8.0.16` on upgrade path from FusionAuth `1.14.0` to `1.15.2`.

The issue is that `DELIMITER` is a command that is honored by the mysql CLI and very few other clients.  Our maintenance mode establishes a jdbc connection to mysql, and jdbc does not support the `DELIMITER` command.  I have a fix for this that will go out in `1.15.3`.

Thank you for reporting @nulian!

**Comment by robotdan** [comment] 2020-02-20 22:29
@trex can you update the known issues in the release notes so we can warn users about this potential error? 

It sounds like a work around then is to perform the schema upgrade manually using our schema zip and use a MySQL CLI to complete the schema upgrade? - or wait for `1.15.3` ?

**Comment by trex** [comment] 2020-02-20 23:52
@robotdan I will update the release notes and note the workaround.

**Closed** 2020-02-27 22:55 UTC
Labels: bug
